const fs = require('fs');
const path = require('path');

const newKeys = {
  en: {
    "common.default": "Default",
    "common.stopAudio": "Stop Audio",
    "common.listenAudio": "Listen",
    "profile.tapToSetDefault": "Tap to set default",
    "habits.fastingEatingWindowGuidelines": "Eating window guidelines: Wind up dinner by 7 PM, take breakfast by 9 AM. Maintain your calorie intake, and avoid processed and unhealthy food.",
    "env.pulmonologistConsultDesc": "Your score flags significant particulate, chemical, or passive smoke inhalation risks. Consider speaking to a pulmonologist to check lung health.",
    "env.airExposureRecDesc": "Reduce your exposure to air pollution and passive second-hand smoke where possible. Use an N95 mask and an air purifier when appropriate.",
    "env.naturalKitchenGuidelines": "Natural Kitchen & Utensil Guidelines",
    "env.lookingForPlasticFree": "Looking for plastic-free stainless steel or glass kitchen storage containers?",
    "env.doneWithKitchenCategory": "Done with Kitchen Category",
    "env.airSafetyDesc": "Reduce your exposure to air pollution where possible. Use an N95 mask and an air purifier when appropriate.",
    "logFasterWithAi": "Log {{target}} 10x Faster with AI!",
    "aiCheckinNotice": "Did you know? You can answer a quick 60-second voice check-in or upload reports with our AI Assistant — no manual typing needed!",
    "continueManually": "Continue Manually",
    "mia.lifestyleTitle": "🌿 4 Personalised Changes for You",
    "mia.lifestyleOutro": "📅 Try these 4 steps today and come back tomorrow to tell me how you feel.",
    "mia.followUpCardDesc": "I've saved your personalised 4-step plan. Please try these steps today and return tomorrow to check in with me. We'll decide your next steps together!",
    "mia.feelBetter": "I feel better!",
    "mia.stillStruggling": "Still struggling",
    "mia.feelBetterChoice": "I feel noticeably better",
    "mia.stillStrugglingChoice": "Still struggling / Feeling worse",
    "mia.continueCardTitle": "That's wonderful — you're making real progress!",
    "mia.continueCardDesc": "Keep going with your 4 lifestyle changes for the next 2 full weeks. Small consistent steps create lasting change at the cellular level. Come back anytime you need support. You are doing brilliantly! 💚",
    "mia.returningBetter": "I feel noticeably better",
    "mia.returningSame": "About the same — no real change",
    "mia.returningWorse": "I feel worse actually",
    "mia.returningSome": "I tried some things but not all",
    "gia.whatToPrepare": "💡 What to prepare for your consultation:",
    "gia.quickToolsTitle": "Gia's Genetic Counseling Quick Tools",
    "gia.highRiskSyndromeGuides": "🧬 High-Risk Syndrome Guides",
    "gia.brcaDesc": "Hereditary breast & ovarian cancer red flags",
    "gia.lynchDesc": "Colorectal & uterine hereditary risk factors",
    "gia.pedigreeDesc": "How to prepare family medical history tree",
    "gia.jumpToQuestion": "⚡ Jump to Specific Genetic Question",
    "gia.jumpPanelTest": "What panel test do I need?",
    "gia.jumpPanelTestPrompt": "Which multi-gene panel testing should I consider based on my family tree?",
    "gia.jumpGinaProtection": "Genetic Discrimination Protection (GINA)",
    "gia.jumpGinaProtectionPrompt": "Explain genetic discrimination protection laws and health insurance implications.",
    "gia.jumpDtcVsClinical": "Direct-to-Consumer vs Clinical Gene Testing",
    "gia.jumpDtcVsClinicalPrompt": "What is the difference between 23andMe DTC tests and clinical diagnostic germline testing?",
    "gia.jumpVariantMeaning": "Pathogenic Variant Meaning",
    "gia.jumpVariantMeaningPrompt": "What is a Variant of Uncertain Significance (VUS) vs Pathogenic Mutation?",
    "gia.inputPlaceholder": "Ask Gia about cancer genes, guidelines, or risk...",
    "gia.askFollowupOrBook": "Ask Gia any follow-up question or book a counselor below for professional panel ordering."
  },
  ta: {
    "common.default": "இயல்புநிலை",
    "common.stopAudio": "ஆடியோவை நிறுத்து",
    "common.listenAudio": "கேட்கவும்",
    "profile.tapToSetDefault": "இயல்புநிலையாக அமைக்க தட்டவும்",
    "habits.fastingEatingWindowGuidelines": "உணவு உண்ணும் கால வழிகாட்டுதல்கள்: இரவு உணவை இரவு 7 மணிக்குள் முடிக்கவும், காலை உணவை காலை 9 மணிக்குள் எடுக்கவும். கலோரிகளைப் பராமரிக்கவும், பதப்படுத்தப்பட்ட உணவுகளைத் தவிர்க்கவும்.",
    "env.pulmonologistConsultDesc": "உங்கள் மதிப்பீடு காற்று மாசுபாடு அல்லது புகை உள்ளிழுக்கும் அபாயங்களைக் குறிக்கிறது. நுரையீரல் ஆரோக்கியத்தைப் பரிசோதிக்க ஒரு நுரையீரல் மருத்துவரிடம் ஆலோசனை பெறவும்.",
    "env.airExposureRecDesc": "காற்று மாசுபாடு மற்றும் பிறர் விடும் புகையிலிருந்து உங்களைப் பாதுகாத்துக் கொள்ளுங்கள். N95 முகக்கவசம் மற்றும் காற்று சுத்திகரிப்பானைப் பயன்படுத்தவும்.",
    "env.naturalKitchenGuidelines": "இயற்கையான சமையலறை மற்றும் பாத்திர வழிகாட்டுதல்கள்",
    "env.lookingForPlasticFree": "பிளாஸ்டிக் இல்லாத துருப்பிடிக்காத எஃகு அல்லது கண்ணாடி சேமிப்பு கொள்கலன்களைத் தேடுகிறீர்களா?",
    "env.doneWithKitchenCategory": "சமையலறை பிரிவு முடிந்தது",
    "env.airSafetyDesc": "முடிந்தவரை காற்று மாசுபாட்டின் வெளிப்பாட்டைக் குறைக்கவும். பொருத்தமான போது N95 முகக்கவசம் மற்றும் காற்று சுத்திகரிப்பானைப் பயன்படுத்தவும்.",
    "logFasterWithAi": "AI மூலம் {{target}} பதிவை 10 மடங்கு விரைவாகப் பதிவு செய்யுங்கள்!",
    "aiCheckinNotice": "உங்களுக்குத் தெரியுமா? எங்கள் AI உதவியாளருடன் 60 வினாடி குரல் பதிவு செய்யலாம் அல்லது அறிக்கைகளைப் பதிவேற்றலாம் — தட்டச்சு செய்யத் தேவையில்லை!",
    "continueManually": "கைமுறையாகத் தொடரவும்",
    "mia.lifestyleTitle": "🌿 உங்களுக்கான 4 தனிப்பயனாக்கப்பட்ட மாற்றங்கள்",
    "mia.lifestyleOutro": "📅 இந்த 4 படிகளை இன்று முயற்சித்துப் பார்த்து, நாளை உங்கள் உணர்வை என்னிடம் பகிருங்கள்.",
    "mia.followUpCardDesc": "உங்கள் தனிப்பயனாக்கப்பட்ட 4-படி திட்டத்தைச் சேமித்துள்ளேன். தயவுசெய்து இன்று இவற்றை முயற்சி செய்து, நாளை என்னுடன் கலந்தாலோசிக்கவும். அடுத்த படிகளை நாம் இணைந்து தீர்மானிப்போம்!",
    "mia.feelBetter": "நன்றாக உணர்கிறேன்!",
    "mia.stillStruggling": "இன்னும் சிரமப்படுகிறேன்",
    "mia.feelBetterChoice": "நான் குறிப்பிடத்தக்க அளவு நன்றாக உணர்கிறேன்",
    "mia.stillStrugglingChoice": "இன்னும் சிரமப்படுகிறேன் / மோசமாக உணர்கிறேன்",
    "mia.continueCardTitle": "அற்புதம் — நீங்கள் உண்மையான முன்னேற்றம் அடைந்து வருகிறீர்கள்!",
    "mia.continueCardDesc": "அடுத்த 2 முழு வாரங்களுக்கு உங்கள் 4 வாழ்க்கைமுறை மாற்றங்களைத் தொடருங்கள். சிறிய நிலையான படிகள் செல்லுலார் மட்டத்தில் நீடித்த மாற்றத்தை உருவாக்குகின்றன. உதவி தேவைப்படும்போது எப்போது வேண்டுமானாலும் வாருங்கள். சிறப்பாகச் செய்கிறீர்கள்! 💚",
    "mia.returningBetter": "நான் குறிப்பிடத்தக்க அளவு நன்றாக உணர்கிறேன்",
    "mia.returningSame": "ஏறக்குறைய அதே நிலை — பெரிய மாற்றமில்லை",
    "mia.returningWorse": "உண்மையில் மோசமாக உணர்கிறேன்",
    "mia.returningSome": "சிலவற்றை முயற்சித்தேன், எல்லாவற்றையும் அல்ல",
    "gia.whatToPrepare": "💡 உங்கள் மருத்துவ ஆலோசனைக்குத் தயார் செய்ய வேண்டியவை:",
    "gia.quickToolsTitle": "ஜியாவின் மரபணு ஆலோசனை விரைவு கருவிகள்",
    "gia.highRiskSyndromeGuides": "🧬 உயர் அபாய நோய்க்குறி வழிகாட்டிகள்",
    "gia.brcaDesc": "பரம்பரை மார்பகம் மற்றும் கருப்பை புற்றுநோய் எச்சரிக்கை அறிகுறிகள்",
    "gia.lynchDesc": "பெருங்குடல் மற்றும் கருப்பை பரம்பரை அபாய காரணிகள்",
    "gia.pedigreeDesc": "குடும்ப மருத்துவ வரலாற்று மரபு வரைபடத்தை எவ்வாறு தயாரிப்பது",
    "gia.jumpToQuestion": "⚡ குறிப்பிட்ட மரபணு கேள்விக்குச் செல்லவும்",
    "gia.jumpPanelTest": "எனக்கு என்ன பேனல் சோதனை தேவை?",
    "gia.jumpPanelTestPrompt": "எனது குடும்ப மரபு அடிப்படையில் நான் எந்த மரபணு குழு பரிசோதனையை பரிசீலிக்க வேண்டும்?",
    "gia.jumpGinaProtection": "மரபணு பாகுபாட்டு பாதுகாப்பு (GINA)",
    "gia.jumpGinaProtectionPrompt": "மரபணு பாகுபாட்டு பாதுகாப்பு சட்டங்கள் மற்றும் சுகாதார காப்பீட்டு தாக்கங்களை விளக்குங்கள்.",
    "gia.jumpDtcVsClinical": "நேரடி நுகர்வோர் vs மருத்துவ மரபணு பரிசோதனை",
    "gia.jumpDtcVsClinicalPrompt": "நுகர்வோர் DTC சோதனைகளுக்கும் மருத்துவ மரபணு பரிசோதனைகளுக்கும் என்ன வித்தியாசம்?",
    "gia.jumpVariantMeaning": "நோய்க்காரணி மாறுபாட்டின் பொருள்",
    "gia.jumpVariantMeaningPrompt": "தெளிவற்ற முக்கியத்துவம் வாய்ந்த மாறுபாடு (VUS) மற்றும் நோய்க்காரணி மாறுபாடு இடையே உள்ள வேறுபாடு என்ன?",
    "gia.inputPlaceholder": "புற்றுநோய் மரபணுக்கள், வழிகாட்டுதல்கள் அல்லது அபாயங்கள் குறித்து ஜியாவிடம் கேளுங்கள்...",
    "gia.askFollowupOrBook": "ஜியாவிடம் ஏதேனும் பின்தொடர் கேள்வியைக் கேட்கவும் அல்லது தொழில்முறை ஆலோசனைக்கு கீழே பதிவு செய்யவும்."
  },
  kn: {
    "common.default": "ಡೀಫಾಲ್ಟ್",
    "common.stopAudio": "ಆಡಿಯೋ ನಿಲ್ಲಿಸಿ",
    "common.listenAudio": "ಆಲಿಸಿ",
    "profile.tapToSetDefault": "ಡೀಫಾಲ್ಟ್ ಆಗಿ ಹೊಂದಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    "habits.fastingEatingWindowGuidelines": "ತಿನ್ನುವ ಸಮಯದ ಮಾರ್ಗಸೂಚಿಗಳು: ರಾತ್ರಿ 7 ರೊಳಗೆ ಊಟ ಮುಗಿಸಿ, ಬೆಳಿಗ್ಗೆ 9 ರೊಳಗೆ ಉಪಾಹಾರ ಸೇವಿಸಿ. ಕ್ಯಾಲೊರಿ ಕಾಪಾಡಿಕೊಳ್ಳಿ ಮತ್ತು ಸಂಸ್ಕರಿಸಿದ ಆಹಾರವನ್ನು ತಪ್ಪಿಸಿ.",
    "env.pulmonologistConsultDesc": "ನಿಮ್ಮ ಅಂಕವು ವಾಯು ಮಾಲಿನ್ಯ ಅಥವಾ ಹೊಗೆ ಉಸಿರಾಟದ ಗಂಭೀರ ಅಪಾಯಗಳನ್ನು ಸೂಚಿಸುತ್ತದೆ. ಶ್ವಾಸಕೋಶದ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸುವುದನ್ನು ಪರಿಗಣಿಸಿ.",
    "env.airExposureRecDesc": "ವಾಯು ಮಾಲಿನ್ಯ ಮತ್ತು ಧೂಮಪಾನದ ಹೊಗೆಯಿಂದ ದೂರವಿರಿ. ಸೂಕ್ತವಾದಾಗ N95 ಮಾಸ್ಕ್ ಮತ್ತು ಏರ್ ಪ್ಯೂರಿಫೈಯರ್ ಬಳಸಿ.",
    "env.naturalKitchenGuidelines": "ನೈಸರ್ಗಿಕ ಅಡುಗೆಮನೆ ಮತ್ತು ಪಾತ್ರೆಗಳ ಮಾರ್ಗಸೂಚಿಗಳು",
    "env.lookingForPlasticFree": "ಪ್ಲಾಸ್ಟಿಕ್ ಮುಕ್ತ ಸ್ಟೇನ್‌ಲೆಸ್ ಸ್ಟೀಲ್ ಅಥವಾ ಗಾಜಿನ ಶೇಖರಣಾ ಪಾತ್ರೆಗಳನ್ನು ಹುಡುಕುತ್ತಿದ್ದೀರಾ?",
    "env.doneWithKitchenCategory": "ಅಡುಗೆಮನೆ ವಿಭಾಗ ಮುಕ್ತಾಯವಾಗಿದೆ",
    "env.airSafetyDesc": "ಸಾಧ್ಯವಾದಷ್ಟು ವಾಯು ಮಾಲಿನ್ಯದಿಂದ ದೂರವಿರಿ. ಸೂಕ್ತ ಸಂದರ್ಭದಲ್ಲಿ N95 ಮಾಸ್ಕ್ ಮತ್ತು ಏರ್ ಪ್ಯೂರಿಫೈಯರ್ ಬಳಸಿ.",
    "logFasterWithAi": "AI ಮೂಲಕ {{target}} ಅನ್ನು 10 ಪಟ್ಟು ವೇಗವಾಗಿ ದಾಖಲಿಸಿ!",
    "aiCheckinNotice": "ನಿಮಗೆ ತಿಳಿದಿದೆಯೇ? ನಮ್ಮ AI ಅಸಿಸ್ಟೆಂಟ್‌ನೊಂದಿಗೆ 60 ಸೆಕೆಂಡುಗಳ ವಾಯ್ಸ್ ಚೆಕ್-ಇನ್ ಮಾಡಬಹುದು — ಯಾವುದೇ ಟೈಪಿಂಗ್ ಅಗತ್ಯವಿಲ್ಲ!",
    "continueManually": "ಹಸ್ತಚಾಲಿತವಾಗಿ ಮುಂದುವರಿಸಿ",
    "mia.lifestyleTitle": "🌿 ನಿಮಗಾಗಿ 4 ವೈಯಕ್ತಿಕ ಬದಲಾವಣೆಗಳು",
    "mia.lifestyleOutro": "📅 ಈ 4 ಹಂತಗಳನ್ನು ಇಂದು ಪ್ರಯತ್ನಿಸಿ ಮತ್ತು ನಾಳೆ ನಿಮಗೆ ಹೇಗನಿಸುತ್ತದೆ ಎಂದು ತಿಳಿಸಿ.",
    "mia.followUpCardDesc": "ನಿಮ್ಮ 4 ಹಂತಗಳ ಯೋಜನೆಯನ್ನು ನಾನು ಉಳಿಸಿದ್ದೇನೆ. ದಯವಿಟ್ಟು ಇಂದು ಇವುಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ ಮತ್ತು ನಾಳೆ ನನ್ನೊಂದಿಗೆ ಮಾತನಾಡಿ. ಮುಂದಿನ ಹಂತಗಳನ್ನು ಒಟ್ಟಾಗಿ ನಿರ್ಧರಿಸೋಣ!",
    "mia.feelBetter": "ಉತ್ತಮವಾಗಿ ಅನಿಸುತ್ತಿದೆ!",
    "mia.stillStruggling": "ಇನ್ನೂ ಕಷ್ಟವಾಗುತ್ತಿದೆ",
    "mia.feelBetterChoice": "ನಾನು ಗಮನಾರ್ಹವಾಗಿ ಉತ್ತಮವಾಗಿದ್ದೇನೆ",
    "mia.stillStrugglingChoice": "ಇನ್ನೂ ಕಷ್ಟವಾಗುತ್ತಿದೆ / ಕೆಟ್ಟದಾಗಿ ಅನಿಸುತ್ತಿದೆ",
    "mia.continueCardTitle": "ಅದ್ಭುತ — ನೀವು ನಿಜವಾದ ಪ್ರಗತಿ ಸಾಧಿಸುತ್ತಿದ್ದೀರಿ!",
    "mia.continueCardDesc": "ಮುಂದಿನ 2 ಪೂರ್ಣ ವಾರಗಳವರೆಗೆ ನಿಮ್ಮ 4 ಜೀವನಶೈಲಿ ಬದಲಾವಣೆಗಳನ್ನು ಮುಂದುವರಿಸಿ. ಸಣ್ಣ ಸ್ಥಿರ ಹೆಜ್ಜೆಗಳು ಸೆಲ್ಯುಲಾರ್ ಮಟ್ಟದಲ್ಲಿ ಶಾಶ್ವತ ಬದಲಾವಣೆಯನ್ನು ತರುತ್ತವೆ. ಸಹಾಯ ಬೇಕಾದಾಗ ಯಾವಾಗ ಬೇಕಾದರೂ ಬನ್ನಿ. ಅದ್ಭುತವಾಗಿ ಮಾಡುತ್ತಿದ್ದೀರಿ! 💚",
    "mia.returningBetter": "ನಾನು ಗಮನಾರ್ಹವಾಗಿ ಉತ್ತಮವಾಗಿದ್ದೇನೆ",
    "mia.returningSame": "ಹಿಂದಿನಂತೆಯೇ ಇದೆ — ಯಾವುದೇ ಬದಲಾವಣೆ ಇಲ್ಲ",
    "mia.returningWorse": "ವಾಸ್ತವವಾಗಿ ಕೆಟ್ಟದಾಗಿದೆ",
    "mia.returningSome": "ಕೆಲವನ್ನು ಪ್ರಯತ್ನಿಸಿದೆ, ಎಲ್ಲವನ್ನೂ ಅಲ್ಲ",
    "gia.whatToPrepare": "💡 ನಿಮ್ಮ ಸಮಾಲೋಚನೆಗಾಗಿ ಸಿದ್ಧಪಡಿಸಿಕೊಳ್ಳಬೇಕಾದದ್ದು:",
    "gia.quickToolsTitle": "ಜಿಯಾ ಅವರ ಜೆನೆಟಿಕ್ ಕೌನ್ಸಿಲಿಂಗ್ ತ್ವರಿತ ಉಪಕರಣಗಳು",
    "gia.highRiskSyndromeGuides": "🧬 ಹೆಚ್ಚಿನ ಅಪಾಯದ ಸಿಂಡ್ರೋಮ್ ಮಾರ್ಗದರ್ಶಿಗಳು",
    "gia.brcaDesc": "ಆನುವಂಶಿಕ ಸ್ತನ ಮತ್ತು ಅಂಡಾಶಯದ ಕ್ಯಾನ್ಸರ್ ಮುನ್ನೆಚ್ಚರಿಕೆ ಚಿಹ್ನೆಗಳು",
    "gia.lynchDesc": "ಕೊಲೊರೆಕ್ಟಲ್ ಮತ್ತು ಗರ್ಭಾಶಯದ ಆನುವಂಶಿಕ ಅಪಾಯಕಾರಿ ಅಂಶಗಳು",
    "gia.pedigreeDesc": "ಕುಟುಂಬದ ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ ವೃಕ್ಷವನ್ನು ಹೇಗೆ ಸಿದ್ಧಪಡಿಸುವುದು",
    "gia.jumpToQuestion": "⚡ ನಿರ್ದಿಷ್ಟ ಜೆನೆಟಿಕ್ ಪ್ರಶ್ನೆಗೆ ತೆರಳಿ",
    "gia.jumpPanelTest": "ನನಗೆ ಯಾವ ಪ್ಯಾನೆಲ್ ಪರೀಕ್ಷೆ ಬೇಕು?",
    "gia.jumpPanelTestPrompt": "ನನ್ನ ಕುಟುಂಬ ವೃಕ್ಷದ ಆಧಾರದ ಮೇಲೆ ನಾನು ಯಾವ ಮಲ್ಟಿ-ಜೀನ್ ಪ್ಯಾನೆಲ್ ಪರೀಕ್ಷೆಯನ್ನು ಪರಿಗಣಿಸಬೇಕು?",
    "gia.jumpGinaProtection": "ಜೆನೆಟಿಕ್ ತಾರತಮ್ಯ ರಕ್ಷಣೆ (GINA)",
    "gia.jumpGinaProtectionPrompt": "ಜೆನೆಟಿಕ್ ತಾರತಮ್ಯ ಸಂರಕ್ಷಣಾ ಕಾನೂನುಗಳು ಮತ್ತು ಆರೋಗ್ಯ ವಿಮೆಯ ಪರಿಣಾಮಗಳನ್ನು ವಿವರಿಸಿ.",
    "gia.jumpDtcVsClinical": "ಡೈರೆಕ್ಟ್-ಟು-ಕನ್ಸ್ಯೂಮರ್ vs ಕ್ಲಿನಿಕಲ್ ಜೆನೆಟಿಕ್ ಪರೀಕ್ಷೆ",
    "gia.jumpDtcVsClinicalPrompt": "ಗ್ರಾಹಕ DTC ಪರೀಕ್ಷೆಗಳು ಮತ್ತು ಕ್ಲಿನಿಕಲ್ ಜೆನೆಟಿಕ್ ಪರೀಕ್ಷೆಗಳ ನಡುವಿನ ವ್ಯತ್ಯಾಸವೇನು?",
    "gia.jumpVariantMeaning": "ರೋಗಕಾರಕ ರೂಪಾಂತರದ ಅರ್ಥ",
    "gia.jumpVariantMeaningPrompt": "ಅನಿಶ್ಚಿತ ಮಹತ್ವದ ರೂಪಾಂತರ (VUS) ಮತ್ತು ರೋಗಕಾರಕ ರೂಪಾಂತರದ ನಡುವಿನ ವ್ಯತ್ಯಾಸವೇನು?",
    "gia.inputPlaceholder": "ಕ್ಯಾನ್ಸರ್ ಜೀನ್‌ಗಳು, ಮಾರ್ಗಸೂಚಿಗಳು ಅಥವಾ ಅಪಾಯಗಳ ಬಗ್ಗೆ ಜಿಯಾ ಅವರಲ್ಲಿ ಕೇಳಿ...",
    "gia.askFollowupOrBook": "ಜಿಯಾ ಅವರಲ್ಲಿ ಮುಂದಿನ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ ಅಥವಾ ವೃತ್ತಿಪರ ಸಲಹೆಗಾಗಿ ಕೆಳಗೆ ಕಾಯ್ದಿರಿಸಿ."
  },
  hi: {
    "common.default": "डिफ़ॉल्ट",
    "common.stopAudio": "ऑडियो रोकें",
    "common.listenAudio": "सुनें",
    "profile.tapToSetDefault": "डिफ़ॉल्ट सेट करने के लिए टैप करें",
    "habits.fastingEatingWindowGuidelines": "भोजन समय दिशानिर्देश: रात 7 बजे तक रात्रिभोज समाप्त करें, सुबह 9 बजे तक नाश्ता करें। कैलोरी की मात्रा बनाए रखें और अस्वास्थ्यकर भोजन से बचें।",
    "env.pulmonologistConsultDesc": "आपका स्कोर वायु प्रदूषण या धुएं के जोखिम को दर्शाता है। फेफड़ों के स्वास्थ्य की जांच के लिए पल्मोनोलॉजिस्ट से परामर्श लें।",
    "env.airExposureRecDesc": "वायु प्रदूषण और निष्क्रिय धूम्रपान के संपर्क को कम करें। उचित समय पर N95 मास्क और एयर प्यूरीफायर का उपयोग करें।",
    "env.naturalKitchenGuidelines": "प्राकृतिक रसोई और बर्तन दिशानिर्देश",
    "env.lookingForPlasticFree": "क्या आप प्लास्टिक-मुक्त स्टेनलेस स्टील या कांच के रसोई कंटेनर तलाश रहे हैं?",
    "env.doneWithKitchenCategory": "रसोई श्रेणी पूर्ण हुई",
    "env.airSafetyDesc": "जहाँ तक संभव हो वायु प्रदूषण से बचें। उपयुक्त समय पर N95 मास्क और एयर प्यूरीफायर का प्रयोग करें।",
    "logFasterWithAi": "AI के साथ {{target}} को 10 गुना तेजी से लॉग करें!",
    "aiCheckinNotice": "क्या आप जानते हैं? आप हमारे AI सहायक के साथ 60 सेकंड में वॉयस चेक-इन कर सकते हैं — टाइपिंग की आवश्यकता नहीं है!",
    "continueManually": "मैन्युअल रूप से जारी रखें",
    "mia.lifestyleTitle": "🌿 आपके लिए 4 व्यक्तिगत बदलाव",
    "mia.lifestyleOutro": "📅 आज इन 4 उपायों को आजमाएं और कल आकर बताएं कि आप कैसा महसूस कर रहे हैं।",
    "mia.followUpCardDesc": "मैंने आपकी 4-चरणीय योजना सुरक्षित कर ली है। कृपया आज इन उपायों को आजमाएं और कल मुझसे चर्चा करें। हम मिलकर अगले कदम तय करेंगे!",
    "mia.feelBetter": "बेहतर महसूस कर रहा हूँ!",
    "mia.stillStruggling": "अभी भी परेशानी है",
    "mia.feelBetterChoice": "मैं काफी बेहतर महसूस कर रहा हूँ",
    "mia.stillStrugglingChoice": "अभी भी संघर्ष कर रहा हूँ / स्थिति खराब है",
    "mia.continueCardTitle": "बहुत बढ़िया — आप वास्तविक प्रगति कर रहे हैं!",
    "mia.continueCardDesc": "अगले 2 पूरे सप्ताह के लिए अपने 4 जीवनशैली बदलाव जारी रखें। छोटे निरंतर कदम सेलुलर स्तर पर स्थायी परिवर्तन लाते हैं। सहायता के लिए कभी भी आएं। आप बहुत अच्छा कर रहे हैं! 💚",
    "mia.returningBetter": "मैं काफी बेहतर महसूस कर रहा हूँ",
    "mia.returningSame": "पहले जैसा ही — कोई खास बदलाव नहीं",
    "mia.returningWorse": "वास्तव में स्थिति और खराब लग रही है",
    "mia.returningSome": "कुछ उपाय आजमाए, सभी नहीं",
    "gia.whatToPrepare": "💡 अपने परामर्श के लिए क्या तैयार रखें:",
    "gia.quickToolsTitle": "जिया के जेनेटिक काउंसलिंग त्वरित टूल्स",
    "gia.highRiskSyndromeGuides": "🧬 उच्च-जोखिम सिंड्रोम गाइड",
    "gia.brcaDesc": "वंशानुगत स्तन और डिम्बग्रंथि कैंसर के चेतावनी संकेत",
    "gia.lynchDesc": "कोलोरेक्टल और गर्भाशय के वंशानुगत जोखिम कारक",
    "gia.pedigreeDesc": "पारिवारिक चिकित्सा इतिहास ट्री कैसे तैयार करें",
    "gia.jumpToQuestion": "⚡ विशिष्ट जेनेटिक प्रश्न पर जाएं",
    "gia.jumpPanelTest": "मुझे किस पैनल टेस्ट की आवश्यकता है?",
    "gia.jumpPanelTestPrompt": "मेरे फैमिली ट्री के आधार पर मुझे किस मल्टी-जीन पैनल टेस्ट पर विचार करना चाहिए?",
    "gia.jumpGinaProtection": "जेनेटिक भेदभाव संरक्षण (GINA)",
    "gia.jumpGinaProtectionPrompt": "जेनेटिक भेदभाव संरक्षण कानूनों और स्वास्थ्य बीमा पर इसके प्रभाव की व्याख्या करें।",
    "gia.jumpDtcVsClinical": "डायरेक्ट-टू-कंज्यूमर बनाम क्लिनिकल जीन परीक्षण",
    "gia.jumpDtcVsClinicalPrompt": "उपभोक्ता DTC परीक्षणों और क्लिनिकल डायग्नोस्टिक परीक्षणों के बीच क्या अंतर है?",
    "gia.jumpVariantMeaning": "रोगजनक म्यूटेशन का अर्थ",
    "gia.jumpVariantMeaningPrompt": "अनिश्चित महत्व के वेरिएंट (VUS) बनाम पैथोजेनिक म्यूटेशन में क्या अंतर है?",
    "gia.inputPlaceholder": "कैंसर जीन, दिशानिर्देश या जोखिम के बारे में जिया से पूछें...",
    "gia.askFollowupOrBook": "जिया से कोई भी प्रश्न पूछें या पेशेवर पैनल ऑर्डरिंग के लिए नीचे काउंसलर बुक करें।"
  },
  te: {
    "common.default": "డిఫాల్ట్",
    "common.stopAudio": "ఆడియోను ఆపండి",
    "common.listenAudio": "వినండి",
    "profile.tapToSetDefault": "డిఫాల్ట్‌గా సెట్ చేయడానికి నొక్కండి",
    "habits.fastingEatingWindowGuidelines": "ఆహార సమయ మార్గదర్శకాలు: రాత్రి 7 గంటలలోపు భోజనం ముగించండి, ఉదయం 9 గంటలలోపు అల్పాహారం తీసుకోండి. కేలరీలను నిర్వహించండి మరియు ప్రాసెస్ చేసిన ఆహారాన్ని నివారించండి.",
    "env.pulmonologistConsultDesc": "మీ స్కోర్ వాయు కాలుష్యం లేదా పొగ పీల్చడం వల్ల కలిగే తీవ్రమైన ప్రమాదాలను సూచిస్తుంది. ఊపిరితిత్తుల నిపుణుడితో మాట్లాడండి.",
    "env.airExposureRecDesc": "వాయు కాలుష్యం మరియు సెకండ్ హ్యాండ్ పొగ నుండి దూరంగా ఉండండి. N95 మాస్క్ మరియు ఎయిర్ ప్యూరిఫైయర్‌ను ఉపయోగించండి.",
    "env.naturalKitchenGuidelines": "సహజ వంటగది మరియు పాత్రల మార్గదర్శకాలు",
    "env.lookingForPlasticFree": "ప్లాస్టిక్ రహిత స్టెయిన్‌లెస్ స్టీల్ లేదా గాజు నిల్వ కంటైనర్ల కోసం చూస్తున్నారా?",
    "env.doneWithKitchenCategory": "వంటగది విభాగం పూర్తయింది",
    "env.airSafetyDesc": "వీలైనంత వరకు వాయు కాలుష్యానికి గురికావడాన్ని తగ్గించండి. తగినప్పుడు N95 మాస్క్ మరియు ఎయిర్ ప్యూరిఫైయర్‌ను ఉపయోగించండి.",
    "logFasterWithAi": "AIతో {{target}}ను 10 రెట్లు వేగంగా లాగ్ చేయండి!",
    "aiCheckinNotice": "మీకు తెలుసా? మా AI అసిస్టెంట్‌తో 60 సెకన్ల వాయిస్ చెక్-ఇన్ చేయవచ్చు లేదా నివేదికలను అప్‌లోడ్ చేయవచ్చు — టైపింగ్ అవసరం లేదు!",
    "continueManually": "మాన్యువల్‌గా కొనసాగించండి",
    "mia.lifestyleTitle": "🌿 మీ కోసం 4 వ్యక్తిగతీకరించిన మార్పులు",
    "mia.lifestyleOutro": "📅 ఈ రోజు ఈ 4 దశలను ప్రయత్నించండి మరియు రేపు మీరు ఎలా ఉన్నారో నాకు చెప్పండి.",
    "mia.followUpCardDesc": "నేను మీ 4-దశల ప్రణాళికను భద్రపరిచాను. దయచేసి ఈ రోజు వీటిని ప్రయత్నించండి మరియు రేపు నాతో మాట్లాడండి. తదుపరి చర్యలను కలిసి నిర్ణయిద్దాం!",
    "mia.feelBetter": "నయంగా అనిపిస్తోంది!",
    "mia.stillStruggling": "ఇంకా ఇబ్బందిగా ఉంది",
    "mia.feelBetterChoice": "నేను చాలా మెరుగ్గా ఉన్నాను",
    "mia.stillStrugglingChoice": "ఇంకా ఇబ్బంది పడుతున్నాను / పరిస్థితి బాగాలేదు",
    "mia.continueCardTitle": "అద్భుతం — మీరు నిజమైన పురోగతి సాధిస్తున్నారు!",
    "mia.continueCardDesc": "తదుపరి 2 పూర్తి వారాల పాటు మీ 4 జీవనశైలి మార్పులను కొనసాగించండి. చిన్న స్థిరమైన అడుగులు సెల్యులార్ స్థాయిలో శాశ్వత మార్పును తెస్తాయి. సహాయం కావాల్సినప్పుడు ఎప్పుడైనా రండి. మీరు అద్భుతంగా చేస్తున్నారు! 💚",
    "mia.returningBetter": "నేను చాలా మెరుగ్గా ఉన్నాను",
    "mia.returningSame": "దాదాపు అలాగే ఉంది — పెద్ద మార్పు లేదు",
    "mia.returningWorse": "నిజానికి పరిస్థితి మరింత బాగాలేదు",
    "mia.returningSome": "కొన్ని ప్రయత్నించాను, అన్నీ కాదు",
    "gia.whatToPrepare": "💡 మీ సంప్రదింపుల కోసం ఏమి సిద్ధం చేసుకోవాలి:",
    "gia.quickToolsTitle": "జియా యొక్క జెనెటిక్ కౌన్సెలింగ్ త్వరిత సాధనాలు",
    "gia.highRiskSyndromeGuides": "🧬 అధిక-ప్రమాద సిండ్రోమ్ మార్గదర్శకాలు",
    "gia.brcaDesc": "వంశపారంపర్య రొమ్ము మరియు అండాశయ క్యాన్సర్ హెచ్చరిక సంకేతాలు",
    "gia.lynchDesc": "కొలొరెక్టల్ మరియు గర్భాశయ వంశపారంపర్య ప్రమాద కారకాలు",
    "gia.pedigreeDesc": "కుటుంబ వైద్య చరిత్ర వృక్షాన్ని ఎలా సిద్ధం చేయాలి",
    "gia.jumpToQuestion": "⚡ నిర్దిష్ట జన్యు ప్రశ్నకు వెళ్లండి",
    "gia.jumpPanelTest": "నాకు ఏ ప్యానెల్ పరీక్ష అవసరం?",
    "gia.jumpPanelTestPrompt": "నా కుటుంబ వృక్షం ఆధారంగా నేను ఏ మల్టీ-జీన్ ప్యానెల్ పరీక్షను పరిగణించాలి?",
    "gia.jumpGinaProtection": "జన్యు వివక్ష రక్షణ (GINA)",
    "gia.jumpGinaProtectionPrompt": "జన్యు వివక్ష రక్షణ చట్టాలు మరియు ఆరోగ్య బీమా ప్రభావాలను వివరించండి.",
    "gia.jumpDtcVsClinical": "డైరెక్ట్-టు-కన్స్యూమర్ వర్సెస్ క్లినికల్ జన్యు పరీక్ష",
    "gia.jumpDtcVsClinicalPrompt": "వినియోగదారు DTC పరీక్షలు మరియు క్లినికల్ డయాగ్నస్టిక్ పరీక్షల మధ్య తేడా ఏమిటి?",
    "gia.jumpVariantMeaning": "వ్యాధికారక జన్యు మార్పు అర్థం",
    "gia.jumpVariantMeaningPrompt": "అనిశ్చిత ప్రాముఖ్యత కలిగిన వేరియంట్ (VUS) మరియు వ్యాధికారక ఉత్పరివర్తనాల మధ్య తేడా ఏమిటి?",
    "gia.inputPlaceholder": "క్యాన్సర్ జన్యువులు, మార్గదర్శకాలు లేదా ప్రమాదం గురించి జియాను అడగండి...",
    "gia.askFollowupOrBook": "జియాను ఏదైనా తదుపరి ప్రశ్న అడగండి లేదా నిపుణుల సలహా కోసం క్రింద కౌన్సెలర్‌ను బుక్ చేయండి."
  }
};

const langs = ['en', 'ta', 'kn', 'hi', 'te'];

langs.forEach(lang => {
  const filePath = path.join(__dirname, `../src/i18n/locales/${lang}.ts`);
  let content = fs.readFileSync(filePath, 'utf8');

  // Insert before closing "} as const;"
  const keysToAdd = newKeys[lang];
  let snippet = '\n  // --- CRITICAL 5-LANGUAGE AI & SCREEN COMPLETIONS ---\n';
  for (const [k, v] of Object.entries(keysToAdd)) {
    // Only add if not already present in file
    if (!content.includes(`"${k}":`)) {
      snippet += `  "${k}": ${JSON.stringify(v)},\n`;
    }
  }

  content = content.replace(/} as const;\s*$/, `${snippet}} as const;\n`);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${lang}.ts with verified translations.`);
});
