const fs = require('fs');

const enKeys = {
  "habits.waterFreeZero": "Yes, it is free (0)",
  "habits.waterNotSureMinus1": "No / Not sure (-1)",
  "habits.pesticidesConsumeMinus1": "Yes, I consume without steps (-1)",
  "habits.pesticidesWashZero": "No, I wash or choose organic (0)",
  "habits.microplasticsRegularMinus1": "Yes, regularly (-1)",
  "habits.microplasticsAvoidZero": "No, I avoid plastic containers (0)",
  "habits.mudDirtCysts": "Mud, dirt, basic cysts",
  "habits.bacteriaVirusesOnly": "Bacteria & Viruses only",
  "habits.pesticidesChlorineVoc": "Pesticides, chlorine, VOCs, carcinogens",
  "habits.heavyMetalsArsenic": "Heavy metals, arsenic, nitrates, microplastics",
  "habits.organicReducesPesticides": "Choosing organic produce drastically reduces chemical pesticide residue levels in your diet.",
  "habits.orderOrganicFood": "Click here to Order Organic Food",
  "habits.swapPlasticStorage": "Swap plastic storage for premium borosilicate glass or stainless steel containers.",
  "habits.orderPlasticFreeProducts": "Click here to Order Plastic-Free Products",
  "habits.avoidPetBottles": "Disposable PET water bottles, heating plastic in microwaves, plastic tea bags.",
  "habits.chooseGlassBottles": "Borosilicate glass bottles, food-grade stainless steel containers, ceramic dinnerware.",
  "habits.isDrinkingWater": "Is your drinking water",
  "habits.areUtensils": "Are utensils like",
  "habits.areCommodities": "Are commodities and ingredients",
  "habits.kitchenMicroplasticsAudit": "Kitchen Microplastics & Utensils Audit",
  "habits.safeContainerPlasticSwaps": "Safe Container Plastic Swaps",
  "habits.dirtyDozenWashingTips": "Dirty Dozen & Residue Washing Tips",
  "habits.technology": "Technology",
  "habits.mainPurpose": "Main Purpose",
  "habits.mitoRebootRecommendation": "MitoReboot Official Recommendation",
  "habits.doneWithWaterCategory": "Done with Water Pollution Category",
  "habits.doneWithPesticidesCategory": "Done with Pesticides Category",
  "habits.doneWithMicroplasticsCategory": "Done with Microplastics Category",
  "habits.doneWithKitchenCategory": "Done with Kitchen Category",
  "habits.avoidLabel": "Avoid ❌",
  "habits.chooseLabel": "Choose ✅",
  "habits.shopNow": "Shop now",
  "habits.yesLabel": "Yes",
  "habits.noLabel": "No",

  "chatModal.dailyHealthSummary": "Daily Health Summary",
  "chatModal.checkinLoggedSuccess": "Check-in Logged Successfully",
  "chatModal.checkinLoggedDesc": "Your circadian fasting, cellular repair, and risk prevention logs are updated on your dashboard.",
  "chatModal.priorityActionPlanTomorrow": "Priority Action Plan for Tomorrow:",
  "chatModal.dailyCheckinReminder": "Daily AI Check-in Reminder",
  "chatModal.selectReminderTime": "Select a reminder time or turn off alerts completely:",
  "chatModal.setTime": "Set Time",
  "chatModal.turnOffDailyReminder": "Turn Off Daily Reminder",
  "chatModal.testAlertNow": "Test Alert Now",
  "chatModal.fastAnswer": "Fast Answer:",
  "chatModal.uploadReportPrompt": "Upload Report (PDF / CSV)",
  "chatModal.uploading": "Uploading...",
  "chatModal.stopSpeaking": "Stop",
  "chatModal.off": "Off",
  "chatModal.editAnswer": "Edit answer",

  "dash.glucoseLevel": "Glucose Level:",
  "dash.libreviewCgm": "LibreView CGM",
  "dash.cgmHistoryDetails": "CGM history & sync details",
  "dash.filesCount": "files",
  "dash.targetRange": "Target: 70–{{max}} mg/dL",
  "dash.logManualReadingPrompt": "Enter a manual blood glucose reading from your glucometer.",
  "dash.highStressCortisol": "High Stress / Cortisol",
  "dash.calmNervousSystem": "Calm Nervous System",
  "dash.sleepDebt": "Sleep Debt (<6h)",
  "dash.restfulSleep": "7+ Hours Restorative Sleep",
  "dash.tobaccoExposure": "Tobacco (Smoking / Chewing)",
  "dash.tobaccoFree": "Tobacco & Smoke-Free Day",
  "dash.alcoholIntake": "Alcohol Intake",
  "dash.zeroAlcohol": "Zero Alcohol Exposure",
  "dash.environmentalToxins": "Environmental Toxins",
  "dash.lowToxicBurden": "Low Toxic Burden",
  "dash.kitchenPlasticRisk": "Kitchen Plastic & Cookware Risk",
  "dash.safeKitchen": "Safe Plastic-Free Kitchen",
  "dash.gastricAcidity": "Gastric Acidity / Refined Food",
  "dash.healthyGutOral": "Healthy Gut & Oral Balance",
  "dash.circadianFasting": "Circadian Fasting (14h+)",
  "dash.aerobicMovement": "20+ Mins Aerobic Movement",
  "dash.antioxidantProtection": "Antioxidant Cellular Protection",
  "dash.powerOfBreath": "Power of Breath & Mindfulness",

  "diag.checkoutAndPay": "Checkout & Pay",
  "diag.trialSpecialOffer": "🎁 Trial Special Offer",
  "diag.trialOfferDesc": "Use the code {{code}} at checkout to book this test fully free for testing purposes!",
  "diag.apply": "Apply",
  "diag.codeAppliedSuccess": "✓ Code applied! Booking fee discounted to 0.",
  "diag.discountApplied100": "100% discount applied",
  "diag.dateTime": "Date & Time",
  "diag.confirmBookingFree": "Confirm Booking (Free)",
  "diag.payViaRazorpay": "Pay ₹{{amount}} via Razorpay",
  "diag.processing": "Processing...",
  "diag.homeVisit": "Home Visit",
  "diag.labVisit": "Lab Visit",

  "appt.myNotesToDoctor": "📝 My Notes to Doctor:",
  "appt.clinicInstructions": "🏥 Clinic Instructions from Doctor:",
  "appt.openCalendarInvite": "Open Google Calendar Invite",
  "appt.joinGoogleMeet": "Join Google Meet",

  "proto.dailyDoseTimings": "Daily dose timings & adherence",
  "proto.noMedDosesToday": "No medication doses logged today. Enter your dose details above to track schedule adherence.",
  "proto.allMenstrualCycles": "All recorded menstrual cycles & regularity",
  "proto.amPmLongitudinalLogs": "AM & PM longitudinal pressure logs",

  "network.checkCellularSettings": "Check Cellular / Mobile Data switch in Settings",
  "network.verifyWifiStrength": "Verify Wi-Fi network connection & signal strength",

  "sub.totalPrice": "Total Price",
  "sub.billingInvoiceHistory": "Billing & Invoice History",
  "sub.totalPaid": "Total Paid:",
  "sub.daysFreeTrial": "🎁 {{days}} Days Free Trial included",
  "sub.startFreeTrial": "Start Free Trial",
  "sub.subscribeNow": "Subscribe Now (₹{{amount}})",

  "shop.patientReviews": "Patient Reviews & Feedback",
  "shop.verifiedReviewsFor": "Verified patient feedback for {{name}}",
  "shop.verifiedPurchase": "Verified Purchase",
  "shop.medicalHealthStore": "Medical & Health Store",

  "legal.acceptAndContinue": "Accept & Continue",
  "legal.mandatoryAgreement": "Mandatory Agreement",
  "legal.savingAcceptance": "Saving Acceptance...",
  "legal.scrollToBottomToContinue": "Please scroll to the bottom to continue.",
  "legal.scrollToBottom": "Scroll to Bottom",
  "legal.reachedBottomPrompt": "You have reached the bottom of the document. You may now accept the terms below.",
  "legal.termsCheckboxLabel": "I have read and understood the Master Disclaimer, Privacy Notice and Terms of Use, and I agree to be bound by them.",
  "legal.termsInstruction": "Please read the complete MitoReboot Master Disclaimer, Privacy Notice, and Terms of Use carefully. You must scroll to the bottom of the document before accepting."
};

const taKeys = {
  "habits.waterFreeZero": "ஆம், நச்சுக்கள் இல்லை (0)",
  "habits.waterNotSureMinus1": "இல்லை / உறுதியாகத் தெரியவில்லை (-1)",
  "habits.pesticidesConsumeMinus1": "ஆம், முன்னெச்சரிக்கையின்றி உட்கொள்கிறேன் (-1)",
  "habits.pesticidesWashZero": "இல்லை, கழுவுகிறேன் அல்லது இயற்கை உணவைத் தேர்ந்தெடுக்கிறேன் (0)",
  "habits.microplasticsRegularMinus1": "ஆம், தொடர்ந்து பயன்படுத்துகிறேன் (-1)",
  "habits.microplasticsAvoidZero": "இல்லை, பிளாஸ்டிக் பாத்திரங்களைத் தவிர்க்கிறேன் (0)",
  "habits.mudDirtCysts": "சேறு, தூசி மற்றும் அடிப்படை அசுத்தங்கள்",
  "habits.bacteriaVirusesOnly": "பாக்டீரியா மற்றும் வைரஸ்கள் மட்டுமே",
  "habits.pesticidesChlorineVoc": "பூச்சிக்கொல்லிகள், குளோரின், நச்சு வாயுக்கள், புற்றுநோய் காரணிகள்",
  "habits.heavyMetalsArsenic": "கன உலோகங்கள், ஆர்சனிக், நைட்ரேட்டுகள், மைக்ரோபிளாஸ்டிக்",
  "habits.organicReducesPesticides": "இயற்கை விவசாயப் பொருட்களைத் தேர்ந்தெடுப்பது உங்கள் உணவில் உள்ள ரசாயன பூச்சிக்கொல்லி அளவைக் கணிசமாகக் குறைக்கிறது.",
  "habits.orderOrganicFood": "இயற்கை உணவை ஆர்டர் செய்ய இங்கே கிளிக் செய்யவும்",
  "habits.swapPlasticStorage": "பிளாஸ்டிக் சேமிப்பிற்குப் பதிலாக போரோசிலிகேட் கண்ணாடி அல்லது துருப்பிடிக்காத எஃகு கொள்கலன்களைப் பயன்படுத்தவும்.",
  "habits.orderPlasticFreeProducts": "பிளாஸ்டிக் இல்லாத தயாரிப்புகளை ஆர்டர் செய்ய இங்கே கிளிக் செய்யவும்",
  "habits.avoidPetBottles": "ஒருமுறை பயன்படுத்தும் PET பாட்டில்கள், மைக்ரோவேவில் பிளாஸ்டிக் சூடாக்குதல், பிளாஸ்டிக் டீ பேக்குகள்.",
  "habits.chooseGlassBottles": "போரோசிலிகேட் கண்ணாடி பாட்டில்கள், எஃகு கொள்கலன்கள், பீங்கான் பாத்திரங்கள்.",
  "habits.isDrinkingWater": "உங்கள் குடிநீர்",
  "habits.areUtensils": "உங்கள் சமையல் பாத்திரங்கள்",
  "habits.areCommodities": "மளிகைப் பொருட்கள்",
  "habits.kitchenMicroplasticsAudit": "சமையலறை மைக்ரோபிளாஸ்டிக் & பாத்திரங்கள் தணிக்கை",
  "habits.safeContainerPlasticSwaps": "பாதுகாப்பான கொள்கலன் மாற்றீடுகள்",
  "habits.dirtyDozenWashingTips": "காய்கறி நச்சு நீக்கம் & கழுவும் குறிப்புகள்",
  "habits.technology": "தொழில்நுட்பம்",
  "habits.mainPurpose": "முக்கிய நோக்கம்",
  "habits.mitoRebootRecommendation": "MitoReboot அதிகாரப்பூர்வ பரிந்துரை",
  "habits.doneWithWaterCategory": "நீர் மாசுபாடு பிரிவு முடிந்தது",
  "habits.doneWithPesticidesCategory": "பூச்சிக்கொல்லிகள் பிரிவு முடிந்தது",
  "habits.doneWithMicroplasticsCategory": "மைக்ரோபிளாஸ்டிக் பிரிவு முடிந்தது",
  "habits.doneWithKitchenCategory": "சமையலறை பிரிவு முடிந்தது",
  "habits.avoidLabel": "தவிர்க்கவும் ❌",
  "habits.chooseLabel": "தேர்வு செய்யவும் ✅",
  "habits.shopNow": "வாங்க",
  "habits.yesLabel": "ஆம்",
  "habits.noLabel": "இல்லை",

  "chatModal.dailyHealthSummary": "தினசரி ஆரோக்கிய சுருக்கம்",
  "chatModal.checkinLoggedSuccess": "தினசரி பதிவு வெற்றிகரமாகச் சேமிக்கப்பட்டது",
  "chatModal.checkinLoggedDesc": "உங்கள் விரதம், செல் பழுதுபார்ப்பு மற்றும் பாதுகாப்புத் தரவுகள் டாஷ்போர்டில் புதுப்பிக்கப்பட்டுள்ளன.",
  "chatModal.priorityActionPlanTomorrow": "நாளைக்கான முன்னுரிமை செயல் திட்டம்:",
  "chatModal.dailyCheckinReminder": "தினசரி AI நினைவூட்டல்",
  "chatModal.selectReminderTime": "நினைவூட்டல் நேரத்தைத் தேர்ந்தெடுக்கவும் அல்லது எச்சரிக்கைகளை முடக்கவும்:",
  "chatModal.setTime": "நேரத்தை அமைக்கவும்",
  "chatModal.turnOffDailyReminder": "தினசரி நினைவூட்டலை முடக்கு",
  "chatModal.testAlertNow": "எச்சரிக்கையைச் சோதிக்கவும்",
  "chatModal.fastAnswer": "விரைவான பதில்:",
  "chatModal.uploadReportPrompt": "அறிக்கையைப் பதிவேற்றவும் (PDF / CSV)",
  "chatModal.uploading": "பதிவேற்றப்படுகிறது...",
  "chatModal.stopSpeaking": "நிறுத்து",
  "chatModal.off": "முடக்கப்பட்டது",
  "chatModal.editAnswer": "பதிலைத் திருத்தவும்",

  "dash.glucoseLevel": "குளுக்கோஸ் அளவு:",
  "dash.libreviewCgm": "LibreView CGM",
  "dash.cgmHistoryDetails": "CGM வரலாறு & ஒத்திசைவு விவரங்கள்",
  "dash.filesCount": "கோப்புகள்",
  "dash.targetRange": "இலக்கு: 70–{{max}} mg/dL",
  "dash.logManualReadingPrompt": "உங்கள் குளுக்கோமீட்டரிலிருந்து கையேடு குளுக்கோஸ் அளவை உள்ளிடவும்.",
  "dash.highStressCortisol": "அதிக மன அழுத்தம் / கார்டிசோல்",
  "dash.calmNervousSystem": "அமைதியான நரம்பு மண்டலம்",
  "dash.sleepDebt": "தூக்கக் குறைபாடு (<6 மணி)",
  "dash.restfulSleep": "7+ மணிநேர ஆழ்ந்த தூக்கம்",
  "dash.tobaccoExposure": "புகையிலை வெளிப்பாடு",
  "dash.tobaccoFree": "புகையிலை இல்லாத நாள்",
  "dash.alcoholIntake": "மது அருந்துதல்",
  "dash.zeroAlcohol": "மது இல்லாத நாள்",
  "dash.environmentalToxins": "சுற்றுச்சூழல் நச்சுகள்",
  "dash.lowToxicBurden": "குறைந்த நச்சுச் சுமை",
  "dash.kitchenPlasticRisk": "சமையலறை பிளாஸ்டிக் அபாயம்",
  "dash.safeKitchen": "பாதுகாப்பான பிளாஸ்டிக் இல்லாத சமையலறை",
  "dash.gastricAcidity": "இரைப்பை அமிலத்தன்மை / பதப்படுத்தப்பட்ட உணவு",
  "dash.healthyGutOral": "ஆரோக்கியமான குடல் மற்றும் வாய் நலம்",
  "dash.circadianFasting": "உண்ணாவிரத சீரமைப்பு (14+ மணி)",
  "dash.aerobicMovement": "20+ நிமிட உடற்பயிற்சி",
  "dash.antioxidantProtection": "ஆன்டிஆக்ஸிடன்ட் செல் பாதுகாப்பு",
  "dash.powerOfBreath": "சுவாசத்தின் ஆற்றல் மற்றும் மன அமைதி",

  "diag.checkoutAndPay": "செக்அவுட் மற்றும் பணம் செலுத்துக",
  "diag.trialSpecialOffer": "🎁 சிறப்பு சோதனை சலுகை",
  "diag.trialOfferDesc": "பரிசோதனை நோக்கங்களுக்காக முற்றிலும் இலவசமாக முன்பதிவு செய்ய {{code}} என்ற குறியீட்டைப் பயன்படுத்தவும்!",
  "diag.apply": "பயன்படுத்து",
  "diag.codeAppliedSuccess": "✓ குறியீடு பயன்படுத்தப்பட்டது! கட்டணம் 0 ஆகக் குறைக்கப்பட்டது.",
  "diag.discountApplied100": "100% தள்ளுபடி பயன்படுத்தப்பட்டது",
  "diag.dateTime": "தேதி & நேரம்",
  "diag.confirmBookingFree": "முன்பதிவை உறுதிப்படுத்துக (இலவசம்)",
  "diag.payViaRazorpay": "Razorpay மூலம் ₹{{amount}} செலுத்துக",
  "diag.processing": "செயலாக்குகிறது...",
  "diag.homeVisit": "வீட்டு வருகை",
  "diag.labVisit": "ஆய்வக வருகை",

  "appt.myNotesToDoctor": "📝 மருத்துவருக்கு என் குறிப்புகள்:",
  "appt.clinicInstructions": "🏥 மருத்துவரின் மருத்துவமனை வழிகாட்டுதல்கள்:",
  "appt.openCalendarInvite": "Google கேலெண்டர் அழைப்பைத் திறக்கவும்",
  "appt.joinGoogleMeet": "Google Meet இல் இணையவும்",

  "proto.dailyDoseTimings": "தினசரி மருந்தளவு நேரம் மற்றும் கண்காணிப்பு",
  "proto.noMedDosesToday": "இன்று மருந்துகள் பதிவு செய்யப்படவில்லை. மருந்தளவு விவரங்களை மேலே உள்ளிடவும்.",
  "proto.allMenstrualCycles": "பதிவு செய்யப்பட்ட மாதவிடாய் சுழற்சிகள் & ஒழுங்குமுறை",
  "proto.amPmLongitudinalLogs": "காலை & மாலை இரத்த அழுத்தப் பதிவுகள்",

  "network.checkCellularSettings": "அமைப்புகளில் செல்லுலார் / மொபைல் டேட்டாவைச் சரிபார்க்கவும்",
  "network.verifyWifiStrength": "வைஃபை இணைப்பு மற்றும் சிக்னல் வலிமையைச் சரிபார்க்கவும்",

  "sub.totalPrice": "மொத்த விலை",
  "sub.billingInvoiceHistory": "பில்லிங் மற்றும் ரசீது வரலாறு",
  "sub.totalPaid": "செலுத்தப்பட்ட மொத்தம்:",
  "sub.daysFreeTrial": "🎁 {{days}} நாட்கள் இலவச சோதனை சேர்க்கப்பட்டுள்ளது",
  "sub.startFreeTrial": "இலவச சோதனையைத் தொடங்கவும்",
  "sub.subscribeNow": "இப்போது சந்தா பெறுக (₹{{amount}})",

  "shop.patientReviews": "நோயாளி மதிப்புரைகள் & கருத்துக்கள்",
  "shop.verifiedReviewsFor": "{{name}} க்கான சரிபார்க்கப்பட்ட கருத்துக்கள்",
  "shop.verifiedPurchase": "சரிபார்க்கப்பட்ட கொள்முதல்",
  "shop.medicalHealthStore": "மருத்துவ மற்றும் சுகாதார அங்காடி",

  "legal.acceptAndContinue": "ஏற்றுக்கொண்டு தொடரவும்",
  "legal.mandatoryAgreement": "கட்டாய ஒப்பந்தம்",
  "legal.savingAcceptance": "ஏற்பு சேமிக்கப்படுகிறது...",
  "legal.scrollToBottomToContinue": "தொடர தயவுசெய்து கீழே வரை உருட்டவும்.",
  "legal.scrollToBottom": "கீழே உருட்டவும்",
  "legal.reachedBottomPrompt": "நீங்கள் ஆவணத்தின் கீழ் பகுதியை அடைந்துவிட்டீர்கள். இப்போது விதிமுறைகளை ஏற்கலாம்.",
  "legal.termsCheckboxLabel": "நான் முழு பொறுப்புதுறப்பு, தனியுரிமை அறிவிப்பு மற்றும் பயன்பாட்டு விதிமுறைகளைப் படித்துப் புரிந்துகொண்டேன், அவற்றுக்குக் கட்டுப்பட ஒப்புக்கொள்கிறேன்.",
  "legal.termsInstruction": "MitoReboot முதன்மை பொறுப்புதுறப்பு, தனியுரிமை அறிவிப்பு மற்றும் பயன்பாட்டு விதிமுறைகளை கவனமாகப் படிக்கவும். ஏற்கும் முன் ஆவணத்தின் கீழே உருட்ட வேண்டும்."
};

const teKeys = {
  "habits.waterFreeZero": "అవును, కాలుష్యాలు లేవు (0)",
  "habits.waterNotSureMinus1": "లేదు / ఖచ్చితంగా తెలియదు (-1)",
  "habits.pesticidesConsumeMinus1": "అవును, నివారణ లేకుండా తీసుకుంటాను (-1)",
  "habits.pesticidesWashZero": "లేదు, కడుగుతాను లేదా సేంద్రీయమైనవి ఎంచుకుంటాను (0)",
  "habits.microplasticsRegularMinus1": "అవును, క్రమం తప్పకుండా (-1)",
  "habits.microplasticsAvoidZero": "లేదు, ప్లాస్టిక్ కంటైనర్లను నివారిస్తాను (0)",
  "habits.mudDirtCysts": "మట్టి, ధూళి మరియు ప్రాథమిక తిత్తులు",
  "habits.bacteriaVirusesOnly": "బాక్టీరియా మరియు వైరస్‌లు మాత్రమే",
  "habits.pesticidesChlorineVoc": "పురుగుమందులు, క్లోరిన్, హానికర రసాయనాలు, క్యాన్సర్ కారకాలు",
  "habits.heavyMetalsArsenic": "భారీ లోహాలు, ఆర్సెనిక్, నైట్రేట్లు, మైక్రోప్లాస్టిక్",
  "habits.organicReducesPesticides": "సేంద్రీయ ఉత్పత్తులను ఎంచుకోవడం మీ ఆహారంలో రసాయన పురుగుమందుల శాతాన్ని గణనీయంగా తగ్గిస్తుంది.",
  "habits.orderOrganicFood": "సేంద్రీయ ఆహారాన్ని ఆర్డర్ చేయడానికి ఇక్కడ క్లిక్ చేయండి",
  "habits.swapPlasticStorage": "ప్లాస్టిక్ నిల్వ స్థానంలో బోరోసిలికేట్ గాజు లేదా స్టెయిన్‌లెస్ స్టీల్ కంటైనర్లను వాడండి.",
  "habits.orderPlasticFreeProducts": "ప్లాస్టిక్ రహిత ఉత్పత్తులను ఆర్డర్ చేయడానికి ఇక్కడ క్లిక్ చేయండి",
  "habits.avoidPetBottles": "డిస్పోజబుల్ PET బాటిళ్లు, మైక్రోవేవ్‌లో ప్లాస్టిక్ వేడి చేయడం, ప్లాస్టిక్ టీ బ్యాగులు.",
  "habits.chooseGlassBottles": "బోరోసిలికేట్ గాజు సీసాలు, స్టీల్ కంటైనర్లు, సిరామిక్ పాత్రలు.",
  "habits.isDrinkingWater": "మీ తాగునీరు",
  "habits.areUtensils": "మీ వంట పాత్రలు",
  "habits.areCommodities": "సరుకులు మరియు పదార్థాలు",
  "habits.kitchenMicroplasticsAudit": "వంటగది మైక్రోప్లాస్టిక్ & పాత్రల ఆడిట్",
  "habits.safeContainerPlasticSwaps": "సురక్షిత పాత్రల మార్పిడి",
  "habits.dirtyDozenWashingTips": "కూరగాయల శుభ్రత & రసాయన నివారణ చిట్కాలు",
  "habits.technology": "సాంకేతికత",
  "habits.mainPurpose": "ప్రధాన ఉద్దేశ్యం",
  "habits.mitoRebootRecommendation": "MitoReboot అధికారిక సిఫార్సు",
  "habits.doneWithWaterCategory": "నీటి కాలుష్య విభాగం పూర్తయింది",
  "habits.doneWithPesticidesCategory": "పురుగుమందుల విభాగం పూర్తయింది",
  "habits.doneWithMicroplasticsCategory": "మైక్రోప్లాస్టిక్ విభాగం పూర్తయింది",
  "habits.doneWithKitchenCategory": "వంటగది విభాగం పూర్తయింది",
  "habits.avoidLabel": "నివారించండి ❌",
  "habits.chooseLabel": "ఎంచుకోండి ✅",
  "habits.shopNow": "కొనుగోలు",
  "habits.yesLabel": "అవును",
  "habits.noLabel": "లేదు",

  "chatModal.dailyHealthSummary": "రోజువారీ ఆరోగ్య సారాంశం",
  "chatModal.checkinLoggedSuccess": "చెకిన్ విజయవంతంగా నమోదు చేయబడింది",
  "chatModal.checkinLoggedDesc": "మీ ఉపవాసం, సెల్యులార్ రిపేర్ మరియు రక్షణ లాగ్‌లు డాష్‌బోర్డ్‌లో అప్‌డేట్ చేయబడ్డాయి.",
  "chatModal.priorityActionPlanTomorrow": "రేపటి ప్రాధాన్యతా కార్యాచరణ ప్రణాళిక:",
  "chatModal.dailyCheckinReminder": "రోజువారీ AI రిమైండర్",
  "chatModal.selectReminderTime": "రిమైండర్ సమయాన్ని ఎంచుకోండి లేదా అలర్ట్‌లను పూర్తిగా ఆపివేయండి:",
  "chatModal.setTime": "సమయం సెట్ చేయండి",
  "chatModal.turnOffDailyReminder": "రోజువారీ రిమైండర్ ఆపివేయండి",
  "chatModal.testAlertNow": "అలర్ట్ పరీక్షించండి",
  "chatModal.fastAnswer": "త్వరిత సమాధానం:",
  "chatModal.uploadReportPrompt": "రిపోర్ట్ అప్‌లోడ్ చేయండి (PDF / CSV)",
  "chatModal.uploading": "అప్‌లోడ్ అవుతోంది...",
  "chatModal.stopSpeaking": "ఆపు",
  "chatModal.off": "ఆఫ్",
  "chatModal.editAnswer": "సమాధానాన్ని సవరించండి",

  "dash.glucoseLevel": "గ్లూకోజ్ స్థాయి:",
  "dash.libreviewCgm": "LibreView CGM",
  "dash.cgmHistoryDetails": "CGM చరిత్ర & సమకాలీకరణ వివరాలు",
  "dash.filesCount": "ఫైళ్లు",
  "dash.targetRange": "లక్ష్యం: 70–{{max}} mg/dL",
  "dash.logManualReadingPrompt": "మీ గ్లూకోమీటర్ నుండి రీడింగ్‌ను నమోదు చేయండి.",
  "dash.highStressCortisol": "అధిక ఒత్తిడి / కార్టిసాల్",
  "dash.calmNervousSystem": "ప్రశాంత నాడీ వ్యవస్థ",
  "dash.sleepDebt": "నిద్ర లోపం (<6 గంటలు)",
  "dash.restfulSleep": "7+ గంటల ప్రశాంత నిద్ర",
  "dash.tobaccoExposure": "పొగాకు ప్రభావం",
  "dash.tobaccoFree": "పొగాకు రహిత దినం",
  "dash.alcoholIntake": "మద్యపానం",
  "dash.zeroAlcohol": "మద్యం రహిత దినం",
  "dash.environmentalToxins": "పర్యావరణ విషపదార్థాలు",
  "dash.lowToxicBurden": "తక్కువ విష భారం",
  "dash.kitchenPlasticRisk": "వంటగది ప్లాస్టిక్ ప్రమాదం",
  "dash.safeKitchen": "సురక్షిత ప్లాస్టిక్ రహిత వంటగది",
  "dash.gastricAcidity": "గ్యాస్ట్రిక్ ఎసిడిటీ / జంక్ ఫుడ్",
  "dash.healthyGutOral": "ఆరోగ్యకరమైన జీర్ణశయాంతర వ్యవస్థ",
  "dash.circadianFasting": "సర్కేడియన్ ఉపవాసం (14+ గం)",
  "dash.aerobicMovement": "20+ నిమిషాల వ్యాయామం",
  "dash.antioxidantProtection": "యాంటీఆక్సిడెంట్ రక్షణ",
  "dash.powerOfBreath": "శ్వాస శక్తి & సంపూర్ణ స్పృహ",

  "diag.checkoutAndPay": "చెక్‌అవుట్ మరియు చెల్లించండి",
  "diag.trialSpecialOffer": "🎁 ప్రత్యేక ట్రయల్ ఆఫర్",
  "diag.trialOfferDesc": "పరీక్ష ప్రయోజనాల కోసం పూర్తిగా ఉచితంగా బుక్ చేసుకోవడానికి {{code}} కోడ్‌ను ఉపయోగించండి!",
  "diag.apply": "వర్తింపజేయి",
  "diag.codeAppliedSuccess": "✓ కోడ్ వర్తించబడింది! బుకింగ్ ఫీజు 0 కి తగ్గించబడింది.",
  "diag.discountApplied100": "100% తగ్గింపు వర్తించబడింది",
  "diag.dateTime": "తేదీ & సమయం",
  "diag.confirmBookingFree": "బుకింగ్‌ను నిర్ధారించండి (ఉచితం)",
  "diag.payViaRazorpay": "Razorpay ద్వారా ₹{{amount}} చెల్లించండి",
  "diag.processing": "ప్రాసెస్ అవుతోంది...",
  "diag.homeVisit": "ఇంటి సందర్శన",
  "diag.labVisit": "ల్యాబ్ సందర్శన",

  "appt.myNotesToDoctor": "📝 వైద్యునికి నా గమనికలు:",
  "appt.clinicInstructions": "🏥 డాక్టర్ నుండి క్లినిక్ సూచనలు:",
  "appt.openCalendarInvite": "Google క్యాలెండర్ ఆహ్వానాన్ని తెరవండి",
  "appt.joinGoogleMeet": "Google Meet లో చేరండి",

  "proto.dailyDoseTimings": "రోజువారీ మోతాదు సమయాలు & నిర్వహణ",
  "proto.noMedDosesToday": "ఈ రోజు ఎటువంటి మందుల మోతాదులు నమోదు చేయలేదు. వివరాలను పైన నమోదు చేయండి.",
  "proto.allMenstrualCycles": "నమోదైన అన్ని ఋతు చక్రాలు & క్రమబద్ధత",
  "proto.amPmLongitudinalLogs": "ఉదయం & సాయంత్రం రక్తపోటు లాగ్‌లు",

  "network.checkCellularSettings": "సెట్టింగ్‌లలో సెల్యులార్ / మొబైల్ డేటాను తనిఖీ చేయండి",
  "network.verifyWifiStrength": "వైఫై కనెక్షన్ మరియు సిగ్నల్ బలాన్ని ధృవీకరించండి",

  "sub.totalPrice": "మొత్తం ధర",
  "sub.billingInvoiceHistory": "బిల్లింగ్ & ఇన్వాయిస్ చరిత్ర",
  "sub.totalPaid": "చెల్లించిన మొత్తం:",
  "sub.daysFreeTrial": "🎁 {{days}} రోజుల ఉచిత ట్రయల్ చేర్చబడింది",
  "sub.startFreeTrial": "ఉచిత ట్రయల్ ప్రారంభించండి",
  "sub.subscribeNow": "ఇప్పుడే చందా తీసుకోండి (₹{{amount}})",

  "shop.patientReviews": "రోగి సమీక్షలు & ఫీడ్‌బ్యాక్",
  "shop.verifiedReviewsFor": "{{name}} కొరకు ధృవీకరించబడిన ఫీడ్‌బ్యాక్",
  "shop.verifiedPurchase": "ధృవీకరించబడిన కొనుగోలు",
  "shop.medicalHealthStore": "వైద్య & ఆరోగ్య స్టోర్",

  "legal.acceptAndContinue": "అంగీకరించి కొనసాగించండి",
  "legal.mandatoryAgreement": "తప్పనిసరి ఒప్పందం",
  "legal.savingAcceptance": "అంగీకారం సేవ్ అవుతోంది...",
  "legal.scrollToBottomToContinue": "కొనసాగడానికి దయచేసి క్రిందికి స్క్రోల్ చేయండి.",
  "legal.scrollToBottom": "క్రిందికి స్క్రోల్ చేయండి",
  "legal.reachedBottomPrompt": "మీరు పత్రం యొక్క దిగువ భాగానికి చేరుకున్నారు. ఇప్పుడు నిబంధనలను అంగీకరించవచ్చు.",
  "legal.termsCheckboxLabel": "నేను నిరాకరణ, గోప్యతా నోటీసు మరియు ఉపయోగ నిబంధనలను చదివాను మరియు అర్థం చేసుకున్నాను, వాటికి కట్టుబడి ఉండటానికి అంగీకరిస్తున్నాను.",
  "legal.termsInstruction": "MitoReboot మాస్టర్ డిస్క్లైమర్, గోప్యతా నోటీసు మరియు ఉపయోగ నిబంధనలను జాగ్రత్తగా చదవండి. అంగీకరించే ముందు మీరు పత్రం చివరికి స్క్రోల్ చేయాలి."
};

const knKeys = {
  "habits.waterFreeZero": "ಹೌದು, ಕಲ್ಮಶಗಳಿಲ್ಲ (0)",
  "habits.waterNotSureMinus1": "ಇಲ್ಲ / ಖಚಿತವಿಲ್ಲ (-1)",
  "habits.pesticidesConsumeMinus1": "ಹೌದು, ಮುನ್ನೆಚ್ಚರಿಕೆಯಿಲ್ಲದೆ ಸೇವಿಸುತ್ತೇನೆ (-1)",
  "habits.pesticidesWashZero": "ಇಲ್ಲ, ತೊಳೆಯುತ್ತೇನೆ ಅಥವಾ ಸಾವಯವ ಆಯ್ಕೆ ಮಾಡುತ್ತೇನೆ (0)",
  "habits.microplasticsRegularMinus1": "ಹೌದು, ನಿಯಮಿತವಾಗಿ (-1)",
  "habits.microplasticsAvoidZero": "ಇಲ್ಲ, ಪ್ಲಾಸ್ಟಿಕ್ ಪಾತ್ರೆಗಳನ್ನು ತಪ್ಪಿಸುತ್ತೇನೆ (0)",
  "habits.mudDirtCysts": "ಮಣ್ಣು, ಧೂಳು ಮತ್ತು ಸಾಮಾನ್ಯ ಕಲ್ಮಶಗಳು",
  "habits.bacteriaVirusesOnly": "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಮತ್ತು ವೈರಸ್‌ಗಳು ಮಾತ್ರ",
  "habits.pesticidesChlorineVoc": "ಕೀಟನಾಶಕಗಳು, ಕ್ಲೋರಿನ್, ಹಾನಿಕಾರಕ ಅನಿಲಗಳು, ಕ್ಯಾನ್ಸರ್ ಕಾರಕಗಳು",
  "habits.heavyMetalsArsenic": "ಭಾರ ಲೋಹಗಳು, ಆರ್ಸೆನಿಕ್, ನೈಟ್ರೇಟ್, ಮೈಕ್ರೋಪ್ಲಾಸ್ಟಿಕ್",
  "habits.organicReducesPesticides": "ಸಾವಯವ ಉತ್ಪನ್ನಗಳನ್ನು ಆರಿಸುವುದರಿಂದ ಆಹಾರದಲ್ಲಿನ ಕೀಟನಾಶಕದ ಮಟ್ಟ ಗಣನೀಯವಾಗಿ ಕಡಿಮೆಯಾಗುತ್ತದೆ.",
  "habits.orderOrganicFood": "ಸಾವಯವ ಆಹಾರವನ್ನು ಆರ್ಡರ್ ಮಾಡಲು ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ",
  "habits.swapPlasticStorage": "ಪ್ಲಾಸ್ಟಿಕ್ ಬದಲಿಗೆ ಬೊರೊಸಿಲಿಕೇಟ್ ಗಾಜು ಅಥವಾ ಸ್ಟೇನ್‌ಲೆಸ್ ಸ್ಟೀಲ್ ಪಾತ್ರೆಗಳನ್ನು ಬಳಸಿ.",
  "habits.orderPlasticFreeProducts": "ಪ್ಲಾಸ್ಟಿಕ್ ಮುಕ್ತ ಉತ್ಪನ್ನಗಳನ್ನು ಆರ್ಡರ್ ಮಾಡಲು ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ",
  "habits.avoidPetBottles": "ಬಿಸಾಡಬಹುದಾದ PET ಬಾಟಲಿಗಳು, ಮೈಕ್ರೋವೇವ್‌ನಲ್ಲಿ ಪ್ಲಾಸ್ಟಿಕ್ ಬಿಸಿ ಮಾಡುವುದು, ಪ್ಲಾಸ್ಟಿಕ್ ಟೀ ಬ್ಯಾಗ್‌ಗಳು.",
  "habits.chooseGlassBottles": "ಬೊರೊಸಿಲಿಕೇಟ್ ಗಾಜಿನ ಬಾಟಲಿಗಳು, ಸ್ಟೀಲ್ ಪಾತ್ರೆಗಳು, ಸೆರಾಮಿಕ್ ವಸ್ತುಗಳು.",
  "habits.isDrinkingWater": "ನಿಮ್ಮ ಕುಡಿಯುವ ನೀರು",
  "habits.areUtensils": "ನಿಮ್ಮ ಅಡುಗೆ ಪಾತ್ರೆಗಳು",
  "habits.areCommodities": "ದವಸ ಧಾನ್ಯಗಳು ಮತ್ತು ಪದಾರ್ಥಗಳು",
  "habits.kitchenMicroplasticsAudit": "ಅಡುಗೆಮನೆ ಮೈಕ್ರೋಪ್ಲಾಸ್ಟಿಕ್ ಮತ್ತು ಪಾತ್ರೆಗಳ ಪರಿಶೀಲನೆ",
  "habits.safeContainerPlasticSwaps": "ಸುರಕ್ಷಿತ ಪಾತ್ರೆಗಳ ಬದಲಿಗಳು",
  "habits.dirtyDozenWashingTips": "ತರಕಾರಿ ತೊಳೆಯುವ ಮತ್ತು ಕೀಟನಾಶಕ ನಿವಾರಣೆಯ ಸಲಹೆಗಳು",
  "habits.technology": "ತಂತ್ರಜ್ಞಾನ",
  "habits.mainPurpose": "ಮುಖ್ಯ ಉದ್ದೇಶ",
  "habits.mitoRebootRecommendation": "MitoReboot ಅಧಿಕೃತ ಶಿಫಾರಸು",
  "habits.doneWithWaterCategory": "ನೀರಿನ ಮಾಲಿನ್ಯ ವಿಭಾಗ ಮುಕ್ತಾಯವಾಗಿದೆ",
  "habits.doneWithPesticidesCategory": "ಕೀಟನಾಶಕಗಳ ವಿಭಾಗ ಮುಕ್ತಾಯವಾಗಿದೆ",
  "habits.doneWithMicroplasticsCategory": "ಮೈಕ್ರೋಪ್ಲಾಸ್ಟಿಕ್ ವಿಭಾಗ ಮುಕ್ತಾಯವಾಗಿದೆ",
  "habits.doneWithKitchenCategory": "ಅಡುಗೆಮನೆ ವಿಭಾಗ ಮುಕ್ತಾಯವಾಗಿದೆ",
  "habits.avoidLabel": "ತಪ್ಪಿಸಿ ❌",
  "habits.chooseLabel": "ಆಯ್ಕೆಮಾಡಿ ✅",
  "habits.shopNow": "ಖರೀದಿಸಿ",
  "habits.yesLabel": "ಹೌದು",
  "habits.noLabel": "ಇಲ್ಲ",

  "chatModal.dailyHealthSummary": "ದೈನಂದಿನ ಆರೋಗ್ಯ ಸಾರಾಂಶ",
  "chatModal.checkinLoggedSuccess": "ಚೆಕ್-ಇನ್ ಯಶಸ್ವಿಯಾಗಿ ದಾಖಲಾಗಿದೆ",
  "chatModal.checkinLoggedDesc": "ನಿಮ್ಮ ಉಪವಾಸ, ಕೋಶೀಯ ದುರಸ್ತಿ ಮತ್ತು ತಡೆಗಟ್ಟುವಿಕೆಯ ವಿವರಗಳನ್ನು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ನವೀಕರಿಸಲಾಗಿದೆ.",
  "chatModal.priorityActionPlanTomorrow": "ನಾಳೆಯ ಆದ್ಯತೆಯ ಕ್ರಿಯಾ ಯೋಜನೆ:",
  "chatModal.dailyCheckinReminder": "ದೈನಂದಿನ AI ಜ್ಞಾಪನೆ",
  "chatModal.selectReminderTime": "ಜ್ಞಾಪನೆಯ ಸಮಯವನ್ನು ಆರಿಸಿ ಅಥವಾ ಎಚ್ಚರಿಕೆಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ:",
  "chatModal.setTime": "ಸಮಯ ಹೊಂದಿಸಿ",
  "chatModal.turnOffDailyReminder": "ದೈನಂದಿನ ಜ್ಞಾಪನೆ ಆಫ್ ಮಾಡಿ",
  "chatModal.testAlertNow": "ಎಚ್ಚರಿಕೆ ಪರೀಕ್ಷಿಸಿ",
  "chatModal.fastAnswer": "ತ್ವರಿತ ಉತ್ತರ:",
  "chatModal.uploadReportPrompt": "ವರದಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (PDF / CSV)",
  "chatModal.uploading": "ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
  "chatModal.stopSpeaking": "ನಿಲ್ಲಿಸಿ",
  "chatModal.off": "ಆಫ್",
  "chatModal.editAnswer": "ಉತ್ತರವನ್ನು ತಿದ್ದಿ",

  "dash.glucoseLevel": "ಗ್ಲುಕೋಸ್ ಮಟ್ಟ:",
  "dash.libreviewCgm": "LibreView CGM",
  "dash.cgmHistoryDetails": "CGM ಇತಿಹಾಸ & ಸಿಂಕ್ ವಿವರಗಳು",
  "dash.filesCount": "ಫೈಲ್‌ಗಳು",
  "dash.targetRange": "ಗುರಿ: 70–{{max}} mg/dL",
  "dash.logManualReadingPrompt": "ಗ್ಲುಕೋಮೀಟರ್‌ನಿಂದ ರೀಡಿಂಗ್ ಅನ್ನು ಹಸ್ತಚಾಲಿತವಾಗಿ ನಮೂದಿಸಿ.",
  "dash.highStressCortisol": "ಹೆಚ್ಚಿನ ಒತ್ತಡ / ಕಾರ್ಟಿಸೋಲ್",
  "dash.calmNervousSystem": "ಶಾಂತ ನರಮಂಡಲ",
  "dash.sleepDebt": "ನಿದ್ರೆಯ ಕೊರತೆ (<6 ಗಂಟೆ)",
  "dash.restfulSleep": "7+ ಗಂಟೆಗಳ ವಿಶ್ರಾಂತಿಯುತ ನಿದ್ರೆ",
  "dash.tobaccoExposure": "ತಂಬಾಕು ಸೇವನೆ / ಧೂಮಪಾನ",
  "dash.tobaccoFree": "ತಂಬಾಕು ಮುಕ್ತ ದಿನ",
  "dash.alcoholIntake": "ಮದ್ಯಪಾನ",
  "dash.zeroAlcohol": "ಮದ್ಯ ಮುಕ್ತ ದಿನ",
  "dash.environmentalToxins": "ಪರಿಸರ ವಿಷಗಳು",
  "dash.lowToxicBurden": "ಕಡಿಮೆ ವಿಷಕಾರಿ ಹೊರೆ",
  "dash.kitchenPlasticRisk": "ಅಡುಗೆಮನೆಯ ಪ್ಲಾಸ್ಟಿಕ್ ಅಪಾಯ",
  "dash.safeKitchen": "ಸುರಕ್ಷಿತ ಪ್ಲಾಸ್ಟಿಕ್ ಮುಕ್ತ ಅಡುಗೆಮನೆ",
  "dash.gastricAcidity": "ಜಠರದುರಿತ / ಸಂಸ್ಕರಿಸಿದ ಆಹಾರ",
  "dash.healthyGutOral": "ಆರೋಗ್ಯಕರ ಕರುಳು ಮತ್ತು ಬಾಯಿ ಸಮತೋಲನ",
  "dash.circadianFasting": "ಸರ್ಕಾಡಿಯನ್ ಉಪವಾಸ (14+ ಗಂಟೆ)",
  "dash.aerobicMovement": "20+ ನಿಮಿಷಗಳ ವ್ಯಾಯಾಮ",
  "dash.antioxidantProtection": "ಆಂಟಿಆಕ್ಸಿಡೆಂಟ್ ರಕ್ಷಣೆ",
  "dash.powerOfBreath": "ಉಸಿರಾಟದ ಶಕ್ತಿ & ಸಾವಧಾನತೆ",

  "diag.checkoutAndPay": "ಚೆಕ್‌ಔಟ್ ಮತ್ತು ಪಾವತಿಸಿ",
  "diag.trialSpecialOffer": "🎁 ಪ್ರಾಯೋಗಿಕ ವಿಶೇಷ ಕೊಡುಗೆ",
  "diag.trialOfferDesc": "ಪರೀಕ್ಷಾರ್ಥವಾಗಿ ಈ ಪರೀಕ್ಷೆಯನ್ನು ಉಚಿತವಾಗಿ ಕಾಯ್ದಿರಿಸಲು {{code}} ಕೋಡ್ ಬಳಸಿ!",
  "diag.apply": "ಅನ್ವಯಿಸಿ",
  "diag.codeAppliedSuccess": "✓ ಕೋಡ್ ಅನ್ವಯಿಸಲಾಗಿದೆ! ಶುಲ್ಕ 0 ಕ್ಕೆ ಇಳಿದಿದೆ.",
  "diag.discountApplied100": "100% ರಿಯಾಯಿತಿ ಅನ್ವಯಿಸಲಾಗಿದೆ",
  "diag.dateTime": "ದಿನಾಂಕ & ಸಮಯ",
  "diag.confirmBookingFree": "ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ (ಉಚಿತ)",
  "diag.payViaRazorpay": "Razorpay ಮೂಲಕ ₹{{amount}} ಪಾವತಿಸಿ",
  "diag.processing": "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
  "diag.homeVisit": "ಮನೆ ಭೇಟಿ",
  "diag.labVisit": "ಲ್ಯಾಬ್ ಭೇಟಿ",

  "appt.myNotesToDoctor": "📝 ವೈದ್ಯರಿಗೆ ನನ್ನ ಟಿಪ್ಪಣಿಗಳು:",
  "appt.clinicInstructions": "🏥 ವೈದ್ಯರಿಂದ ಕ್ಲಿನಿಕ್ ಸೂಚನೆಗಳು:",
  "appt.openCalendarInvite": "Google ಕ್ಯಾಲೆಂಡರ್ ಆಹ್ವಾನವನ್ನು ತೆರೆಯಿರಿ",
  "appt.joinGoogleMeet": "Google Meet ಸೇರಿಕೊಳ್ಳಿ",

  "proto.dailyDoseTimings": "ದೈನಂದಿನ ಡೋಸ್ ಸಮಯ & ನಿರ್ವಹಣೆ",
  "proto.noMedDosesToday": "ಇಂದು ಯಾವುದೇ ಔಷಧಿಗಳನ್ನು ದಾಖಲಿಸಲಾಗಿಲ್ಲ. ವಿವರಗಳನ್ನು ಮೇಲೆ ನಮೂದಿಸಿ.",
  "proto.allMenstrualCycles": "ದಾಖಲಾದ ಋತುಚಕ್ರಗಳು & ನಿಯಮಿತತೆ",
  "proto.amPmLongitudinalLogs": "ಬೆಳಿಗ್ಗೆ & ಸಂಜೆಯ ರಕ್ತದೊತ್ತಡ ದಾಖಲೆಗಳು",

  "network.checkCellularSettings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಮೊಬೈಲ್ ಡೇಟಾವನ್ನು ಪರಿಶೀಲಿಸಿ",
  "network.verifyWifiStrength": "ವೈಫೈ ಸಂಪರ್ಕ ಮತ್ತು ಸಿಗ್ನಲ್ ಸಾಮರ್ಥ್ಯವನ್ನು ಪರಿಶೀಲಿಸಿ",

  "sub.totalPrice": "ಒಟ್ಟು ಬೆಲೆ",
  "sub.billingInvoiceHistory": "ಬಿಲ್ಲಿಂಗ್ & ಇನ್‌ವಾಯ್ಸ್ ಇತಿಹಾಸ",
  "sub.totalPaid": "ಪಾವತಿಸಿದ ಒಟ್ಟು ಮೊತ್ತ:",
  "sub.daysFreeTrial": "🎁 {{days}} ದಿನಗಳ ಉಚಿತ ಪ್ರಯೋಗ ಒಳಗೊಂಡಿದೆ",
  "sub.startFreeTrial": "ಉಚಿತ ಪ್ರಯೋಗವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
  "sub.subscribeNow": "ಈಗ ಚಂದಾದಾರರಾಗಿ (₹{{amount}})",

  "shop.patientReviews": "ರೋಗಿಗಳ ವಿಮರ್ಶೆಗಳು & ಪ್ರತಿಕ್ರಿಯೆ",
  "shop.verifiedReviewsFor": "{{name}} ಗಾಗಿ ಪರಿಶೀಲಿಸಿದ ಪ್ರತಿಕ್ರಿಯೆ",
  "shop.verifiedPurchase": "ಖಚಿತಪಡಿಸಿದ ಖರೀದಿ",
  "shop.medicalHealthStore": "ವೈದ್ಯಕೀಯ ಮತ್ತು ಆರೋಗ್ಯ ಮಳಿಗೆ",

  "legal.acceptAndContinue": "ಸ್ವೀಕರಿಸಿ ಮುಂದುವರಿಯಿರಿ",
  "legal.mandatoryAgreement": "ಕಡ್ಡಾಯ ಒಪ್ಪಂದ",
  "legal.savingAcceptance": "ಸ್ವೀಕಾರವನ್ನು ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
  "legal.scrollToBottomToContinue": "ಮುಂದುವರಿಯಲು ದಯವಿಟ್ಟು ಕೆಳಗೆ ಸ್ಕ್ರಾಲ್ ಮಾಡಿ.",
  "legal.scrollToBottom": "ಕೆಳಗೆ ಸ್ಕ್ರಾಲ್ ಮಾಡಿ",
  "legal.reachedBottomPrompt": "ನೀವು ದಾಖಲೆಯ ಕೆಳಭಾಗವನ್ನು ತಲುಪಿದ್ದೀರಿ. ಈಗ ನಿಯಮಗಳನ್ನು ಒಪ್ಪಿಕೊಳ್ಳಬಹುದು.",
  "legal.termsCheckboxLabel": "ನಾನು ಹಕ್ಕುತ್ಯಾಗ, ಗೌಪ್ಯತಾ ಸೂಚನೆ ಮತ್ತು ಬಳಕೆಯ ನಿಯಮಗಳನ್ನು ಓದಿದ್ದೇನೆ ಮತ್ತು ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೇನೆ ಮತ್ತು ಅವುಗಳಿಗೆ ಬದ್ಧವಾಗಿರಲು ಒಪ್ಪುತ್ತೇನೆ.",
  "legal.termsInstruction": "MitoReboot ಮಾಸ್ಟರ್ ಹಕ್ಕುತ್ಯಾಗ, ಗೌಪ್ಯತಾ ಸೂಚನೆ ಮತ್ತು ಬಳಕೆಯ ನಿಯಮಗಳನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ಓದಿ. ಒಪ್ಪಿಕೊಳ್ಳುವ ಮೊದಲು ನೀವು ಕೆಳಗೆ ಸ್ಕ್ರಾಲ್ ಮಾಡಬೇಕು."
};

const hiKeys = {
  "habits.waterFreeZero": "हाँ, यह मुक्त है (0)",
  "habits.waterNotSureMinus1": "नहीं / निश्चित नहीं (-1)",
  "habits.pesticidesConsumeMinus1": "हाँ, बिना किसी सावधानी के लेता हूँ (-1)",
  "habits.pesticidesWashZero": "नहीं, धोता हूँ या जैविक चुनता हूँ (0)",
  "habits.microplasticsRegularMinus1": "हाँ, नियमित रूप से (-1)",
  "habits.microplasticsAvoidZero": "नहीं, प्लास्टिक बर्तनों से बचता हूँ (0)",
  "habits.mudDirtCysts": "मिट्टी, धूल और बुनियादी अशुद्धियाँ",
  "habits.bacteriaVirusesOnly": "केवल बैक्टीरिया और वायरस",
  "habits.pesticidesChlorineVoc": "कीटनाशक, क्लोरीन, हानिकारक गैसें, कार्सिनोजेन्स",
  "habits.heavyMetalsArsenic": "भारी धातुएं, आर्सेनिक, नाइट्रेट्स, माइक्रोप्लास्टिक",
  "habits.organicReducesPesticides": "जैविक उपज चुनने से आपके आहार में रासायनिक कीटनाशकों का स्तर काफी कम हो जाता है।",
  "habits.orderOrganicFood": "जैविक भोजन ऑर्डर करने के लिए यहाँ क्लिक करें",
  "habits.swapPlasticStorage": "प्लास्टिक की जगह बोरोसिलिकेट ग्लास या स्टेनलेस स्टील कंटेनर का उपयोग करें।",
  "habits.orderPlasticFreeProducts": "प्लास्टिक मुक्त उत्पाद ऑर्डर करने के लिए यहाँ क्लिक करें",
  "habits.avoidPetBottles": "डिस्पोजेबल पीईटी बोतलें, माइक्रोवेव में प्लास्टिक गर्म करना, प्लास्टिक टी बैग।",
  "habits.chooseGlassBottles": "बोरोसिलिकेट ग्लास बोतलें, स्टील कंटेनर, सिरेमिक बर्तन।",
  "habits.isDrinkingWater": "क्या आपका पीने का पानी",
  "habits.areUtensils": "क्या आपके बर्तन",
  "habits.areCommodities": "क्या सामग्री और उत्पाद",
  "habits.kitchenMicroplasticsAudit": "रसोई माइक्रोप्लास्टिक और बर्तन ऑडिट",
  "habits.safeContainerPlasticSwaps": "सुरक्षित कंटेनर विकल्प",
  "habits.dirtyDozenWashingTips": "सब्जी धुलाई और अवशेष हटाने के सुझाव",
  "habits.technology": "तकनीक",
  "habits.mainPurpose": "मुख्य उद्देश्य",
  "habits.mitoRebootRecommendation": "MitoReboot आधिकारिक सिफारिश",
  "habits.doneWithWaterCategory": "जल प्रदूषण श्रेणी पूर्ण",
  "habits.doneWithPesticidesCategory": "कीटनाशक श्रेणी पूर्ण",
  "habits.doneWithMicroplasticsCategory": "माइक्रोप्लास्टिक श्रेणी पूर्ण",
  "habits.doneWithKitchenCategory": "रसोई श्रेणी पूर्ण",
  "habits.avoidLabel": "बचें ❌",
  "habits.chooseLabel": "चुनें ✅",
  "habits.shopNow": "खरीदें",
  "habits.yesLabel": "हाँ",
  "habits.noLabel": "नहीं",

  "chatModal.dailyHealthSummary": "दैनिक स्वास्थ्य सारांश",
  "chatModal.checkinLoggedSuccess": "चेक-इन सफलतापूर्वक दर्ज किया गया",
  "chatModal.checkinLoggedDesc": "आपका उपवास, कोशिकीय मरम्मत और सुरक्षा रिकॉर्ड डैशबोर्ड पर अपडेट कर दिए गए हैं।",
  "chatModal.priorityActionPlanTomorrow": "कल के लिए प्राथमिकता कार्य योजना:",
  "chatModal.dailyCheckinReminder": "दैनिक AI रिमाइंडर",
  "chatModal.selectReminderTime": "रिमाइंडर का समय चुनें या अलर्ट पूरी तरह से बंद करें:",
  "chatModal.setTime": "समय सेट करें",
  "chatModal.turnOffDailyReminder": "दैनिक रिमाइंडर बंद करें",
  "chatModal.testAlertNow": "अलर्ट का परीक्षण करें",
  "chatModal.fastAnswer": "त्वरित उत्तर:",
  "chatModal.uploadReportPrompt": "रिपोर्ट अपलोड करें (PDF / CSV)",
  "chatModal.uploading": "अपलोड हो रहा है...",
  "chatModal.stopSpeaking": "रोकें",
  "chatModal.off": "बंद",
  "chatModal.editAnswer": "उत्तर संपादित करें",

  "dash.glucoseLevel": "ग्लूकोज स्तर:",
  "dash.libreviewCgm": "LibreView CGM",
  "dash.cgmHistoryDetails": "CGM इतिहास और सिंक विवरण",
  "dash.filesCount": "फ़ाइलें",
  "dash.targetRange": "लक्ष्य: 70–{{max}} mg/dL",
  "dash.logManualReadingPrompt": "ग्लूकोमीटर से रीडिंग मैन्युअल रूप से दर्ज करें।",
  "dash.highStressCortisol": "उच्च तनाव / कोर्टिसोल",
  "dash.calmNervousSystem": "शांत तंत्रिका तंत्र",
  "dash.sleepDebt": "नींद की कमी (<6 घंटे)",
  "dash.restfulSleep": "7+ घंटे की आरामदायक नींद",
  "dash.tobaccoExposure": "तंबाकू का सेवन / धूम्रपान",
  "dash.tobaccoFree": "तंबाकू मुक्त दिन",
  "dash.alcoholIntake": "शराब का सेवन",
  "dash.zeroAlcohol": "शराब मुक्त दिन",
  "dash.environmentalToxins": "पर्यावरणीय विषाक्त पदार्थ",
  "dash.lowToxicBurden": "कम विषाक्त भार",
  "dash.kitchenPlasticRisk": "रसोई में प्लास्टिक का जोखिम",
  "dash.safeKitchen": "सुरक्षित प्लास्टिक-मुक्त रसोई",
  "dash.gastricAcidity": "गैस्ट्रिक एसिडिटी / रिफाइंड खाना",
  "dash.healthyGutOral": "स्वस्थ आंत और मौखिक संतुलन",
  "dash.circadianFasting": "सर्कैडियन उपवास (14+ घंटे)",
  "dash.aerobicMovement": "20+ मिनट का व्यायाम",
  "dash.antioxidantProtection": "एंटीऑक्सीडेंट सेल सुरक्षा",
  "dash.powerOfBreath": "श्वास की शक्ति और सचेतनता",

  "diag.checkoutAndPay": "चेकआउट और भुगतान",
  "diag.trialSpecialOffer": "🎁 विशेष ट्रायल ऑफर",
  "diag.trialOfferDesc": "परीक्षण के लिए इसे पूरी तरह मुफ्त बुक करने के लिए कोड {{code}} का उपयोग करें!",
  "diag.apply": "लागू करें",
  "diag.codeAppliedSuccess": "✓ कोड लागू हुआ! बुकिंग शुल्क 0 हो गया।",
  "diag.discountApplied100": "100% छूट लागू",
  "diag.dateTime": "दिनांक और समय",
  "diag.confirmBookingFree": "बुकिंग की पुष्टि करें (मुफ्त)",
  "diag.payViaRazorpay": "Razorpay के माध्यम से ₹{{amount}} भुगतान करें",
  "diag.processing": "प्रक्रिया जारी है...",
  "diag.homeVisit": "होम विजिट",
  "diag.labVisit": "लैब विजिट",

  "appt.myNotesToDoctor": "📝 डॉक्टर के लिए मेरे नोट्स:",
  "appt.clinicInstructions": "🏥 डॉक्टर से क्लिनिक निर्देश:",
  "appt.openCalendarInvite": "Google कैलेंडर आमंत्रण खोलें",
  "appt.joinGoogleMeet": "Google Meet में शामिल हों",

  "proto.dailyDoseTimings": "दैनिक खुराक समय और पालन",
  "proto.noMedDosesToday": "आज कोई दवा दर्ज नहीं की गई है। विवरण ऊपर दर्ज करें।",
  "proto.allMenstrualCycles": "दर्ज किए गए मासिक धर्म चक्र और नियमितता",
  "proto.amPmLongitudinalLogs": "सुबह और शाम के रक्तचाप रिकॉर्ड",

  "network.checkCellularSettings": "सेटिंग्स में मोबाइल डेटा स्विच की जाँच करें",
  "network.verifyWifiStrength": "वाई-फ़ाई कनेक्शन और सिग्नल की शक्ति की जाँच करें",

  "sub.totalPrice": "कुल कीमत",
  "sub.billingInvoiceHistory": "बिलिंग और चालान इतिहास",
  "sub.totalPaid": "कुल भुगतान:",
  "sub.daysFreeTrial": "🎁 {{days}} दिनों का निःशुल्क परीक्षण शामिल",
  "sub.startFreeTrial": "निःशुल्क परीक्षण शुरू करें",
  "sub.subscribeNow": "अभी सदस्यता लें (₹{{amount}})",

  "shop.patientReviews": "मरीजों की समीक्षाएं और प्रतिक्रिया",
  "shop.verifiedReviewsFor": "{{name}} के लिए सत्यापित प्रतिक्रिया",
  "shop.verifiedPurchase": "सत्यापित खरीद",
  "shop.medicalHealthStore": "चिकित्सा और स्वास्थ्य स्टोर",

  "legal.acceptAndContinue": "स्वीकार करें और जारी रखें",
  "legal.mandatoryAgreement": "अनिवार्य अनुबंध",
  "legal.savingAcceptance": "स्वीकृति सहेजी जा रही है...",
  "legal.scrollToBottomToContinue": "जारी रखने के लिए कृपया नीचे स्क्रॉल करें।",
  "legal.scrollToBottom": "नीचे स्क्रॉल करें",
  "legal.reachedBottomPrompt": "आप दस्तावेज़ के अंत तक पहुँच गए हैं। अब आप नीचे दी गई शर्तों को स्वीकार कर सकते हैं।",
  "legal.termsCheckboxLabel": "मैंने अस्वीकरण, गोपनीयता नोटिस और उपयोग की शर्तों को पढ़ और समझ लिया है, और मैं उनसे बाध्य होने के लिए सहमत हूँ।",
  "legal.termsInstruction": "कृपया MitoReboot अस्वीकरण, गोपनीयता नोटिस और उपयोग की शर्तों को ध्यान से पढ़ें। स्वीकार करने से पहले आपको नीचे तक स्क्रॉल करना होगा।"
};

function appendKeys(filePath, newKeys) {
  let content = fs.readFileSync(filePath, 'utf8');
  const insertIndex = content.lastIndexOf('} as const;');
  if (insertIndex === -1) {
    console.error('Could not find } as const; in', filePath);
    return;
  }
  
  let additions = '\n  // --- UNIVERSAL ZERO-MIXED-LANGUAGE HARDCODED REPLACEMENTS ---\n';
  Object.keys(newKeys).forEach(k => {
    // only if not already present
    if (!content.includes(`"${k}":`)) {
      additions += `  "${k}": ${JSON.stringify(newKeys[k])},\n`;
    }
  });

  content = content.slice(0, insertIndex) + additions + content.slice(insertIndex);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Appended keys to', filePath);
}

appendKeys('./user/src/i18n/locales/en.ts', enKeys);
appendKeys('./user/src/i18n/locales/ta.ts', taKeys);
appendKeys('./user/src/i18n/locales/te.ts', teKeys);
appendKeys('./user/src/i18n/locales/kn.ts', knKeys);
appendKeys('./user/src/i18n/locales/hi.ts', hiKeys);
console.log('All 5 locales updated with 100% key parity.');
