const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '../src/i18n/locales/en.ts');
const taPath = path.join(__dirname, '../src/i18n/locales/ta.ts');
const knPath = path.join(__dirname, '../src/i18n/locales/kn.ts');
const hiPath = path.join(__dirname, '../src/i18n/locales/hi.ts');

const remainingBatch = {
  en: {
    "dashboard.apptWith": "Appt with",
    "dashboard.doctor": "Doctor",
    "dashboard.at": "at",
    "dashboard.upcoming": "Upcoming",
    "dashboard.metabolicFasting": "Circadian Metabolic Fasting",
    "dashboard.autophagy": "Autophagy & cellular alignment",
    "dashboard.logToday": "Log today",
    "dashboard.continueHeader": "Continue Where You Left Off",
    "chatbot.completed": "completed",
    "chatbot.speaking": "SPEAKING",
    "gia.optBreast": "Breast cancer",
    "gia.optOvarian": "Ovarian cancer",
    "gia.optColorectal": "Colorectal cancer",
    "gia.optEndometrial": "Endometrial cancer",
    "gia.optPancreatic": "Pancreatic cancer",
    "gia.optProstate": "Prostate cancer",
    "common.refresh": "Refresh Data",
    "rateOrder": "Rate Products",
    "openDailyCheckinChatbot": "Open AI Daily Check-in Assistant",
    "appBackButton": "Back",
    "common.logged": "Logged",
    "common.minutes": "Minutes",
    "Yes": "Yes",
    "No": "No",
    "Skip": "Skip",
    "yes": "Yes",
    "no": "No",
    "Stress": "Stress Management",
    "Sleep": "Sleep & Recovery",
    "Smoking": "Smoking Cessation",
    "Alcohol": "Alcohol Moderation",
    "Substances": "Substance Reduction",
    "Environmental": "Environmental Safety",
    "Kitchen": "Kitchen Detox",
    "Obesity": "Weight & Metabolism",
    "Dental": "Dental & Oral Care",
    "Gastritis": "Gastritis & Gut Health",
    "Genetic": "Hereditary Cancer Risk",
    "Fasting": "Intermittent Fasting",
    "Movement": "Physical Movement",
    "Stillness": "Stillness & Meditation",
    "Breath": "Breathwork",
    "Joy": "Joy & Mental Wellbeing",
    "Antioxidants": "Antioxidant Nutrition",
    "SaferProducts": "Toxin-Free Products",
    "CancerScreening": "Cancer Screening",
    "IndianCancers": "Regional Cancer Analytics"
  },
  ta: {
    "dashboard.apptWith": "மருத்துவ சந்திப்பு:",
    "dashboard.doctor": "மருத்துவர்",
    "dashboard.at": "நேரம்:",
    "dashboard.upcoming": "வரவிருக்கும்",
    "dashboard.metabolicFasting": "சர்க்காடியன் வளர்சிதை மாற்ற விரதம்",
    "dashboard.autophagy": "ஆட்டோபேஜி & செல் சீரமைப்பு",
    "dashboard.logToday": "இன்றைய பதிவு",
    "dashboard.continueHeader": "முந்தையதை தொடரவும்",
    "chatbot.completed": "முடிந்தது",
    "chatbot.speaking": "பேசுகிறது",
    "gia.optBreast": "மார்பகப் புற்றுநோய்",
    "gia.optOvarian": "கருப்பை புற்றுநோய்",
    "gia.optColorectal": "பெருங்குடல் புற்றுநோய்",
    "gia.optEndometrial": "எண்டோமெட்ரியல் புற்றுநோய்",
    "gia.optPancreatic": "கணையப் புற்றுநோய்",
    "gia.optProstate": "புரோஸ்டேட் புற்றுநோய்",
    "common.refresh": "தரவை புதுப்பி",
    "rateOrder": "தயாரிப்புகளை மதிப்பிடுங்கள்",
    "openDailyCheckinChatbot": "AI தினசரி பரிசோதனை உதவியாளரைத் திற",
    "appBackButton": "பின்செல்",
    "common.logged": "பதிவு செய்யப்பட்டது",
    "common.minutes": "நிமிடங்கள்",
    "Yes": "ஆம்",
    "No": "இல்லை",
    "Skip": "தவிர்",
    "yes": "ஆம்",
    "no": "இல்லை",
    "Stress": "மன அழுத்த மேலாண்மை",
    "Sleep": "தூக்கம் & மீட்பு",
    "Smoking": "புகைபிடித்தல் நிறுத்தம்",
    "Alcohol": "மது கட்டுப்பாடு",
    "Substances": "பொருட்கள் குறைப்பு",
    "Environmental": "சுற்றுச்சூழல் பாதுகாப்பு",
    "Kitchen": "சமையலறை நச்சுநீக்கம்",
    "Obesity": "எடை & வளர்சிதை மாற்றம்",
    "Dental": "பல் & வாய்வழி பராமரிப்பு",
    "Gastritis": "இரைப்பை அழற்சி & குடல் ஆரோக்கியம்",
    "Genetic": "பரம்பரை புற்றுநோய் ஆபத்து",
    "Fasting": "இடைப்பட்ட விரதம்",
    "Movement": "உடல் இயக்கம்",
    "Stillness": "அமைதி & தியானம்",
    "Breath": "சுவாசப் பயிற்சி",
    "Joy": "மகிழ்ச்சி & மன நலம்",
    "Antioxidants": "ஆன்டிஆக்ஸிடன்ட் ஊட்டச்சத்து",
    "SaferProducts": "நச்சு இல்லாத பொருட்கள்",
    "CancerScreening": "புற்றுநோய் பரிசோதனை",
    "IndianCancers": "பிராந்திய புற்றுநோய் பகுப்பாய்வு"
  },
  kn: {
    "dashboard.apptWith": "ವೈದ್ಯರ ಭೇಟಿ:",
    "dashboard.doctor": "ವೈದ್ಯರು",
    "dashboard.at": "ಸಮಯ:",
    "dashboard.upcoming": "ಮುಂಬರುವ",
    "dashboard.metabolicFasting": "ಸಿರ್ಕಾಡಿಯನ್ ಮೆಟಾಬಾಲಿಕ್ ಉಪವಾಸ",
    "dashboard.autophagy": "ಆಟೋಫ್ಯಾಜಿ & ಜೀವಕೋಶ ಪುನರುಜ್ಜೀವನ",
    "dashboard.logToday": "ಇಂದು ದಾಖಲಿಸಿ",
    "dashboard.continueHeader": "ಹಿಂದಿನದನ್ನು ಮುಂದುವರಿಸಿ",
    "chatbot.completed": "ಪೂರ್ಣಗೊಂಡಿದೆ",
    "chatbot.speaking": "ಮಾತನಾಡುತ್ತಿದೆ",
    "gia.optBreast": "ಸ್ತನ ಕ್ಯಾನ್ಸರ್",
    "gia.optOvarian": "ಅಂಡಾಶಯದ ಕ್ಯಾನ್ಸರ್",
    "gia.optColorectal": "ಕೊಲೊರೆಕ್ಟಲ್ ಕ್ಯಾನ್ಸರ್",
    "gia.optEndometrial": "ಎಂಡೊಮೆಟ್ರಿಯಲ್ ಕ್ಯಾನ್ಸರ್",
    "gia.optPancreatic": "ಮೇದೋಜ್ಜೀರಕ ಗ್ರಂಥಿಯ ಕ್ಯಾನ್ಸರ್",
    "gia.optProstate": "ಪ್ರಾಸ್ಟೇಟ್ ಕ್ಯಾನ್ಸರ್",
    "common.refresh": "ಡೇಟಾವನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ",
    "rateOrder": "ಉತ್ಪನ್ನಗಳನ್ನು ರೇಟ್ ಮಾಡಿ",
    "openDailyCheckinChatbot": "AI ದೈನಂದಿನ ತಪಾಸಣೆ ಸಹಾಯಕರನ್ನು ತೆರೆಯಿರಿ",
    "appBackButton": "ಹಿಂದಕ್ಕೆ",
    "common.logged": "ದಾಖಲಿಸಲಾಗಿದೆ",
    "common.minutes": "ನಿಮಿಷಗಳು",
    "Yes": "ಹೌದು",
    "No": "ಇಲ್ಲ",
    "Skip": "ಬಿಟ್ಟುಬಿಡಿ",
    "yes": "ಹೌದು",
    "no": "ಇಲ್ಲ",
    "Stress": "ಒತ್ತಡ ನಿರ್ವಹಣೆ",
    "Sleep": "ನಿದ್ರೆ & ಚೇತರಿಕೆ",
    "Smoking": "ಧೂಮಪಾನ ತ್ಯಾಗ",
    "Alcohol": "ಮದ್ಯಪಾನ ನಿಯಂತ್ರಣ",
    "Substances": "ಮಾದಕ ವಸ್ತುಗಳ ಇಳಿಕೆ",
    "Environmental": "ಪರಿಸರ ಸುರಕ್ಷತೆ",
    "Kitchen": "ಅಡುಗೆಮನೆ ನಿರ್ವಿಷೀಕರಣ",
    "Obesity": "ತೂಕ & ಚಯಾಪಚಯ",
    "Dental": "ದಂತ & ಮೌಖಿಕ ಆರೈಕೆ",
    "Gastritis": "ಗ್ಯಾಸ್ಟ್ರೈಟಿಸ್ & ಜಠರದ ಆರೋಗ್ಯ",
    "Genetic": "ಆನುವಂಶಿಕ ಕ್ಯಾನ್ಸರ್ ಅಪಾಯ",
    "Fasting": "ಮಧ್ಯಂತರ ಉಪವಾಸ",
    "Movement": "ದೈಹಿಕ ಚಲನೆ",
    "Stillness": "ಶಾಂತತೆ & ಧ್ಯಾನ",
    "Breath": "ಉಸಿರಾಟದ ವ್ಯಾಯಾಮ",
    "Joy": "ಸಂತೋಷ & ಮಾನಸಿಕ ಕ್ಷೇಮ",
    "Antioxidants": "ಆಂಟಿಆಕ್ಸಿಡೆಂಟ್ ಪೋಷಣೆ",
    "SaferProducts": "ವಿಷಮುಕ್ತ ಉತ್ಪನ್ನಗಳು",
    "CancerScreening": "ಕ್ಯಾನ್ಸರ್ ತಪಾಸಣೆ",
    "IndianCancers": "ಪ್ರಾದೇಶಿಕ ಕ್ಯಾನ್ಸರ್ ವಿಶ್ಲೇಷಣೆ"
  },
  hi: {
    "dashboard.apptWith": "चिकित्सक अपॉइंटमेंट:",
    "dashboard.doctor": "डॉक्टर",
    "dashboard.at": "समय:",
    "dashboard.upcoming": "आगामी",
    "dashboard.metabolicFasting": "सर्केडियन मेटाबॉलिक उपवास",
    "dashboard.autophagy": "ऑटोफैगी & सेलुलर नवीनीकरण",
    "dashboard.logToday": "आज दर्ज करें",
    "dashboard.continueHeader": "जहाँ छोड़ा था वहीं से जारी रखें",
    "chatbot.completed": "पूर्ण",
    "chatbot.speaking": "बोल रहा है",
    "gia.optBreast": "स्तन कैंसर",
    "gia.optOvarian": "अंडाशय का कैंसर",
    "gia.optColorectal": "कोलोरेक्टल कैंसर",
    "gia.optEndometrial": "एंडोमेट्रियल कैंसर",
    "gia.optPancreatic": "अग्नाशय का कैंसर",
    "gia.optProstate": "प्रोस्टेट कैंसर",
    "common.refresh": "डेटा रीफ़್ರೆश करें",
    "rateOrder": "उत्पादों को रेट करें",
    "openDailyCheckinChatbot": "AI दैनिक चेक-इन सहायक खोलें",
    "appBackButton": "वापस",
    "common.logged": "दर्ज किया गया",
    "common.minutes": "मिनट",
    "Yes": "हाँ",
    "No": "नहीं",
    "Skip": "छोड़ें",
    "yes": "हाँ",
    "no": "नहीं",
    "Stress": "तनाव प्रबंधन",
    "Sleep": "नींद & रिकवरी",
    "Smoking": "धूम्रपान छोड़ना",
    "Alcohol": "शराब नियंत्रण",
    "Substances": "पदार्थों में कमी",
    "Environmental": "पर्यावरण सुरक्षा",
    "Kitchen": "रसोई डिटॉक्स",
    "Obesity": "वजन & चयापचय",
    "Dental": "दंत & मौखिक देखभाल",
    "Gastritis": "गैस्ट्राइटिस & आंत का स्वास्थ्य",
    "Genetic": "आनुवंशिक कैंसर जोखिम",
    "Fasting": "आंतरायिक उपवास",
    "Movement": "शारीरिक गतिविधि",
    "Stillness": "शांति & ध्यान",
    "Breath": "श्वास अभ्यास",
    "Joy": "खुशी & मानसिक कल्याण",
    "Antioxidants": "एंटीऑक्सीडेंट पोषण",
    "SaferProducts": "टॉक्सिन-मुक्त उत्पाद",
    "CancerScreening": "कैंसर स्क्रीनिंग",
    "IndianCancers": "क्षेत्रीय कैंसर विश्लेषण"
  }
};

function insertKeysIntoFile(filePath, keysObj) {
  let content = fs.readFileSync(filePath, 'utf8');
  const lastBraceIdx = content.lastIndexOf('} as const;');
  if (lastBraceIdx === -1) {
    console.error(`Could not find closing brace in ${filePath}`);
    return;
  }

  let injection = '\n  // --- REMAINING FINAL BATCH ---\n';
  for (const [k, v] of Object.entries(keysObj)) {
    const escapedVal = JSON.stringify(v);
    injection += `  ${JSON.stringify(k)}: ${escapedVal},\n`;
  }

  const before = content.slice(0, lastBraceIdx);
  const after = content.slice(lastBraceIdx);
  fs.writeFileSync(filePath, before + injection + after, 'utf8');
  console.log(`Updated ${filePath} with ${Object.keys(keysObj).length} keys.`);
}

insertKeysIntoFile(enPath, remainingBatch.en);
insertKeysIntoFile(taPath, remainingBatch.ta);
insertKeysIntoFile(knPath, remainingBatch.kn);
insertKeysIntoFile(hiPath, remainingBatch.hi);
