const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '../src/i18n/locales/en.ts');
const taPath = path.join(__dirname, '../src/i18n/locales/ta.ts');
const knPath = path.join(__dirname, '../src/i18n/locales/kn.ts');
const hiPath = path.join(__dirname, '../src/i18n/locales/hi.ts');

const translations = {
  en: {
    "gia.optMultipleCancers": "Multiple cancers",
    "gia.optUnder35": "Under 35 years",
    "gia.opt35to45": "35–45 years",
    "gia.opt46to50": "46–50 years",
    "gia.opt51to60": "51–60 years",
    "gia.optOver60": "Over 60 years",
    "gia.optMotherSister": "Mother / Sister",
    "gia.optFatherBrother": "Father / Brother",
    "gia.optMaternalAunt": "Maternal aunt / grandmother",
    "gia.optPaternalRelative": "Paternal relative",
    "gia.optMultipleRelatives": "Multiple relatives on same side",
    "gia.optAshkenazi": "Ashkenazi Jewish ancestry",
    "gia.optSouthAsian": "South Asian / Indian",
    "gia.optFamilyTestedPositive": "Yes, family member tested positive",
    "gia.optNoPriorTesting": "No prior testing in family",
    "gia.optTellMeBrca": "Tell me more about BRCA",
    "gia.optWhatIsLynch": "What is Lynch Syndrome?",
    "gia.optBookCounseling": "Book Genetic Counseling",
    "gia.qCancerTypes": "Thank you. Understanding cancer types across generations is crucial for guideline evaluations.\n\nWhich specific type(s) of cancer were diagnosed in yourself or your family members?",
    "gia.qAge": "Thank you. Age at diagnosis is one of the strongest indicators of hereditary risk under NCCN guidelines (e.g. Breast cancer diagnosed ≤50, Colorectal ≤50, or Ovarian at any age).\n\nAt what age was the cancer first diagnosed?",
    "gia.qRelatives": "Got it. Next, which specific family relatives were affected, and on which side of the family (maternal or paternal)? Prompt: Think broadly across first, second, and third-degree relatives.",
    "gia.qAncestry": "Understood. Are there any known genetic test results in the family (e.g. BRCA1/2 mutation positive), or Ashkenazi Jewish ancestry?",
    "gia.assessmentSummary": "### 🧬 NCCN v2.2025 Oncogenetic Risk Assessment\n\nBased on the history shared, **germline hereditary cancer testing is RECOMMENDED** under current NCCN & ASCO guidelines.\n\n**Candidate Syndromes & Gene Panels to Evaluate:**\n- **HBOC Panel (BRCA1, BRCA2, PALB2, ATM, CHEK2)**: Indicated for early-onset breast, ovarian, pancreatic, or high-risk prostate cancer.\n- **Lynch Syndrome Panel (MLH1, MSH2, MSH6, PMS2, EPCAM)**: Indicated for early colorectal, endometrial, or gastric clusters.\n\n**Next Steps:**\n1. Consult a certified Genetic Counselor for a comprehensive 3-generation pedigree review.\n2. Order a clinical multi-gene panel blood/saliva test as determined by your counselor.",
    "closeChatAria": "Close Chat",
    "gia.assessmentNextStepsDesc": "A genetic counselor will review your full pedigree, order the precise multi-gene panel, and interpret findings for your family's prevention plan.",
    "coaching.title": "AI Health Coach",
    "common.typeMessage": "Type response...",
    "updating": "Updating...",
    "common.submitting": "Submitting...",
    "editReview": "Edit Review",
    "navigation.notifications": "Notifications",
    "common.noData": "No data available",
    "common.skip": "Skip",
    "getStarted": "Get Started",
    "useGpsLocation": "Use GPS Location",
    "checkButton": "Check Now",
    "whatsNew.cancerCare.title": "Active Cancer Care Support Mode",
    "whatsNew.cancerCare.desc": "Specialized protocols for chemotherapy tolerance, organ protection, and secondary recurrence defense.",
    "whatsNew.breath.title": "Vagus Nerve Stimulating Breathwork",
    "whatsNew.breath.desc": "Interactive animated timer with Box breathing, 4-7-8 relaxing breath, and Coherent resonance.",
    "whatsNew.environmental.title": "Environmental Carcinogen & Cookware Hub",
    "whatsNew.environmental.desc": "Comprehensive audit for PM2.5 air toxins, water contaminants, microplastics, and teflon cookware.",
    "whatsNew.shop.title": "Curated Wellness Products & Safe Living Store",
    "whatsNew.shop.desc": "HEPA air purifiers, water filtration devices, toxin-free kitchenware, and targeted antioxidants.",
    "whatsNew.version": "Version",
    "whatsNew.updates": "Updates",
    "whatsNew.title": "What’s New in",
    "common.explore": "Explore",
    "whatsNew.footer": "Check back anytime from your profile settings",
    "specialty.geriatrician": "Geriatrician / Preventive Physician",
    "doctor.geriatricianDesc": "Schedule annual health span assessments, bone density DEXA scans, and metabolic blood panels with your physician.",
    "habits.days": "days",
    "coaching.medicalDisclaimer": "Personalized coaching based on your meal spikes",
    "coaching.aiCoachActive": "No Active Coaching",
    "common.saving": "Saving...",
    "saveActivity": "Save Activity",
    "snapPictureMacros": "Snap a picture of your food to auto-estimate calories & macros!",
    "habits.kitchen": "Kitchen Habits",
    "fasting.medicalDisclaimerTitle": "Medical Disclaimer",
    "fasting.medicalDisclaimerDesc": "Intermittent fasting during cancer treatment is experimental. Please consult an expert and intimate your treating medical team.",
    "nav.logout": "Log Out",
    "reportReadyCollection": "Your test report has been finalized and is ready for download.",
    "common.price": "Price",
    "reportsIn": "Reports in",
    "homeCollectionAvailable": "Home Collection Available",
    "prepNote": "Preparation Note",
    "selectCenter": "Select this Center",
    "pdfReportAvailable": "PDF Report Available",
    "pdfReportReadyDesc": "Your detailed diagnostic results are ready. Download or view them externally.",
    "openPdfDocument": "Open PDF Document",
    "doYouConsume": "Do you consume",
    "orTakeSupplements": "or take antioxidant supplements",
    "toSupportRepair": "to support your body's repair mechanisms",
    "notToday": "Not today",
    "sevenDayTrend": "7-Day Trend",
    "noDaysLogged": "No days logged yet. Start your streak today!",
    "cancerScreen.tagline": "Mito Reboot · Cancer Screening",
    "cancerScreen.title": "Screening Guide by Age & Risk Group",
    "cancerScreen.bannerNotice": "General guidance for adults in India. This isn't personalised medical advice — actual intervals should be set with a treating doctor based on individual and family history.",
    "cancerScreen.highRiskNoteDesc": "— yearly, from age 60 — is suggested in addition to the standard screening above for individuals with a known genetic predisposition (e.g. BRCA1/2, Lynch syndrome) or a strong family history of cancer, or anyone otherwise assessed as high-risk. This should be discussed with a genetic counsellor or oncologist rather than done as a routine test for the general population.",
    "cancerScreen.ruleOfThumb": "Rule of thumb: if any symptom below lasts more than 3 weeks, consult a doctor — don't wait it out.",
    "cancerScreen.saving": "Saving...",
    "cancerScreen.clinicalNoteHide": "Hide clinical note ▲",
    "cancerScreen.clinicalNoteShow": "Clinical note ▼",
    "cancerScreen.bookAppointmentTest": "Book Appointment Test",
    "dental.damageBreadcrumb": "Damage · Dental",
    "dental.oralHealthDesc": "Poor dental health, sharp teeth, and tobacco staining are linked to chronic inflammation and increased risk of oral cancers.",
    "dental.sharpToothConsultDesc": "A sharp tooth can cause chronic irritation which might lead to complications over time. Please consult a dentist.",
    "dental.tobaccoConsultDesc": "Tobacco staining requires professional cleaning and evaluation to prevent further damage.",
    "dental.disclaimerText": "This tool gives an informal, photo-based approximation for personal tracking only, is not a validated diagnostic device, and does not replace a professional dental examination.",
    "dental.dentureConsultDesc": "An ill-fitting denture can cause chronic mucosal irritation, ulcers, or other long-term oral health issues. Please consult a dentist.",
    "environmental.risk": "Risk",
    "environmental.damageBreadcrumb": "Damage · Environment",
    "environmental.environment": "Environment",
    "environmental.airPollution": "Air Pollution",
    "underweight": "Underweight",
    "optimalBmi": "Optimal Weight",
    "overweight": "Overweight",
    "obese": "Obese"
  },
  ta: {
    "gia.optMultipleCancers": "பல புற்றுநோய்கள்",
    "gia.optUnder35": "35 வயதிற்கு கீழ்",
    "gia.opt35to45": "35–45 வயது",
    "gia.opt46to50": "46–50 வயது",
    "gia.opt51to60": "51–60 வயது",
    "gia.optOver60": "60 வயதிற்கு மேல்",
    "gia.optMotherSister": "தாய் / சகோதரி",
    "gia.optFatherBrother": "தந்தை / சகோதரன்",
    "gia.optMaternalAunt": "தாய்வழி அத்தை / பாட்டி",
    "gia.optPaternalRelative": "தந்தைவழி உறவினர்",
    "gia.optMultipleRelatives": "ஒரே பக்கத்தில் பல உறவினர்கள்",
    "gia.optAshkenazi": "அஷ்கெனாசி யூத வம்சாவளி",
    "gia.optSouthAsian": "தெற்காசிய / இந்தியர்",
    "gia.optFamilyTestedPositive": "ஆம், குடும்ப உறுப்பினருக்கு உறுதி செய்யப்பட்டது",
    "gia.optNoPriorTesting": "குடும்பத்தில் முன் பரிசோதனை இல்லை",
    "gia.optTellMeBrca": "BRCA பற்றி மேலும் கூறுங்கள்",
    "gia.optWhatIsLynch": "லிஞ்ச் நோய்க்குறி என்றால் என்ன?",
    "gia.optBookCounseling": "மரபணு ஆலோசனையை முன்பதிவு செய்",
    "gia.qCancerTypes": "நன்றி. தலைமுறைகளுக்கிடையேயான புற்றுநோய் வகைகளைப் புரிந்துகொள்வது வழிகாட்டுதல் மதிப்பீடுகளுக்கு முக்கியமானது.\n\nஉங்களுக்கோ அல்லது உங்கள் குடும்பத்தினருக்கோ எந்த வகையான புற்றுநோய் கண்டறியப்பட்டது?",
    "gia.qAge": "நன்றி. கண்டறியப்பட்ட வயது மரபணு ஆபத்தின் மிக முக்கியமான குறிகாட்டியாகும்.\n\nபுற்றுநோய் முதன்முதலில் எந்த வயதில் கண்டறியப்பட்டது?",
    "gia.qRelatives": "புரிந்தது. அடுத்து, எந்த குறிப்பிட்ட உறவினர்கள் பாதிக்கப்பட்டனர், மற்றும் குடும்பத்தின் எந்தப் பக்கத்தில் (தாய்வழி அல்லது தந்தைவழி)?",
    "gia.qAncestry": "புரிந்தது. குடும்பத்தில் ஏதேனும் மரபணு சோதனை முடிவுகள் உள்ளதா (எ.கா. BRCA1/2 பாசிட்டிவ்)?",
    "gia.assessmentSummary": "### 🧬 NCCN v2.2025 புற்றுநோய் மரபணு ஆபத்து மதிப்பீடு\n\nபகிர்ந்த வரலாற்றின் அடிப்படையில், தற்போதைய NCCN வழிகாட்டுதல்களின்படி **மரபணு புற்றுநோய் பரிசோதனை பரிந்துரைக்கப்படுகிறது**.\n\n**பரிசீலிக்க வேண்டிய மரபணு பேனல்கள்:**\n- **HBOC பேனல் (BRCA1, BRCA2, PALB2, ATM, CHEK2)**\n- **லிஞ்ச் நோய்க்குறி பேனல் (MLH1, MSH2, MSH6, PMS2, EPCAM)**\n\n**அடுத்த படிகள்:**\n1. சான்றளிக்கப்பட்ட மரபணு ஆலோசகரை அணுகவும்.\n2. பல மரபணு பேனல் ரத்தப் பரிசோதனை செய்யவும்.",
    "closeChatAria": "அரட்டையை மூடு",
    "gia.assessmentNextStepsDesc": "மரபணு ஆலோசகர் உங்கள் குடும்ப வரலாற்றை ஆய்வு செய்து, துல்லியமான மரபணு பரிசோதனையை பரிந்துரைப்பார்.",
    "coaching.title": "AI ஆரோக்கிய பயிற்சியாளர்",
    "common.typeMessage": "பதிலைத் தட்டச்சு செய்க...",
    "updating": "புதுப்பிக்கப்படுகிறது...",
    "common.submitting": "சமர்ப்பிக்கப்படுகிறது...",
    "editReview": "மதிப்புரையைத் திருத்து",
    "navigation.notifications": "அறிவிப்புகள்",
    "common.noData": "தரவு எதுவும் இல்லை",
    "common.skip": "தவிர்",
    "getStarted": "தொடங்குங்கள்",
    "useGpsLocation": "GPS இருப்பிடத்தைப் பயன்படுத்து",
    "checkButton": "இப்போதே சரிபார்க்கவும்",
    "whatsNew.cancerCare.title": "செயலில் உள்ள புற்றுநோய் சிகிச்சை ஆதரவு முறை",
    "whatsNew.cancerCare.desc": "கீமோதெரபி சகிப்புத்தன்மை, உறுப்பு பாதுகாப்பு மற்றும் மீண்டும் வராமல் தடுப்பதற்கான சிறப்பு நெறிமுறைகள்.",
    "whatsNew.breath.title": "வாகஸ் நரம்பு தூண்டுதல் சுவாசப் பயிற்சி",
    "whatsNew.breath.desc": "பாக்ஸ் பிரீத்திங், 4-7-8 அமைதி சுவாசம் மற்றும் ஒத்திசைவு அதிர்வு நேரக்கணிப்பான்.",
    "whatsNew.environmental.title": "சுற்றுச்சூழல் புற்றுநோய் காரணிகள் & பாத்திரங்கள் மையம்",
    "whatsNew.environmental.desc": "PM2.5 காற்று நச்சுகள், நீர் மாசுபாடுகள், மைக்ரோபிளாஸ்டிக்ஸ் மற்றும் டெஃப்ளான் பாத்திரங்களுக்கான விரிவான தணிக்கை.",
    "whatsNew.shop.title": "தேர்ந்தெடுக்கப்பட்ட ஆரோக்கிய பொருட்கள் & பாதுகாப்பான அங்காடி",
    "whatsNew.shop.desc": "HEPA காற்று சுத்திகரிப்பாளர்கள், நீர் வடிகட்டிகள், நச்சு இல்லாத பாத்திரங்கள் மற்றும் ஆன்டிஆக்ஸிடன்ட்கள்.",
    "whatsNew.version": "பதிப்பு",
    "whatsNew.updates": "புதுப்பிப்புகள்",
    "whatsNew.title": "புதிய அம்சங்கள் -",
    "common.explore": "ஆராயுங்கள்",
    "whatsNew.footer": "உங்கள் சுயவிவர அமைப்புகளில் இருந்து எப்போது வேண்டுமானாலும் பார்க்கலாம்",
    "specialty.geriatrician": "முதியோர் நல மருத்துவர் / தடுப்பு மருத்துவர்",
    "doctor.geriatricianDesc": "வருடாந்திர ஆயுட்கால மதிப்பீடுகள், எலும்பு அடர்த்தி DEXA ஸ்கேன்கள் மற்றும் இரத்தப் பரிசோதனைகளை திட்டமிடுங்கள்.",
    "habits.days": "நாட்கள்",
    "coaching.medicalDisclaimer": "உங்கள் உணவு சர்க்கரை அளவுகளின் அடிப்படையிலான தனிப்பயனாக்கப்பட்ட பயிற்சி",
    "coaching.aiCoachActive": "செயலில் உள்ள பயிற்சி எதுவும் இல்லை",
    "common.saving": "சேமிக்கப்படுகிறது...",
    "saveActivity": "செயல்பாட்டைச் சேமி",
    "snapPictureMacros": "கலோரிகள் & ஊட்டச்சத்துக்களைக் கணக்கிட உங்கள் உணவை படம் எடுக்கவும்!",
    "habits.kitchen": "சமையலறை பழக்கங்கள்",
    "fasting.medicalDisclaimerTitle": "மருத்துவ மறுப்பு",
    "fasting.medicalDisclaimerDesc": "புற்றுநோய் சிகிச்சையின் போது இடைப்பட்ட விரதம் சோதனைக்குரியது. தயவுசெய்து உங்கள் மருத்துவரிடம் கலந்தாலோசிக்கவும்.",
    "nav.logout": "வெளியேறு",
    "reportReadyCollection": "உங்கள் பரிசோதனை அறிக்கை தயாராக உள்ளது மற்றும் பதிவிறக்கம் செய்யலாம்.",
    "common.price": "விலை",
    "reportsIn": "அறிக்கை கிடைக்கும் நேரம்",
    "homeCollectionAvailable": "வீட்டு மாதிரி சேகரிப்பு உள்ளது",
    "prepNote": "தயாரிப்பு குறிப்பு",
    "selectCenter": "இந்த மையத்தைத் தேர்ந்தெடுக்கவும்",
    "pdfReportAvailable": "PDF அறிக்கை உள்ளது",
    "pdfReportReadyDesc": "உங்கள் விரிவான முடிவுகள் தயாராக உள்ளன. அவற்றை பதிவிறக்கம் செய்து பார்க்கவும்.",
    "openPdfDocument": "PDF ஆவணத்தைத் திறக்கவும்",
    "doYouConsume": "நீங்கள் உட்கொள்கிறீர்களா",
    "orTakeSupplements": "அல்லது ஆன்டிஆக்ஸிடன்ட் சப்ளிமெண்ட்ஸ் எடுக்கிறீர்களா",
    "toSupportRepair": "உங்கள் உடலின் பழுதுபார்க்கும் வழிமுறைகளை ஆதரிக்க",
    "notToday": "இன்று இல்லை",
    "sevenDayTrend": "7 நாள் போக்கு",
    "noDaysLogged": "நாட்கள் எதுவும் பதிவு செய்யப்படவில்லை. இன்றே தொடங்குங்கள்!",
    "cancerScreen.tagline": "Mito Reboot · புற்றுநோய் பரிசோதனை",
    "cancerScreen.title": "வயது & ஆபத்து குழுவின் அடிப்படையிலான பரிசோதனை வழிகாட்டி",
    "cancerScreen.bannerNotice": "இந்தியாவில் உள்ள பெரியவர்களுக்கான பொதுவான வழிகாட்டுதல். இது தனிப்பட்ட மருத்துவ ஆலோசனை அல்ல.",
    "cancerScreen.highRiskNoteDesc": "மரபணு ஆபத்து உள்ளவர்களுக்கு 60 வயதிலிருந்து வருடாந்திர பரிசோதனை பரிந்துரைக்கப்படுகிறது. புற்றுநோய் நிபுணருடன் கலந்தாலோசிக்கவும்.",
    "cancerScreen.ruleOfThumb": "விதி: ஏதேனும் அறிகுறி 3 வாரங்களுக்கு மேல் நீடித்தால், உடனே மருத்துவரை அணுகவும்.",
    "cancerScreen.saving": "சேமிக்கப்படுகிறது...",
    "cancerScreen.clinicalNoteHide": "மருத்துவக் குறிப்பை மறை ▲",
    "cancerScreen.clinicalNoteShow": "மருத்துவக் குறிப்பைக் காட்டு ▼",
    "cancerScreen.bookAppointmentTest": "பரிசோதனை முன்பதிவு செய்",
    "dental.damageBreadcrumb": "சேதம் · பல் பராமரிப்பு",
    "dental.oralHealthDesc": "மோசமான பல் சுகாதாரம், கூர்மையான பற்கள் மற்றும் புகையிலை கறைகள் வாய்வழி புற்றுநோய் அபாயத்தை அதிகரிக்கின்றன.",
    "dental.sharpToothConsultDesc": "கூர்மையான பல் நீண்டகால எரிச்சலை ஏற்படுத்தக்கூடும். பல் மருத்துவரை அணுகவும்.",
    "dental.tobaccoConsultDesc": "புகையிலை கறைகளுக்கு தொழில்முறை சுத்தம் மற்றும் சிகிச்சை தேவை.",
    "dental.disclaimerText": "இந்தக் கருவி தனிப்பட்ட கண்காணிப்புக்கானது மட்டுமே, தொழில்முறை மருத்துவ பரிசோதனைக்கு மாற்றாகாது.",
    "dental.dentureConsultDesc": "பொருந்தாத செயற்கைப்பல் புண்களை ஏற்படுத்தக்கூடும். பல் மருத்துவரை அணுகவும்.",
    "environmental.risk": "ஆபத்து",
    "environmental.damageBreadcrumb": "சேதம் · சுற்றுச்சூழல்",
    "environmental.environment": "சுற்றுச்சூழல்",
    "environmental.airPollution": "காற்று மாசுபாடு",
    "underweight": "குறைந்த எடை",
    "optimalBmi": "சரியான எடை",
    "overweight": "அதிக எடை",
    "obese": "உடல் பருமன்"
  },
  kn: {
    "gia.optMultipleCancers": "ಬಹು ಕ್ಯಾನ್ಸರ್‌ಗಳು",
    "gia.optUnder35": "35 ವರ್ಷಕ್ಕಿಂತ ಕಡಿಮೆ",
    "gia.opt35to45": "35–45 ವರ್ಷಗಳು",
    "gia.opt46to50": "46–50 ವರ್ಷಗಳು",
    "gia.opt51to60": "51–60 ವರ್ಷಗಳು",
    "gia.optOver60": "60 ವರ್ಷ ಮೇಲ್ಪಟ್ಟವರು",
    "gia.optMotherSister": "ತಾಯಿ / ಸಹೋದರಿ",
    "gia.optFatherBrother": "ತಂದೆ / ಸಹೋದರ",
    "gia.optMaternalAunt": "ತಾಯಿಯ ಕಡೆಯ ಅತ್ತೆ / ಅಜ್ಜಿ",
    "gia.optPaternalRelative": "ತಂದೆಯ ಕಡೆಯ ಸಂಬಂಧಿ",
    "gia.optMultipleRelatives": "ಒಂದೇ ಕಡೆಯ ಬಹು ಸಂಬಂಧಿಕರು",
    "gia.optAshkenazi": "ಅಶ್ಕೆನಾಜಿ ಯಹೂದಿ ವಂಶಾವಳಿ",
    "gia.optSouthAsian": "ದಕ್ಷಿಣ ಏಷ್ಯಾ / ಭಾರತೀಯ",
    "gia.optFamilyTestedPositive": "ಹೌದು, ಕುಟುಂಬದ ಸದಸ್ಯರಿಗೆ ದೃಢಪಟ್ಟಿದೆ",
    "gia.optNoPriorTesting": "ಕುಟುಂಬದಲ್ಲಿ ಯಾವುದೇ ಹಿಂದಿನ ಪರೀಕ್ಷೆಯಿಲ್ಲ",
    "gia.optTellMeBrca": "BRCA ಬಗ್ಗೆ ಇನ್ನಷ್ಟು ತಿಳಿಸಿ",
    "gia.optWhatIsLynch": "ಲಿಂಚ್ ಸಿಂಡ್ರೋಮ್ ಎಂದರೇನು?",
    "gia.optBookCounseling": "ಆನುವಂಶಿಕ ಸಮಾಲೋಚನೆ ಕಾಯ್ದಿರಿಸಿ",
    "gia.qCancerTypes": "ಧನ್ಯವಾದಗಳು. ತಲೆಮಾರುಗಳಾದ್ಯಂತ ಕ್ಯಾನ್ಸರ್ ವಿಧಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದು ಬಹಳ ಮುಖ್ಯ.\n\nನಿಮಗೆ ಅಥವಾ ನಿಮ್ಮ ಕುಟುಂಬಕ್ಕೆ ಯಾವ ರೀತಿಯ ಕ್ಯಾನ್ಸರ್ ಇರುವುದು ಕಂಡುಬಂದಿದೆ?",
    "gia.qAge": "ಧನ್ಯವಾದಗಳು. ರೋಗನಿರ್ಣಯದ ವಯಸ್ಸು ಆನುವಂಶಿಕ ಅಪಾಯದ ಪ್ರಮುಖ ಸೂಚಕವಾಗಿದೆ.\n\nಕ್ಯಾನ್ಸರ್ ಮೊದಲ ಬಾರಿಗೆ ಯಾವ ವಯಸ್ಸಿನಲ್ಲಿ ಪತ್ತೆಯಾಯಿತು?",
    "gia.qRelatives": "ಅರ್ಥವಾಯಿತು. ಯಾವ ನಿರ್ದಿಷ್ಟ ಸಂಬಂಧಿಕರು ಪ್ರಭಾವಿತರಾಗಿದ್ದಾರೆ ಮತ್ತು ಕುಟುಂಬದ ಯಾವ ಕಡೆಯಿಂದ?",
    "gia.qAncestry": "ತಿಳಿಯಿತು. ಕುಟುಂಬದಲ್ಲಿ ಯಾವುದೇ ಆನುವಂಶಿಕ ಪರೀಕ್ಷಾ ಫಲಿತಾಂಶಗಳಿವೆಯೇ (ಉದಾ: BRCA1/2 ಪಾಸಿಟಿವ್)?",
    "gia.assessmentSummary": "### 🧬 NCCN v2.2025 ಆಂಕೊಜೆನೆಟಿಕ್ ಅಪಾಯದ ಮೌಲ್ಯಮಾಪನ\n\nಹಂಚಿಕೊಂಡ ಇತಿಹಾಸದ ಆಧಾರದ ಮೇಲೆ, **ಆನುವಂಶಿಕ ಕ್ಯಾನ್ಸರ್ ಪರೀಕ್ಷೆಯನ್ನು ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ**.\n\n**ಮೌಲ್ಯಮಾಪನ ಮಾಡಬೇಕಾದ ಪ್ಯಾನೆಲ್‌ಗಳು:**\n- **HBOC ಪ್ಯಾನೆಲ್ (BRCA1, BRCA2, PALB2, ATM, CHEK2)**\n- **ಲಿಂಚ್ ಸಿಂಡ್ರೋಮ್ ಪ್ಯಾನೆಲ್ (MLH1, MSH2, MSH6, PMS2, EPCAM)**\n\n**ಮುಂದಿನ ಹಂತಗಳು:**\n1. ಪ್ರಮಾಣೀಕೃತ ಆನುವಂಶಿಕ ಸಲಹೆಗಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ.\n2. ಬಹು-ಜೀನ್ ಪ್ಯಾನೆಲ್ ರಕ್ತ ಪರೀಕ್ಷೆಯನ್ನು ಮಾಡಿಸಿ.",
    "closeChatAria": "ಚಾಟ್ ಮುಚ್ಚಿ",
    "gia.assessmentNextStepsDesc": "ಆನುವಂಶಿಕ ಸಲಹೆಗಾರರು ನಿಮ್ಮ ವಂಶಾವಳಿಯನ್ನು ಪರಿಶೀಲಿಸಿ ಸೂಕ್ತ ಪರೀಕ್ಷೆಗಳನ್ನು ಶಿಫಾರಸು ಮಾಡುತ್ತಾರೆ.",
    "coaching.title": "AI ಆರೋಗ್ಯ ತರಬೇತುದಾರ",
    "common.typeMessage": "ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ...",
    "updating": "ನವೀಕರಿಸಲಾಗುತ್ತಿದೆ...",
    "common.submitting": "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
    "editReview": "ವಿಮರ್ಶೆಯನ್ನು ಸಂಪಾದಿಸಿ",
    "navigation.notifications": "ಅಧಿಸೂಚನೆಗಳು",
    "common.noData": "ಯಾವುದೇ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ",
    "common.skip": "ಬಿಟ್ಟುಬಿಡಿ",
    "getStarted": "ಪ್ರಾರಂಭಿಸಿ",
    "useGpsLocation": "GPS ಸ್ಥಳ ಬಳಸಿ",
    "checkButton": "ಈಗಲೇ ಪರಿಶೀಲಿಸಿ",
    "whatsNew.cancerCare.title": "ಸಕ್ರಿಯ ಕ್ಯಾನ್ಸರ್ ಆರೈಕೆ ಬೆಂಬಲ ಮೋಡ್",
    "whatsNew.cancerCare.desc": "ಕೀಮೋಥೆರಪಿ ಸಹಿಷ್ಣುತೆ ಮತ್ತು ಅಂಗಗಳ ರಕ್ಷಣೆಗಾಗಿ ವಿಶೇಷ ಪ್ರೋಟೋಕಾಲ್‌ಗಳು.",
    "whatsNew.breath.title": "ವಾಗಸ್ ನರ ಉತ್ತೇಜಿಸುವ ಉಸಿರಾಟದ ವ್ಯಾಯಾಮ",
    "whatsNew.breath.desc": "ಬಾಕ್ಸ್ ಬ್ರೀತಿಂಗ್, 4-7-8 ವಿಶ್ರಾಂತಿ ಉಸಿರಾಟ ಮತ್ತು ಅನುರಣನ ಟೈಮರ್.",
    "whatsNew.environmental.title": "ಪರಿಸರ ಕಾರ್ಸಿನೋಜೆನ್ & ಪಾತ್ರೆಗಳ ಕೇಂದ್ರ",
    "whatsNew.environmental.desc": "PM2.5 ವಾಯು ವಿಷಗಳು, ನೀರಿನ ಕಲ್ಮಶಗಳು ಮತ್ತು ಮೈಕ್ರೋಪ್ಲಾಸ್ಟಿಕ್‌ಗಳ ಲೆಕ್ಕಪರಿಶೋಧನೆ.",
    "whatsNew.shop.title": "ಆರೋಗ್ಯಕರ ಉತ್ಪನ್ನಗಳು & ಸುರಕ್ಷಿತ ಅಂಗಡಿ",
    "whatsNew.shop.desc": "HEPA ಏರ್ ಪ್ಯೂರಿಫೈಯರ್‌ಗಳು, ನೀರಿನ ಫಿಲ್ಟರ್‌ಗಳು ಮತ್ತು ವಿಷಮುಕ್ತ ಪಾತ್ರೆಗಳು.",
    "whatsNew.version": "ಆವೃತ್ತಿ",
    "whatsNew.updates": "ನವೀಕರಣಗಳು",
    "whatsNew.title": "ಹೊಸ ವೈಶಿಷ್ಟ್ಯಗಳು -",
    "common.explore": "ಅನ್ವೇಷಿಸಿ",
    "whatsNew.footer": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಿಂದ ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ಪರಿಶೀಲಿಸಿ",
    "specialty.geriatrician": "ಜೆರಿಯಾಟ್ರಿಶಿಯನ್ / ತಡೆಗಟ್ಟುವ ವೈದ್ಯರು",
    "doctor.geriatricianDesc": "ವಾರ್ಷಿಕ ಆರೋಗ್ಯ ಮೌಲ್ಯಮಾಪನಗಳು ಮತ್ತು ಮೂಳೆ ಸಾಂದ್ರತೆಯ ಸ್ಕ್ಯಾನ್‌ಗಳನ್ನು ನಿಗದಿಪಡಿಸಿ.",
    "habits.days": "ದಿನಗಳು",
    "coaching.medicalDisclaimer": "ನಿಮ್ಮ ಊಟದ ಸಕ್ಕರೆ ಮಟ್ಟವನ್ನು ಆಧರಿಸಿದ ವೈಯಕ್ತಿಕ ತರಬೇತಿ",
    "coaching.aiCoachActive": "ಯಾವುದೇ ಸಕ್ರಿಯ ತರಬೇತಿ ಇಲ್ಲ",
    "common.saving": "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    "saveActivity": "ಚಟುವಟಿಕೆಯನ್ನು ಉಳಿಸಿ",
    "snapPictureMacros": "ಕ್ಯಾಲೋರಿಗಳನ್ನು ಅಂದಾಜು ಮಾಡಲು ನಿಮ್ಮ ಊಟದ ಚಿತ್ರವನ್ನು ತೆಗೆಯಿರಿ!",
    "habits.kitchen": "ಅಡುಗೆಮನೆಯ ಅಭ್ಯಾಸಗಳು",
    "fasting.medicalDisclaimerTitle": "ವೈದ್ಯಕೀಯ ಹಕ್ಕುತ್ಯಾಗ",
    "fasting.medicalDisclaimerDesc": "ಕ್ಯಾನ್ಸರ್ ಚಿಕಿತ್ಸೆಯ ಸಮಯದಲ್ಲಿ ಮಧ್ಯಂತರ ಉಪವಾಸವು ಪ್ರಾಯೋಗಿಕವಾಗಿದೆ. ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "nav.logout": "ಲಾಗ್ ಔಟ್",
    "reportReadyCollection": "ನಿಮ್ಮ ಪರೀಕ್ಷಾ ವರದಿ ಸಿದ್ಧವಾಗಿದೆ ಮತ್ತು ಡೌನ್‌ಲೋಡ್ ಮಾಡಬಹುದು.",
    "common.price": "ಬೆಲೆ",
    "reportsIn": "ವರದಿ ಬರುವ ಸಮಯ",
    "homeCollectionAvailable": "ಮನೆ ಮಾದರಿ ಸಂಗ್ರಹಣೆ ಲಭ್ಯವಿದೆ",
    "prepNote": "ಸಿದ್ಧತೆ ಟಿಪ್ಪಣಿ",
    "selectCenter": "ಈ ಕೇಂದ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "pdfReportAvailable": "PDF ವರದಿ ಲಭ್ಯವಿದೆ",
    "pdfReportReadyDesc": "ನಿಮ್ಮ ವಿವರವಾದ ಫಲಿತಾಂಶಗಳು ಸಿದ್ಧವಾಗಿವೆ. ಅವುಗಳನ್ನು ವೀಕ್ಷಿಸಿ.",
    "openPdfDocument": "PDF ಡಾಕ್ಯುಮೆಂಟ್ ತೆರೆಯಿರಿ",
    "doYouConsume": "ನೀವು ಸೇವಿಸುತ್ತೀರಾ",
    "orTakeSupplements": "ಅಥವಾ ಆಂಟಿಆಕ್ಸಿಡೆಂಟ್ ಪೂರಕಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತೀರಾ",
    "toSupportRepair": "ದೇಹದ ದುರಸ್ತಿ ಕಾರ್ಯವಿಧಾನಗಳನ್ನು ಬೆಂಬಲಿಸಲು",
    "notToday": "ಇಂದು ಇಲ್ಲ",
    "sevenDayTrend": "7 ದಿನಗಳ ಪ್ರವೃತ್ತಿ",
    "noDaysLogged": "ಇನ್ನೂ ಯಾವುದೇ ದಿನಗಳನ್ನು ದಾಖಲಿಸಿಲ್ಲ. ಇಂದೇ ಪ್ರಾರಂಭಿಸಿ!",
    "cancerScreen.tagline": "Mito Reboot · ಕ್ಯಾನ್ಸರ್ ಸ್ಕ್ರೀನಿಂಗ್",
    "cancerScreen.title": "ವಯಸ್ಸು & ಅಪಾಯದ ಗುಂಪಿನ ಆಧಾರದ ಸ್ಕ್ರೀನಿಂಗ್ ಮಾರ್ಗದರ್ಶಿ",
    "cancerScreen.bannerNotice": "ಭಾರತದ ವಯಸ್ಕರಿಗೆ ಸಾಮಾನ್ಯ ಮಾರ್ಗದರ್ಶನ. ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "cancerScreen.highRiskNoteDesc": "ಆನುವಂಶಿಕ ಅಪಾಯ ಹೊಂದಿರುವ ವ್ಯಕ್ತಿಗಳಿಗೆ 60 ನೇ ವಯಸ್ಸಿನಿಂದ ವಾರ್ಷಿಕ ಪರೀಕ್ಷೆಗಳನ್ನು ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ.",
    "cancerScreen.ruleOfThumb": "ಯಾವುದೇ ರೋಗಲಕ್ಷಣ 3 ವಾರಗಳಿಗಿಂತ ಹೆಚ್ಚು ಕಾಲ ಮುಂದುವರಿದರೆ ತಕ್ಷಣ ವೈದ್ಯರನ್ನು ಭೇಟಿ ಮಾಡಿ.",
    "cancerScreen.saving": "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
    "cancerScreen.clinicalNoteHide": "ವೈದ್ಯಕೀಯ ಟಿಪ್ಪಣಿ ಮರೆಮಾಡಿ ▲",
    "cancerScreen.clinicalNoteShow": "ವೈದ್ಯಕೀಯ ಟಿಪ್ಪಣಿ ತೋರಿಸಿ ▼",
    "cancerScreen.bookAppointmentTest": "ಪರೀಕ್ಷೆಯನ್ನು ಕಾಯ್ದಿರಿಸಿ",
    "dental.damageBreadcrumb": "ಹಾನಿ · ದಂತ ಆರೈಕೆ",
    "dental.oralHealthDesc": "ಕಳಪೆ ದಂತ ಆರೋಗ್ಯ ಮತ್ತು ತಂಬಾಕು ಕಲೆಗಳು ಮೌಖಿಕ ಕ್ಯಾನ್ಸರ್ ಅಪಾಯವನ್ನು ಹೆಚ್ಚಿಸುತ್ತವೆ.",
    "dental.sharpToothConsultDesc": "ತೀಕ್ಷ್ಣವಾದ ಹಲ್ಲು ಕಿರಿಕಿರಿಯನ್ನು ಉಂಟುಮಾಡಬಹುದು. ದಂತವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "dental.tobaccoConsultDesc": "ತಂಬಾಕು ಕಲೆಗಳಿಗೆ ವೃತ್ತಿಪರ ಶುಚಿಗೊಳಿಸುವಿಕೆ ಅಗತ್ಯವಿದೆ.",
    "dental.disclaimerText": "ಈ ಉಪಕರಣವು ವೈಯಕ್ತಿಕ ಟ್ರ್ಯಾಕಿಂಗ್‌ಗಾಗಿ ಮಾತ್ರ.",
    "dental.dentureConsultDesc": "ಸರಿಯಾಗಿ ಹೊಂದಿಕೆಯಾಗದ ದಂತಪಂಕ್ತಿಗಳು ಹುಣ್ಣುಗಳಿಗೆ ಕಾರಣವಾಗಬಹುದು.",
    "environmental.risk": "ಅಪಾಯ",
    "environmental.damageBreadcrumb": "ಹಾನಿ · ಪರಿಸರ",
    "environmental.environment": "ಪರಿಸರ",
    "environmental.airPollution": "ವಾಯು ಮಾಲಿನ್ಯ",
    "underweight": "ಕಡಿಮೆ ತೂಕ",
    "optimalBmi": "ಸೂಕ್ತ ತೂಕ",
    "overweight": "ಅಧಿಕ ತೂಕ",
    "obese": "ಸ್ಥೂಲಕಾಯ"
  },
  hi: {
    "gia.optMultipleCancers": "कई प्रकार के कैंसर",
    "gia.optUnder35": "35 वर्ष से कम",
    "gia.opt35to45": "35–45 वर्ष",
    "gia.opt46to50": "46–50 वर्ष",
    "gia.opt51to60": "51–60 वर्ष",
    "gia.optOver60": "60 वर्ष से अधिक",
    "gia.optMotherSister": "माता / बहन",
    "gia.optFatherBrother": "पिता / भाई",
    "gia.optMaternalAunt": "मातृ पक्ष की मौसी / नानी",
    "gia.optPaternalRelative": "पितृ पक्ष के रिश्तेदार",
    "gia.optMultipleRelatives": "एक ही पक्ष के कई रिश्तेदार",
    "gia.optAshkenazi": "अशकेनाज़ी यहूदी वंश",
    "gia.optSouthAsian": "दक्षिण एशियाई / भारतीय",
    "gia.optFamilyTestedPositive": "हाँ, परिवार के सदस्य की रिपोर्ट पॉजिटिव आई थी",
    "gia.optNoPriorTesting": "परिवार में पहले कोई परीक्षण नहीं हुआ",
    "gia.optTellMeBrca": "BRCA के बारे में अधिक बताएं",
    "gia.optWhatIsLynch": "लिंच सिंड्रोम क्या है?",
    "gia.optBookCounseling": "जेनेटिक काउंसलिंग बुक करें",
    "gia.qCancerTypes": "धन्यवाद। पीढ़ियों के कैंसर के प्रकार को समझना दिशानिर्देश मूल्यांकन के लिए महत्वपूर्ण है।\n\nआपको या आपके परिवार में किस प्रकार का कैंसर पाया गया था?",
    "gia.qAge": "धन्यवाद। निदान की उम्र आनुवंशिक जोखिम का सबसे मजबूत संकेतक है।\n\nकैंसर का पहली बार किस उम्र में पता चला था?",
    "gia.qRelatives": "समझ गया। आगे, कौन से विशिष्ट रिश्तेदार प्रभावित हुए और परिवार के किस पक्ष से?",
    "gia.qAncestry": "समझा। क्या परिवार में कोई ज्ञात आनुवंशिक परीक्षण परिणाम हैं (जैसे BRCA1/2 पॉजिटिव)?",
    "gia.assessmentSummary": "### 🧬 NCCN v2.2025 ऑन्कोजेनेटिक जोखिम मूल्यांकन\n\nसाझा किए गए इतिहास के आधार पर, **आनुवंशिक कैंसर परीक्षण की सिफारिश की जाती है**।\n\n**जांच के लिए उपयुक्त पैनल:**\n- **HBOC पैनल (BRCA1, BRCA2, PALB2, ATM, CHEK2)**\n- **लिंच सिंड्रोम पैनल (MLH1, MSH2, MSH6, PMS2, EPCAM)**\n\n**अगले कदम:**\n1. प्रमाणित जेनेटिक काउंसलर से परामर्श लें।\n2. मल्टी-जीन पैनल ब्लड टेस्ट करवाएं।",
    "closeChatAria": "चैट बंद करें",
    "gia.assessmentNextStepsDesc": "जेनेटिक काउंसलर आपके पारिवारिक इतिहास की समीक्षा करेंगे और सटीक परीक्षण की सिफारिश करेंगे।",
    "coaching.title": "एआई स्वास्थ्य कोच",
    "common.typeMessage": "जवाब टाइप करें...",
    "updating": "अपडेट हो रहा है...",
    "common.submitting": "जमा किया जा रहा है...",
    "editReview": "समीक्षा संपादित करें",
    "navigation.notifications": "सूचनाएं",
    "common.noData": "कोई डेटा उपलब्ध नहीं है",
    "common.skip": "छोड़ें",
    "getStarted": "शुरू करें",
    "useGpsLocation": "जीपीएस स्थान का उपयोग करें",
    "checkButton": "अभी जांचें",
    "whatsNew.cancerCare.title": "सक्रिय कैंसर देखभाल सहायता मोड",
    "whatsNew.cancerCare.desc": "कीमोथेरेपी सहनशीलता और अंगों की सुरक्षा के लिए विशेष प्रोटोकॉल।",
    "whatsNew.breath.title": "वेगस तंत्रिका उत्तेजक श्वास अभ्यास",
    "whatsNew.breath.desc": "बॉक्स ब्रीदिंग, 4-7-8 रिलैक्सिंग ब्रीद और रेजोनेंस टाइमर।",
    "whatsNew.environmental.title": "पर्यावरणीय कार्सिनोजेन & कुकवेयर हब",
    "whatsNew.environmental.desc": "PM2.5 वायु विषाक्त पदार्थों, जल दूषकों और टेफ्लॉन कुकवेयर का व्यापक ऑडिट।",
    "whatsNew.shop.title": "क्यूरेटेड वेलनेस उत्पाद & सुरक्षित स्टोर",
    "whatsNew.shop.desc": "HEPA एयर प्यूरीफायर, वाटर फिल्टर, गैर-विषैले बर्तन और एंटीऑक्सीडेंट।",
    "whatsNew.version": "संस्करण",
    "whatsNew.updates": "अपडेट",
    "whatsNew.title": "नया क्या है -",
    "common.explore": "अन्वेषण करें",
    "whatsNew.footer": "अपनी प्रोफ़ाइल सेटिंग्स से कभी भी देखें",
    "specialty.geriatrician": "जेरियाट्रीशियन / निवारक चिकित्सक",
    "doctor.geriatricianDesc": "वार्षिक स्वास्थ्य मूल्यांकन और अस्थि घनत्व DEXA स्कैन निर्धारित करें।",
    "habits.days": "दिन",
    "coaching.medicalDisclaimer": "आपके भोजन ग्लूकोज स्तर पर आधारित व्यक्तिगत कोचिंग",
    "coaching.aiCoachActive": "कोई सक्रिय कोचिंग नहीं",
    "common.saving": "सहेजा जा रहा है...",
    "saveActivity": "गतिविधि सहेजें",
    "snapPictureMacros": "कैलोरी का अनुमान लगाने के लिए अपने भोजन की तस्वीर लें!",
    "habits.kitchen": "रसोई की आदतें",
    "fasting.medicalDisclaimerTitle": "चिकित्सा अस्वीकरण",
    "fasting.medicalDisclaimerDesc": "कैंसर उपचार के दौरान आंतरायिक उपवास प्रायोगिक है। डॉक्टर से परामर्श लें।",
    "nav.logout": "लॉग आउट",
    "reportReadyCollection": "आपकी परीक्षण रिपोर्ट तैयार है और डाउनलोड की जा सकती है।",
    "common.price": "मूल्य",
    "reportsIn": "रिपोर्ट मिलने का समय",
    "homeCollectionAvailable": "होम कलेक्शन उपलब्ध है",
    "prepNote": "तैयारी नोट",
    "selectCenter": "इस केंद्र का चयन करें",
    "pdfReportAvailable": "PDF रिपोर्ट उपलब्ध",
    "pdfReportReadyDesc": "आपके विस्तृत परिणाम तैयार हैं। उन्हें डाउनलोड करें।",
    "openPdfDocument": "PDF दस्तावेज़ खोलें",
    "doYouConsume": "क्या आप उपभोग करते हैं",
    "orTakeSupplements": "या एंटीऑक्सीडेंट सप्लीमेंट्स लेते हैं",
    "toSupportRepair": "शरीर की मरम्मत में सहायता के लिए",
    "notToday": "आज नहीं",
    "sevenDayTrend": "7-दिवसीय रुझान",
    "noDaysLogged": "अभी तक कोई दिन दर्ज नहीं हुआ। आज ही शुरू करें!",
    "cancerScreen.tagline": "Mito Reboot · कैंसर स्क्रीनिंग",
    "cancerScreen.title": "आयु और जोखिम समूह के अनुसार स्क्रीनिंग गाइड",
    "cancerScreen.bannerNotice": "भारत के वयस्कों के लिए सामान्य मार्गदर्शन। डॉक्टर से परामर्श लें।",
    "cancerScreen.highRiskNoteDesc": "आनुवंशिक जोखिम वाले लोगों के लिए 60 वर्ष की आयु से वार्षिक परीक्षण की सिफारिश की जाती है।",
    "cancerScreen.ruleOfThumb": "नियम: यदि कोई लक्षण 3 सप्ताह से अधिक बना रहता है, तो तुरंत डॉक्टर से परामर्श लें।",
    "cancerScreen.saving": "सहेजा जा रहा है...",
    "cancerScreen.clinicalNoteHide": "क्लिनिकल नोट छिपाएं ▲",
    "cancerScreen.clinicalNoteShow": "क्लिनिकल नोट दिखाएं ▼",
    "cancerScreen.bookAppointmentTest": "परीक्षण बुक करें",
    "dental.damageBreadcrumb": "हानि · दंत चिकित्सा",
    "dental.oralHealthDesc": "खराब दंत स्वास्थ्य और तंबाकू के दाग मौखिक कैंसर के जोखिम को बढ़ाते हैं।",
    "dental.sharpToothConsultDesc": "तेज दांत लगातार जलन पैदा कर सकता है। दंत चिकित्सक से परामर्श लें।",
    "dental.tobaccoConsultDesc": "तंबाकू के दाग के लिए पेशेवर सफाई की आवश्यकता होती है।",
    "dental.disclaimerText": "यह उपकरण केवल व्यक्तिगत ट्रैकिंग के लिए है।",
    "dental.dentureConsultDesc": "अनुचित बत्तीसी छालों का कारण बन सकती है। दंत चिकित्सक से परामर्श लें।",
    "environmental.risk": "जोखिम",
    "environmental.damageBreadcrumb": "हानि · पर्यावरण",
    "environmental.environment": "पर्यावरण",
    "environmental.airPollution": "वायु प्रदूषण",
    "underweight": "कम वजन",
    "optimalBmi": "उचित वजन",
    "overweight": "अधिक वजन",
    "obese": "मोटापा"
  }
};

function insertKeysIntoFile(filePath, keysObj) {
  let content = fs.readFileSync(filePath, 'utf8');
  const lastBraceIdx = content.lastIndexOf('} as const;');
  if (lastBraceIdx === -1) {
    console.error(`Could not find closing brace in ${filePath}`);
    return;
  }

  let injection = '\n  // --- FINAL 165 LOCALIZATION BATCH ---\n';
  for (const [k, v] of Object.entries(keysObj)) {
    const escapedVal = JSON.stringify(v);
    injection += `  ${JSON.stringify(k)}: ${escapedVal},\n`;
  }

  const before = content.slice(0, lastBraceIdx);
  const after = content.slice(lastBraceIdx);
  fs.writeFileSync(filePath, before + injection + after, 'utf8');
  console.log(`Updated ${filePath} with ${Object.keys(keysObj).length} keys.`);
}

insertKeysIntoFile(enPath, translations.en);
insertKeysIntoFile(taPath, translations.ta);
insertKeysIntoFile(knPath, translations.kn);
insertKeysIntoFile(hiPath, translations.hi);
