import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import ShopProduct from './models/ShopProduct';
import { ShopCategory } from './models/ShopCategory';

dotenv.config({ path: path.join(__dirname, '../.env') });

export const SHOP_CATEGORIES = [
  { name: 'Pesticide free food', description: 'Certified pesticide-free farm produce, raw nuts, and organic superfoods.' },
  { name: 'Arivu in nutrition', description: 'Doctor-formulated diabetic health mixes, sprouted grain flours, and low-GI foods.' },
  { name: 'Environment safe products', description: 'Medical-grade air monitors, HEPA purifiers, alkaline filters, and non-toxic daily care.' },
  { name: 'Safe kitchen', description: 'Non-toxic, chemical-free cookware: pre-seasoned cast iron tawas, skillets, and glass/steel storage.' },
  { name: 'Glucose monitoring', description: 'Continuous glucose monitoring sensors, ketone meters, and blood analyte tracking kits.' },
  { name: 'Cancer support wig', description: 'Ultra-soft, breathable medical head coverings designed for oncology and hair loss support.' },
  { name: 'Antioxidants', description: 'High-potency cellular antioxidants, pure turmeric curcumin, and evidence-based longevity literature.' }
];

export const AFFILIATE_PRODUCTS = [
  // ── CATEGORY 1: Pesticide free food ──
  {
    name: 'Vinnie Premium Walnut Inshell Natural (500g)',
    description: '100% natural, pesticide-free Kashmiri inshell walnuts packed with essential Omega-3 fatty acids, plant sterols, and polyphenols to support brain function and metabolic stability.',
    shortDescription: 'Pesticide-free inshell walnuts rich in Omega-3 and brain-supporting nutrients.',
    category: 'Pesticide free food',
    brand: 'Vinnie',
    price: 499,
    regularPrice: 599,
    offerPrice: 499,
    discountPercent: 17,
    image: 'https://m.media-amazon.com/images/I/81KBQ4jrO7L.jpg',
    images: ['https://m.media-amazon.com/images/I/81KBQ4jrO7L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Vinnie-Premium-Walnut-Inshell-Natural/dp/B09R4DGRH9?tag=mitoreboot-21&linkCode=ll2',
    stock: 100,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Cold-shelled for maximum nutrient density', 'High plant-based Omega-3 ALA content', 'Free of pesticides and chemical preservatives']
  },
  {
    name: 'Fresh Farm Amla - Indian Gooseberry (250g)',
    description: 'Farm-fresh, chemical-free Indian Gooseberry (Amla) harvested directly from organic orchards. High natural Vitamin C and bioflavonoids for glycemic control and cellular defense.',
    shortDescription: 'Farm-fresh Vitamin C powerhouse for antioxidant defense and immunity.',
    category: 'Pesticide free food',
    brand: 'Fresh Farm',
    price: 65,
    regularPrice: 80,
    offerPrice: 65,
    discountPercent: 19,
    image: 'https://m.media-amazon.com/images/I/31Ip4aURUpL.png',
    images: ['https://m.media-amazon.com/images/I/31Ip4aURUpL.png'],
    buyOnAmazonUrl: 'https://www.amazon.in/Fresh-Amla-250g/dp/B07BG7D7SC?tag=mitoreboot-21&linkCode=ll2',
    stock: 100,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Raw whole food Vitamin C', 'Assists in insulin sensitivity and digestion', 'Direct farm harvest with zero post-harvest chemicals']
  },
  {
    name: 'Fresh Organic Ooty Carrots (500g)',
    description: 'Naturally sweetened organic Ooty mountain carrots, grown in nutrient-dense soil without artificial pesticides. Loaded with beta-carotene, lutein, and prebiotic soluble fiber.',
    shortDescription: 'Organic highland carrots rich in beta-carotene and dietary fiber.',
    category: 'Pesticide free food',
    brand: 'Fresh Organic',
    price: 89,
    regularPrice: 110,
    offerPrice: 89,
    discountPercent: 19,
    image: 'https://m.media-amazon.com/images/I/41RgULA8t0L.jpg',
    images: ['https://m.media-amazon.com/images/I/41RgULA8t0L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Fresh-Organic-Carrot-Ooty-500g/dp/B0B53W9WJX?tag=mitoreboot-21&linkCode=ll2',
    stock: 100,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Rich in Provitamin A & Lutein', 'Supports eye, skin, and mucosal membrane health', 'Zero pesticide residues from pristine hill cultivation']
  },

  // ── CATEGORY 3: Environment safe products ──
  {
    name: 'Prana Air Pocket Real-Time PM2.5 Air Quality Monitor',
    description: 'Compact portable laser particle sensor for immediate PM2.5 monitoring and air purifier efficiency testing. Measures indoor and outdoor airborne particulate levels with high-precision optical sensors and app sync.',
    shortDescription: 'Portable real-time PM2.5 laser air purifier companion & AQI monitor.',
    category: 'Environment safe products',
    brand: 'Prana Air',
    price: 4990,
    regularPrice: 5990,
    offerPrice: 4990,
    discountPercent: 17,
    image: 'https://m.media-amazon.com/images/I/41k46nyhQJL.jpg',
    images: ['https://m.media-amazon.com/images/I/41k46nyhQJL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Prana-Air-Portable-Real-Time-Connectivity/dp/B0GVK35WXS?tag=mitoreboot-21&linkCode=ll2',
    stock: 50,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Laser PM2.5 optical particulate counter', 'Air purifier filtration efficiency testing', 'Real-time air pollution alerts']
  },
  {
    name: 'Eureka Forbes 360° Particulate Air Purifier with True HEPA',
    description: 'Surround 360-degree filtration system engineered to capture 99.97% of fine airborne allergens, micro-dust, pet dander, and PM2.5 pollutants for clean lung respiration.',
    shortDescription: 'True HEPA 360-degree high-efficiency air purifier for home and clinic.',
    category: 'Environment safe products',
    brand: 'Eureka Forbes',
    price: 6499,
    regularPrice: 9999,
    offerPrice: 6499,
    discountPercent: 35,
    image: 'https://m.media-amazon.com/images/I/61nNG5witoL.jpg',
    images: ['https://m.media-amazon.com/images/I/61nNG5witoL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Eureka-Forbes-Technology-Particulate-Purification/dp/B0CMJ6T9JB?tag=mitoreboot-21&linkCode=ll2',
    stock: 35,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['True HEPA particulate capture', '360-degree air intake flow', 'Whisper-quiet night mode for deep sleep']
  },
  {
    name: 'Philips GoPure 3601 High-Efficiency Car Air Purifier',
    description: 'Compact automotive air filtration eliminating toxic exhaust fumes, VOCs, fine road particulate matter (PM2.5), and airborne allergens during commuting.',
    shortDescription: 'In-car high-performance air purifier for toxic road fumes & PM2.5.',
    category: 'Environment safe products',
    brand: 'Philips',
    price: 4499,
    regularPrice: 5999,
    offerPrice: 4499,
    discountPercent: 25,
    image: 'https://m.media-amazon.com/images/I/61OQAQ7TkuL.jpg',
    images: ['https://m.media-amazon.com/images/I/61OQAQ7TkuL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Philips-3601-Car-Air-Purifier/dp/B0CRRWXQC4?tag=mitoreboot-21&linkCode=ll2',
    stock: 40,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Removes traffic exhaust & volatile compounds', 'Rapid cabin air exchange rate', 'Auto-power with car ignition']
  },
  {
    name: 'KENT Supreme Alkaline RO Water Purifier',
    description: 'State-of-the-art dual filtration RO + UV + UF + Alkaline water purifier with activated carbon defense. Removes heavy metals, microplastics, and pesticide runoff while maintaining optimal alkaline pH (8.0-8.5).',
    shortDescription: 'Multi-stage RO + UV water purifier with dual filtration and alkaline pH balance.',
    category: 'Environment safe products',
    brand: 'KENT',
    price: 15499,
    regularPrice: 20000,
    offerPrice: 15499,
    discountPercent: 22,
    image: 'https://m.media-amazon.com/images/I/61UUbUkDGRL.jpg',
    images: ['https://m.media-amazon.com/images/I/61UUbUkDGRL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/KENT-Supreme-Alkaline-Purification-Black/dp/B0CB8KG44H?tag=mitoreboot-21&linkCode=ll2',
    stock: 25,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Dual filtration activated carbon defense', 'Retains essential minerals with TDS controller', 'Alkaline pH enhancement for reduced body acidity']
  },
  {
    name: 'Atovio Anti-Pollution N95 & N99 Respirator Mask with Replaceable Filters',
    description: 'Certified N95 and N99 particulate respirator face mask with dual exhale valves and replaceable active carbon filter inserts. Blocks fine particulate matter (PM2.5), dust, smog, and airborne pathogens.',
    shortDescription: 'Certified N95 / N99 reusable anti-pollution face mask with carbon filters.',
    category: 'Environment safe products',
    brand: 'Atovio',
    price: 799,
    regularPrice: 1299,
    offerPrice: 799,
    discountPercent: 38,
    image: 'https://m.media-amazon.com/images/I/717KndjwFYL.jpg',
    images: ['https://m.media-amazon.com/images/I/717KndjwFYL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/atovio-Anti-Pollution-Filtration-Respirator-Replaceable/dp/B0G2YNB443?tag=mitoreboot-21&linkCode=ll2',
    stock: 80,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Certified N95 and N99 particulate barrier protection', '6-layer activated carbon PM2.5 filters', 'Comfortable skin-friendly washable fabric with breathable air valve']
  },
  {
    name: 'Oral-B CrossAction Battery-Powered Electric Toothbrush',
    description: 'Clinically proven rotating cross-action oscillating brush head. Removes significantly more plaque and oral biofilm than manual brushing without abrasive enamel erosion.',
    shortDescription: 'CrossAction oscillating electric brush for optimal oral microbiome.',
    category: 'Environment safe products',
    brand: 'Oral-B',
    price: 549,
    regularPrice: 799,
    offerPrice: 549,
    discountPercent: 31,
    image: 'https://m.media-amazon.com/images/I/413HAuxlHPL.jpg',
    images: ['https://m.media-amazon.com/images/I/413HAuxlHPL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Oral-Crossaction-Battery-Powered-Toothbrush/dp/B018IE1XSM?tag=mitoreboot-21&linkCode=ll2',
    stock: 90,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Rotational micro-pulse plaque breakdown', 'Gentle on gums and enamel', 'Battery operated convenience']
  },
  {
    name: 'Natural Neem Herbal Bristle Eco Toothbrush',
    description: 'Sustainably sourced bamboo handle with natural antimicrobial neem-infused bristles. Plastic-free, biodegradable, and gentle on sensitive oral tissues.',
    shortDescription: 'Biodegradable bamboo toothbrush with antimicrobial neem bristles.',
    category: 'Environment safe products',
    brand: 'EcoHealth',
    price: 199,
    regularPrice: 299,
    offerPrice: 199,
    discountPercent: 33,
    image: 'https://m.media-amazon.com/images/I/413HAuxlHPL.jpg',
    images: ['https://m.media-amazon.com/images/I/413HAuxlHPL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Oral-Crossaction-Battery-Powered-Toothbrush/dp/B018IE1XSM?tag=mitoreboot-21&linkCode=ll2',
    stock: 120,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['100% plastic-free compostable handle', 'Natural antibacterial neem properties', 'BPA-free bristles']
  },
  {
    name: 'Sensodyne Expert White Daily Whitening Toothpaste (140g)',
    description: 'Enamel-safe desensitizing formulation designed for gentle stain removal while soothing hyper-sensitive nerve endings. SLS-free, low-abrasion protection.',
    shortDescription: 'Dentist-recommended sensitive whitening and mineral defense.',
    category: 'Environment safe products',
    brand: 'Sensodyne',
    price: 240,
    regularPrice: 280,
    offerPrice: 240,
    discountPercent: 14,
    image: 'https://m.media-amazon.com/images/I/51JSOPM8qRL.jpg',
    images: ['https://m.media-amazon.com/images/I/51JSOPM8qRL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Sensodyne-Expert-White-Toothpaste-140GM/dp/B0GYZ7WH1F?tag=mitoreboot-21&linkCode=ll2',
    stock: 100,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Potassium nitrate sensitivity shield', 'Low RDA abrasive score', 'Long-lasting oral freshness']
  },
  {
    name: 'Cureveda Sparkle Ayurvedic Oil Pulling (Virgin Coconut & Mint)',
    description: 'Traditional Ayurvedic Gandusha formula with cold-pressed virgin coconut oil, eucalyptus, clove, and mint. Promotes oral detoxification, reduces harmful bacteria, and freshens breath naturally.',
    shortDescription: 'Ayurvedic virgin coconut oil pulling rinse for natural oral detox.',
    category: 'Environment safe products',
    brand: 'Cureveda',
    price: 499,
    regularPrice: 595,
    offerPrice: 499,
    discountPercent: 16,
    image: 'https://m.media-amazon.com/images/I/51YuQGAWwWL.jpg',
    images: ['https://m.media-amazon.com/images/I/51YuQGAWwWL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Cureveda-Sparkle-Immunity-essential-Whitening/dp/B08C5HKS1R?tag=mitoreboot-21&linkCode=ll2',
    stock: 75,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Cold pressed virgin coconut base', 'Enriched with clove and peppermint oils', 'Reduces oral microbial burden naturally']
  },

  // ── CATEGORY 4: Safe kitchen ──
  {
    name: 'CUMIN & CO Induction-Ready Pre-Seasoned Cast Iron Dosa Tava',
    description: 'Pure 100% chemical-free cast iron tawa seasoned with cold-pressed gingelly oil. Naturally non-stick, delivers bioavailable dietary iron with every meal, and free of PTFE/PFOA coatings.',
    shortDescription: 'Chemical-free pre-seasoned cast iron tava for healthy everyday cooking.',
    category: 'Safe kitchen',
    brand: 'CUMIN & CO',
    price: 1199,
    regularPrice: 1799,
    offerPrice: 1199,
    discountPercent: 33,
    image: 'https://m.media-amazon.com/images/I/41KG0qflglL.jpg',
    images: ['https://m.media-amazon.com/images/I/41KG0qflglL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/CUMIN-CO-Induction-Accessories-Seasoning/dp/B0FZX1FGFS?tag=mitoreboot-21&linkCode=ll2',
    stock: 60,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Zero toxic Teflon, PFAS, or lead coatings', 'Naturally adds dietary iron to foods', 'Induction and gas stove compatible']
  },
  {
    name: 'The Indus Valley Pure Cast Iron Tawa & Cookware Set',
    description: 'Handcrafted artisan cast iron cookware set with heavy heat retention. Naturally enriched with food-grade plant oils for non-toxic cooking without carcinogenic chemical residues.',
    shortDescription: 'Handcrafted pure cast iron cookware set, 100% toxin-free.',
    category: 'Safe kitchen',
    brand: 'The Indus Valley',
    price: 1899,
    regularPrice: 2800,
    offerPrice: 1899,
    discountPercent: 32,
    image: 'https://m.media-amazon.com/images/I/61Z3CcoB0oL.jpg',
    images: ['https://m.media-amazon.com/images/I/61Z3CcoB0oL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Indus-Valley-Cast-Iron-Tawa/dp/B0BZJFWFN8?tag=mitoreboot-21&linkCode=ll2',
    stock: 45,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Even heat distribution prevents hot spots', 'Traditional pre-seasoning with edible oils', 'Lifelong durability with zero microplastics']
  },
  {
    name: 'Naturally Nonstick Pre-Seasoned Cast Iron Cookware Set',
    description: 'Complete multi-piece cast iron kitchen essentials including deep skillet, sauté pan, and tava. Eliminate hormone-disrupting PFAS from your household cooking completely.',
    shortDescription: 'Multi-piece pre-seasoned cast iron cookware bundle.',
    category: 'Safe kitchen',
    brand: 'IronChef',
    price: 2499,
    regularPrice: 3899,
    offerPrice: 2499,
    discountPercent: 36,
    image: 'https://m.media-amazon.com/images/I/61K4i8KRqCL.jpg',
    images: ['https://m.media-amazon.com/images/I/61K4i8KRqCL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Pre-Seasoned-Cookware-Kitchen-Naturally-Nonstick/dp/B0DN1SXXRK?tag=mitoreboot-21&linkCode=ll2',
    stock: 30,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['100% cast iron with natural flaxseed oil coat', 'Zero plastic or resin handles', 'Superior high-temperature searing capacity']
  },
  {
    name: 'OLMARTT Non-Plastic Natural Solid Wood Chopping Board',
    description: 'Eco-friendly solid wood chopping board crafted without toxic glue, formaldehyde, or microplastic release. Naturally antimicrobial, gentle on knives, and food-safe.',
    shortDescription: 'Plastic-free organic solid wood cutting board for microplastic-free prep.',
    category: 'Safe kitchen',
    brand: 'OLMARTT',
    price: 649,
    regularPrice: 999,
    offerPrice: 649,
    discountPercent: 35,
    image: 'https://m.media-amazon.com/images/I/51sUnc8zadL.jpg',
    images: ['https://m.media-amazon.com/images/I/51sUnc8zadL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/OLMARTT-KITCHENWARE-Chopping-Board-Multi-Purpose/dp/B0FF4YS9K2?tag=mitoreboot-21&linkCode=ll2',
    stock: 70,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Zero plastic shavings in food preparation', 'Naturally antibacterial hardwood surface', 'Heavy-duty non-slip thickness']
  },
  {
    name: 'MEEROK Non-Plastic Glass & Stainless Steel Oil Dispenser Set',
    description: 'Durable borosilicate glass bottles with stainless steel non-drip pourers. Protects heart-healthy cooking oils from endocrine-disrupting phthalates and plasticizer leaching.',
    shortDescription: 'Borosilicate glass & stainless steel oil dispenser duo.',
    category: 'Safe kitchen',
    brand: 'MEEROK',
    price: 499,
    regularPrice: 799,
    offerPrice: 499,
    discountPercent: 38,
    image: 'https://m.media-amazon.com/images/I/31WEpuFnNKL.jpg',
    images: ['https://m.media-amazon.com/images/I/31WEpuFnNKL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/MEEROK-Oil-dispenser-Pourer-Pack/dp/B0HC329FYK?tag=mitoreboot-21&linkCode=ll2',
    stock: 85,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Food-grade 304 stainless steel nozzles', 'Prevents oil oxidation and plastic chemical leaching', 'Precision measured pouring']
  },
  {
    name: 'NATULIX Premium Stainless Steel Kitchen Storage Containers Set',
    description: 'Heavy gauge mirror-finish 100% stainless steel storage canister set with airtight lids. Safeguards pulses, spices, grains, and dry goods without BPA or microplastics.',
    shortDescription: 'Airtight food-grade stainless steel pantry storage set.',
    category: 'Safe kitchen',
    brand: 'NATULIX',
    price: 899,
    regularPrice: 1399,
    offerPrice: 899,
    discountPercent: 36,
    image: 'https://m.media-amazon.com/images/I/81hWOKoo51L.jpg',
    images: ['https://m.media-amazon.com/images/I/81hWOKoo51L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/NATULIX-Kg-Stainless-Containers-kitchen/dp/B0CDL5G2R8?tag=mitoreboot-21&linkCode=ll2',
    stock: 55,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Zero plastic contact with dry food supplies', 'Airtight seal preserves food freshness', 'Rust-resistant heavy gauge steel']
  },

  // ── CATEGORY 5: Glucose monitoring ──
  {
    name: 'Abbott FreeStyle Libre Sensor Continuous Glucose Monitoring (CGM)',
    description: 'Factory-calibrated 14-day continuous glucose monitoring sensor. Automatically measures glucose concentrations day and night through interstitial fluid without routine fingersticks.',
    shortDescription: 'Continuous glucose sensor providing real-time 24/7 metabolic insight.',
    category: 'Glucose monitoring',
    brand: 'Abbott',
    price: 4999,
    regularPrice: 5499,
    offerPrice: 4999,
    discountPercent: 9,
    image: 'https://m.media-amazon.com/images/I/713hiv6kD1L.jpg',
    images: ['https://m.media-amazon.com/images/I/713hiv6kD1L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/FreeStyle-Libre-Sensor-Glucose-Monitoring/dp/B0849WHJQN?tag=mitoreboot-21&linkCode=ll2',
    stock: 50,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['14-day continuous automatic glucose tracking', 'Water-resistant sensor for bathing and exercise', 'Identifies nocturnal hypoglycemia and meal spikes']
  },
  {
    name: 'Abbott FreeStyle Optium Blood Ketone Test Strips (Pack of 10)',
    description: 'Individually foil-wrapped electro-chemical test strips for precise quantitative measurement of beta-hydroxybutyrate (blood ketones). Essential for therapeutic ketogenic therapy.',
    shortDescription: 'Clinical-grade blood beta-hydroxybutyrate ketone test strips.',
    category: 'Glucose monitoring',
    brand: 'Abbott',
    price: 999,
    regularPrice: 1250,
    offerPrice: 999,
    discountPercent: 20,
    image: 'https://m.media-amazon.com/images/I/61i0US9EP2L.jpg',
    images: ['https://m.media-amazon.com/images/I/61i0US9EP2L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Abbott-FreeStyle-Optimum-Ketone-Strips/dp/B08KXS4TGC?tag=mitoreboot-21&linkCode=ll2',
    stock: 65,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Accurate blood ketone measurement in 10 seconds', 'Monitors therapeutic ketosis and metabolic shift', 'Individually foil-sealed for long shelf life']
  },
  {
    name: 'FreeStyle Libre 2 Reader Glucose & Ketone Dual System',
    description: 'Advanced handheld color touchscreen reader compatible with FreeStyle Libre sensors and Optium ketone/glucose test strips. Provides visual trend arrows and customizable threshold alarms.',
    shortDescription: 'Handheld touchscreen reader with trend analysis & alarms.',
    category: 'Glucose monitoring',
    brand: 'Abbott',
    price: 5299,
    regularPrice: 5999,
    offerPrice: 5299,
    discountPercent: 12,
    image: 'https://m.media-amazon.com/images/I/61i0US9EP2L.jpg',
    images: ['https://m.media-amazon.com/images/I/61i0US9EP2L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/FreeStyle-Libre-2-Reader-Glucose-Monitoring/dp/B0H267WC5H?tag=mitoreboot-21&linkCode=ll2',
    stock: 30,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Dual testing for glucose and blood ketone levels', 'Visual ambulatory glucose profile (AGP) reports', 'Stores 90 days of glycemic history']
  },

  // ── CATEGORY 6: Cancer support wig ──
  {
    name: 'PALAY Soft Elastic Cotton Chemo Caps Turban Headwear for Cancer Hair Loss',
    description: 'Specially designed soft, breathable cotton elastic chemo headwear and cancer cap turban for sensitive scalps during oncology treatments, alopecia, and hair loss.',
    shortDescription: 'Soft elastic cotton chemo turban & cap for sensitive scalp hair loss.',
    category: 'Cancer support wig',
    brand: 'PALAY',
    price: 599,
    regularPrice: 999,
    offerPrice: 599,
    discountPercent: 40,
    image: 'https://m.media-amazon.com/images/I/41k5AtmKFnL.jpg',
    images: ['https://m.media-amazon.com/images/I/41k5AtmKFnL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/dp/B0BXSBH2BQ?tag=mitoreboot-21&linkCode=ll2',
    stock: 50,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Hypoallergenic soft breathable cotton blend', 'Pre-tied elastic design for gentle, secure fit', 'Non-irritating seam construction for sensitive scalp comfort']
  },
  {
    name: 'The Headscarves Women Silky Soft Bamboo Viscose Sleep Cap for Hair Loss Chemo Headwear',
    description: 'Ultra-soft bamboo viscose cranial sleep cap engineered specifically for medical hair loss, sensitive scalp protection, and chemo comfort.',
    shortDescription: 'Silky soft bamboo viscose chemo sleep skull cap.',
    category: 'Cancer support wig',
    brand: 'The Headscarves',
    price: 499,
    regularPrice: 799,
    offerPrice: 499,
    discountPercent: 38,
    image: 'https://m.media-amazon.com/images/I/31o8ZP686xL.jpg',
    images: ['https://m.media-amazon.com/images/I/31o8ZP686xL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/dp/B07MYZHL82?tag=mitoreboot-21&linkCode=ll2',
    stock: 45,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Natural moisture-wicking bamboo viscose', 'Seam-free inner design preventing irritation', 'Thermal regulating all-season wear']
  },

  // ── CATEGORY 7: Antioxidants ──
  {
    name: 'TATA Organic India Premium Green Tea Powder - Antioxidant Blend',
    description: 'Certified organic whole leaf green tea powder enriched with natural catechins and EGCG. Delivers high ORAC antioxidant capacity to protect cellular mitochondria from free radical stress.',
    shortDescription: 'Pure organic EGCG green tea powder with high antioxidant score.',
    category: 'Antioxidants',
    brand: 'TATA Organic India',
    price: 349,
    regularPrice: 420,
    offerPrice: 349,
    discountPercent: 17,
    image: 'https://m.media-amazon.com/images/I/61b3pxcp73L.jpg',
    images: ['https://m.media-amazon.com/images/I/61b3pxcp73L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/TATA-Product-Organic-India-Powder/dp/B0FG72Q5XM?tag=mitoreboot-21&linkCode=ll2',
    stock: 90,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['High epigallocatechin gallate (EGCG) concentration', 'Fosters mitochondrial biogenesis', '100% certified organic cultivation']
  },
  {
    name: 'Babu Curcumin Rich Pure Organic Turmeric Powder (500g)',
    description: 'Direct farm-processed indigenous Lakadong turmeric powder with certified >7% natural curcuminoid potency. Potent anti-inflammatory and cellular antioxidant action.',
    shortDescription: 'High-curcumin (>7%) Lakadong organic turmeric powder.',
    category: 'Antioxidants',
    brand: 'Babu Organic',
    price: 299,
    regularPrice: 399,
    offerPrice: 299,
    discountPercent: 25,
    image: 'https://m.media-amazon.com/images/I/61b3pxcp73L.jpg',
    images: ['https://m.media-amazon.com/images/I/61b3pxcp73L.jpg'],
    stock: 120,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Lab-tested high curcuminoid content (>7%)', 'Unadulterated single-origin cultivation', 'Enhances cellular antioxidant enzyme systems']
  },
  {
    name: 'Oncocur Curcumin & Piperine Antioxidant Herbal Capsules (60 Veg Caps)',
    description: 'Therapeutic bio-enhanced curcumin extract standardized to 95% curcuminoids complexed with black pepper piperine for 2000% increased bioavailability. Promotes healthy inflammatory modulation.',
    shortDescription: 'Standardized 95% curcuminoid capsules with piperine bioavailability enhancer.',
    category: 'Antioxidants',
    brand: 'Oncocur',
    price: 899,
    regularPrice: 1299,
    offerPrice: 899,
    discountPercent: 31,
    image: 'https://m.media-amazon.com/images/I/61b3pxcp73L.jpg',
    images: ['https://m.media-amazon.com/images/I/61b3pxcp73L.jpg'],
    stock: 80,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Standardized 95% pure curcuminoid complex', 'Piperine-enhanced systemic absorption', 'Supports cellular integrity and immune resilience']
  },
  {
    name: 'The Antioxidant Counter: Your Complete Guide to Superfoods',
    description: 'Authoritative clinical reference detailing the Oxygen Radical Absorbance Capacity (ORAC) scores of everyday foods, herbs, and supplements to slow oxidative aging.',
    shortDescription: 'Complete food ORAC guide for high-antioxidant living.',
    category: 'Antioxidants',
    brand: 'Health Books',
    price: 499,
    regularPrice: 650,
    offerPrice: 499,
    discountPercent: 23,
    image: 'https://m.media-amazon.com/images/I/51Yu8ipM2xL.jpg',
    images: ['https://m.media-amazon.com/images/I/51Yu8ipM2xL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/gp/product/1989682812?tag=mitoreboot-21&linkCode=ll2',
    stock: 40,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['ORAC value tables for over 500 ingredients', 'Practical meal pairing strategies for oxidative stress', 'Evidence-based longevity protocols']
  },
  {
    name: 'Anti-Inflammatory & Antioxidant Diet Guide for Vitality',
    description: 'Science-backed guide detailing how specific bioflavonoids, carotenoids, and polyphenols interact with cellular signaling pathways to lower systemic inflammation.',
    shortDescription: 'Practical guide to anti-inflammatory eating and polyphenol protocols.',
    category: 'Antioxidants',
    brand: 'Health Books',
    price: 599,
    regularPrice: 799,
    offerPrice: 599,
    discountPercent: 25,
    image: 'https://m.media-amazon.com/images/I/517KtSbXg8L.jpg',
    images: ['https://m.media-amazon.com/images/I/517KtSbXg8L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/gp/product/1632872323?tag=mitoreboot-21&linkCode=ll2',
    stock: 35,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Low-glycemic anti-inflammatory recipe plans', 'Gut-friendly polyphenol rich preparations', 'Elimination of inflammatory trigger foods']
  },
  {
    name: 'Natural Antioxidants in Clinical Practice & Cellular Health',
    description: 'In-depth medical text reviewing clinical trials on vitamins C, E, alpha-lipoic acid, CoQ10, and plant antioxidants in metabolic, cardiovascular, and oncological care.',
    shortDescription: 'Clinical review of molecular antioxidants and therapeutic applications.',
    category: 'Antioxidants',
    brand: 'Medical Publishing',
    price: 850,
    regularPrice: 1100,
    offerPrice: 850,
    discountPercent: 23,
    image: 'https://m.media-amazon.com/images/I/51ZcAcdJFyL.jpg',
    images: ['https://m.media-amazon.com/images/I/51ZcAcdJFyL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/gp/product/9350578883?tag=mitoreboot-21&linkCode=ll2',
    stock: 30,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Cellular pharmacology of master antioxidants', 'Dosage strategies for clinical care', 'Physician and clinician oriented insights']
  },
  {
    name: 'The Antioxidant Miracle: High-Performance Longevity',
    description: 'Bestselling guide by leading researchers breaking down the antioxidant network (Vitamins C & E, CoQ10, Lipoic Acid, and Glutathione) to protect cells from premature aging.',
    shortDescription: 'The definitive guide to the 5 key network antioxidants for longevity.',
    category: 'Antioxidants',
    brand: 'Health Books',
    price: 499,
    regularPrice: 699,
    offerPrice: 499,
    discountPercent: 29,
    image: 'https://m.media-amazon.com/images/I/11Sa2OpQXzL.png',
    images: ['https://m.media-amazon.com/images/I/11Sa2OpQXzL.png'],
    buyOnAmazonUrl: 'https://www.amazon.in/gp/product/1557043019?tag=mitoreboot-21&linkCode=ll2',
    stock: 25,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['How the five network antioxidants rejuvenate each other', 'Supplements versus whole food intake guidelines', 'Targeted protocols for energy and vitality']
  },
  {
    name: 'The Ultimate Guide to Antioxidants & DNA Protection',
    description: 'A comprehensive handbook exploring how botanical antioxidants protect nuclear DNA and mitochondrial telomeres from environmental radiation and oxidative decay.',
    shortDescription: 'DNA and telomere cellular protection via natural antioxidants.',
    category: 'Antioxidants',
    brand: 'Longevity Books',
    price: 520,
    regularPrice: 700,
    offerPrice: 520,
    discountPercent: 26,
    image: 'https://m.media-amazon.com/images/I/412CnuZG7NL.jpg',
    images: ['https://m.media-amazon.com/images/I/412CnuZG7NL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/gp/product/1578263239?tag=mitoreboot-21&linkCode=ll2',
    stock: 35,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Botanical extracts for cellular repair', 'Epigenetic diet recommendations', 'Nutraceutical synergistic combos']
  },

  // ── Women's Health & Longevity Books ──
  {
    name: 'The Menopause Brain: The New Science for Empowering Women',
    description: 'Groundbreaking neuroscientific insight by Dr. Lisa Mosconi exploring how hormonal shifts reshape the female brain during perimenopause and menopause.',
    shortDescription: 'Neuroscience and lifestyle roadmap for brain wellness during menopause.',
    category: 'Antioxidants',
    brand: 'Avery Publishing',
    price: 699,
    regularPrice: 899,
    offerPrice: 699,
    discountPercent: 22,
    image: 'https://m.media-amazon.com/images/I/412Q1McRQ1L.jpg',
    images: ['https://m.media-amazon.com/images/I/412Q1McRQ1L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Inside-Menopause-Brain-Understanding-Happens/dp/B0DKT5B8S1?tag=mitoreboot-21&linkCode=ll2',
    stock: 40,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Written by leading neuroscientist Lisa Mosconi, PhD', 'Actionable dietary and sleep protocols for hot flashes & fog', 'Optimizes cognitive reserve and metabolic transition']
  },
  {
    name: 'The Menopause Gut: Balance Microbiome to Reclaim Health',
    description: 'Explores the critical estrobolome connection — the gut bacteria that regulate estrogen metabolism — with evidence-backed dietary strategies to reduce bloating and mood fluctuations.',
    shortDescription: 'Gut microbiome balance for healthy estrogen metabolism.',
    category: 'Antioxidants',
    brand: 'Rodale Books',
    price: 649,
    regularPrice: 850,
    offerPrice: 649,
    discountPercent: 24,
    image: 'https://m.media-amazon.com/images/I/41FEp9Wm3oL.jpg',
    images: ['https://m.media-amazon.com/images/I/41FEp9Wm3oL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Menopause-Gut-Balance-Microbiome-Reclaim/dp/0593855191?tag=mitoreboot-21&linkCode=ll2',
    stock: 30,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Unlocks the estrobolome microbiome connection', 'High-fiber and prebiotic meal templates', 'Alleviates hormonal weight gain and digestive issues']
  },
  {
    name: 'Self-Help for Premenstrual Syndrome (Dr. Michelle Harrison)',
    description: 'Pioneering compassionate guide outlining practical medical and nutritional steps to overcome cyclical PMS mood changes, cramps, and energy crashes naturally.',
    shortDescription: 'Physician-authored practical guide to overcoming PMS symptoms.',
    category: 'Antioxidants',
    brand: 'Random House',
    price: 499,
    regularPrice: 650,
    offerPrice: 499,
    discountPercent: 23,
    image: 'https://m.media-amazon.com/images/I/41xiBDefxrL.jpg',
    images: ['https://m.media-amazon.com/images/I/41xiBDefxrL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Self-Help-Premenstrual-Syndrome-Michelle-Harrison/dp/0679778004?tag=mitoreboot-21&linkCode=ll2',
    stock: 35,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Proven nutritional supplementation guidelines', 'Stress and progesterone balancing techniques', 'Empowering self-advocacy tools for women']
  },
  {
    name: 'Recipes for Health: Overcoming Premenstrual Tension',
    description: 'Delicious whole-food culinary guide filled with micronutrient-rich recipes specifically formulated to stabilize blood sugar, ease prostaglandins, and balance cyclic hormones.',
    shortDescription: 'Culinary medicine recipes formulated to ease premenstrual symptoms.',
    category: 'Antioxidants',
    brand: 'HarperCollins',
    price: 399,
    regularPrice: 550,
    offerPrice: 399,
    discountPercent: 27,
    image: 'https://m.media-amazon.com/images/I/5100Y82JG2L.jpg',
    images: ['https://m.media-amazon.com/images/I/5100Y82JG2L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/Recipes-Health-Overcoming-Premenstrual-Tension/dp/0722531400?tag=mitoreboot-21&linkCode=ll2',
    stock: 45,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Magnesium and B6-rich meal combinations', 'Glycemic-friendly sweet tooth alternatives', 'Easy meal prep for high-stress cycle phases']
  },
  {
    name: 'Ayurvedic & Modern Overview of Premenstrual Syndrome',
    description: 'Integrative medical manual bridging classical Ayurvedic doshic balancing (Vata-Pitta regulation) with modern endocrinological findings for holistic reproductive wellness.',
    shortDescription: 'Integrative Ayurvedic & endocrinology perspective on PMS.',
    category: 'Antioxidants',
    brand: 'Chaukhambha',
    price: 450,
    regularPrice: 600,
    offerPrice: 450,
    discountPercent: 25,
    image: 'https://m.media-amazon.com/images/I/41SAS8UeP1L.jpg',
    images: ['https://m.media-amazon.com/images/I/41SAS8UeP1L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/AYURVEDIC-MODERN-OVERVIEW-PREMENSTRUAL-SYNDROME/dp/9355154461?tag=mitoreboot-21&linkCode=ll2',
    stock: 30,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Doshic analysis of PMS presentations', 'Traditional herbal rasayanas and formulation insights', 'Comparative modern hormone diagnostic charts']
  },

  // ── Senior Cognitive & Memory Books ──
  {
    name: 'Memory Activity Book for Seniors: Cognitive Wellness & Retention',
    description: 'Engaging, clinically structured neurobic mental exercises designed to strengthen working memory, verbal recall, and spatial reasoning in older adults.',
    shortDescription: 'Neurobic brain exercises to maintain sharp memory in seniors.',
    category: 'Antioxidants',
    brand: 'Senior Wellness',
    price: 499,
    regularPrice: 699,
    offerPrice: 499,
    discountPercent: 29,
    image: 'https://m.media-amazon.com/images/I/51iAl5o17WL.jpg',
    images: ['https://m.media-amazon.com/images/I/51iAl5o17WL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/gp/product/1648450954?tag=mitoreboot-21&linkCode=ll2',
    stock: 50,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Large print format for easy senior readability', 'Targeted neuroplasticity activation exercises', 'Builds daily cognitive stimulation habits']
  },
  {
    name: 'Brain Games & Memory Puzzles for Seniors',
    description: 'Doctor-endorsed cognitive stimulation book with over 200 logic puzzles, word associations, and pattern recognitions to defend against cognitive decline.',
    shortDescription: 'Doctor-endorsed puzzle challenges for mental agility and focus.',
    category: 'Antioxidants',
    brand: 'Brain Fitness',
    price: 449,
    regularPrice: 599,
    offerPrice: 449,
    discountPercent: 25,
    image: 'https://m.media-amazon.com/images/I/61InrePRt5L.jpg',
    images: ['https://m.media-amazon.com/images/I/61InrePRt5L.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/gp/product/B0DM1BM3PS?tag=mitoreboot-21&linkCode=ll2',
    stock: 45,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Graduated difficulty levels for continuous progress', 'Supports memory, processing speed, and focus', 'Fun, frustration-free layout']
  },
  {
    name: 'The Complete Memory Sharpener for Healthy Aging',
    description: 'Evidence-based holistic framework uniting nutritional neuroscience, physical balance routines, and targeted memory mnemonics to preserve brain vitality throughout aging.',
    shortDescription: 'Comprehensive lifestyle roadmap for cognitive longevity and healthy aging.',
    category: 'Antioxidants',
    brand: 'Healthy Aging Press',
    price: 549,
    regularPrice: 750,
    offerPrice: 549,
    discountPercent: 27,
    image: 'https://m.media-amazon.com/images/I/41ZDJAd45AL.jpg',
    images: ['https://m.media-amazon.com/images/I/41ZDJAd45AL.jpg'],
    buyOnAmazonUrl: 'https://www.amazon.in/gp/product/1837995346?tag=mitoreboot-21&linkCode=ll2',
    stock: 35,
    isActive: true,
    doctorRecommended: false,
    keyBenefits: ['Brain-derived neurotrophic factor (BDNF) optimization', 'Mitochondrial nutrients for synaptic health', 'Practical daily routine recommendations']
  }
];

export async function seedShopAffiliateProducts() {
  const uri = process.env.MONGO_URI || process.env.MONGODB_URI || 'mongodb://localhost:27017/fastgluco';
  console.log('[Seed] Connecting to MongoDB...');
  await mongoose.connect(uri);

  console.log('[Seed] Ensuring 7 Core Shop Categories...');
  for (const cat of SHOP_CATEGORIES) {
    await ShopCategory.findOneAndUpdate(
      { name: cat.name },
      { $set: { name: cat.name, description: cat.description, isActive: true } },
      { upsert: true, new: true }
    );
  }

  console.log('[Seed] Seeding/Updating Affiliate Products...');
  let seededCount = 0;
  for (const prod of AFFILIATE_PRODUCTS) {
    const filter = (prod as any).buyOnAmazonUrl ? { buyOnAmazonUrl: (prod as any).buyOnAmazonUrl } : { name: prod.name };
    const update = {
      $set: {
        ...prod,
        regularPrice: prod.regularPrice || prod.price,
        offerPrice: prod.offerPrice || prod.price,
        discountPercent: prod.discountPercent || 0,
        availableStock: prod.stock,
        productStatus: 'active'
      }
    };
    await ShopProduct.findOneAndUpdate(filter, update, { upsert: true, new: true, setDefaultsOnInsert: true });
    seededCount++;
  }

  console.log(`[Seed] Successfully seeded ${seededCount} affiliate products across the 7 categories!`);
  await mongoose.disconnect();
}

if (require.main === module) {
  seedShopAffiliateProducts()
    .then(() => {
      console.log('[Seed] Done!');
      process.exit(0);
    })
    .catch((err) => {
      console.error('[Seed] Error:', err);
      process.exit(1);
    });
}
